### ISSUE TITLE
Cross-level reference link line can't be disabled

### ISSUE THREAD

**Issue by ykt-dev** [deepnight/ldtk#1000]
See attached video. 

https://github.com/deepnight/ldtk/assets/147815609/80274f37-3456-48e6-8b4e-0c55e012d563

Cross-level link is always visible on the receiving side, even if set to "Do not show".
This bug gives me a lot of visual clutter

**Comment by deepnight** [comment]
Thanks for reporting!

**Comment by deepnight** [comment]
Fixed in 1.5
