### ISSUE TITLE
CPU stuck in Entities and enums with big picture preview.

### ISSUE THREAD

**Issue by hnhhzy** [deepnight/ldtk#1007]
If I use a single larger image, either as Entities or using the large cut Enums preview image, it causes cpu lag, causing editing Entities or dragging with Enums to become unusually stuck. Here's one of my failing projects
[level1.zip](https://github.com/deepnight/ldtk/files/13513022/level1.zip)

**Comment by hnhhzy** [comment]
wrong in JsTools.createEntityPreview

**Comment by hnhhzy** [comment]
befor

https://github.com/deepnight/ldtk/assets/215678/fd3370bb-85d1-471f-81df-714c28d03e3a

after

https://github.com/deepnight/ldtk/assets/215678/5440df7d-5f93-4f5a-8ca5-09ac4e5760f6

**Comment by deepnight** [comment]
I merged the PR, but please not that your demo project is using 1100x1100 images as UI icons in the Entity list, which is quite too much for an icon. To get much better perfs, you should probably use smaller icons in your UI lists.

**Comment by hnhhzy** [comment]
After all, he's an entity, and I'm afraid he won't be able to maintain consistency with the final rendering of the map if other thumbnails are used

**Comment by deepnight** [comment]
I understand 🤔  
Maybe there's a way for LDtk to cache smaller size versions of the images when used in UI context, to avoid allocating huge images for very small screen space.

I'll create an issue for a later update.
