### ISSUE TITLE
Feature request: Hex grids

### ISSUE THREAD

**Issue by morgan3d** [deepnight/ldtk#102]
For simplicity, most tile editors support hex grids by keeping their regular rectangular structure and just rendering alternating rows offset by 1/2 a tile in each direction. This makes it a rendering hack that reduces implementation difficulty.

**Comment by deepnight** [comment]
Yes, this kind of hex is quite easy to implement, but the difficulty comes from hidden "dev costs", like supporting rules in a Hex based space. Even if it's a fake one, a single cell will have more neighbors than in a square space.

It would be easier to implement isometric first, but I will think about it :)
