### ISSUE TITLE
Update website with latest logo & screenshots

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#1023]
- [x] #1028
- [x] logo in header
- [x] home page rework (refs: vscode, firefox)
- [x] showcase page rework
- [x] showcase screenshots
- [x] add new recent games
- [x] static header menu

**Comment by Fypur** [comment]
https://fypur.itch.io/unnamed
Unnamed is a game about a robot platforming and exploring his way out of an abandonned factory. This is a hostile place, and he might find threats along the way... Use your jetpack and your swinging rope in order to navigate through levels and reach safety! I'll provide a banner, the logo, and an in game screenshot. 
![banner](https://github.com/deepnight/ldtk/assets/84095553/97f7188c-89b9-411e-8a59-47c5347640cf)
![Logo](https://github.com/deepnight/ldtk/assets/84095553/b4d61225-7332-48b2-aff6-9e3a265188b2)
![screenshot](https://github.com/deepnight/ldtk/assets/84095553/2a41fe4f-159a-46d0-b74e-fa113cca65bb)

**Comment by chosencharacters** [comment]
https://renainegame.com/

A fast paced platformer inspired by fighting games, pull stylish combos as you guide Aine, the Phoenix Knight, on her eternal quest to save the cute and colorful world of Lineria!

![renaine_logo-02-02 (1)](https://github.com/deepnight/ldtk/assets/22716528/7f24a683-fe93-4b31-8ad7-d774106a888f)

![renaine-screenshot-5](https://github.com/deepnight/ldtk/assets/22716528/ec13dfcb-61bb-414c-8565-d52388578c2a)
![renaine-screenshot-3](https://github.com/deepnight/ldtk/assets/22716528/b34a219e-4841-4656-859a-56ee5dca1b32)
![renaine-screenshot-2](https://github.com/deepnight/ldtk/assets/22716528/66d93785-ea12-493f-9695-1ede1627d7c0)

**Comment by valryon** [comment]
Hello!
Thanks for your work and this awesome tool <3
We're using it in

Cthuloot

It is a fun & spooky cooperative mutliplayer game where you'll join the best families of looters and search for mythical relics all around the world to please a mysterious Big Vilain. But beware of what lurks in the shadows and… in the other dimensions! 

Key Art
![Cthuloot_KeyArt](https://github.com/deepnight/ldtk/assets/155884/9f59f497-3679-4620-942a-a2da1fad2e47)

Screenshot
![cthuloot](https://github.com/deepnight/ldtk/assets/155884/b0bcd6d7-53bb-417b-9f80-1988d97e6f00)

Release planned for 2024 hopefully.

You played a very early build at Gameconf but hopefully it's really better now 😆

**Comment by GuvBubbs** [comment]
Comet

https://guv-bubbs.itch.io/comet

> _When her brother goes missing after a comet fragment hits, Stella has to overcome her fear of the dark and venture out of her village into the unknown to find him._

Comet is a puzzle adventure game for the Playdate.

Key Art
![THE-COVER2](https://github.com/deepnight/ldtk/assets/22435318/470ace56-30f8-45f6-8f73-98192f93be19)

Screenshot
![playdate-20231231-064450](https://github.com/deepnight/ldtk/assets/22435318/3e83fff1-1311-4e5e-96ee-a0dcbdfbf64c)

**Comment by Ailwuful** [comment]
Hello deepnight. LDtk is phenomenal, thank you.

Vinterget: https://store.steampowered.com/app/2328410/Vinterget/

Vinterget is a precision platformer in which you use a grappling tool to swing your ways through various challenges. Surpass your limits and ascend to the peak to meet Vinterget, the god of winter.

![Vinterget_Maincaps](https://github.com/deepnight/ldtk/assets/93070196/0f16b9b9-c594-42fa-9614-6bfbaf72583c)

![Runner_UBtzrsIyd0](https://github.com/deepnight/ldtk/assets/93070196/354a66da-559d-499b-9711-025e14f9fb3d)
![ss_c6061a398735c561b9cfbae800d0f80405eb1b2f](https://github.com/deepnight/ldtk/assets/93070196/ee1cbc2f-5e2a-478e-9e90-2a8a2875a477)

**Comment by pinwizkid** [comment]
Nixie now has a steam page that can be added!
https://store.steampowered.com/app/2584810/Nixie/

Here's some screenshot variety from the 3 worlds so far:
![Everlush (5)](https://github.com/deepnight/ldtk/assets/100722504/73af5206-5589-452b-bf8e-bb2c93b38283)
![1](https://github.com/deepnight/ldtk/assets/100722504/58e72ccf-3b6f-43cc-876b-6ed31de2fb4b)
![Port Valius (10)](https://github.com/deepnight/ldtk/assets/100722504/151ef838-27bf-4fe0-95d7-3cd3d113c42c)

**Comment by jan-martinek** [comment]
Hi, here’s a bit about **Gotta Bounce**. I’m using LDTK from the start and I’m still finding ways to make my work easier. I’m working with Playdate, so I started with the importer made by Nic Magnier and then moved to working directly with the JSON.

- link to the [website](https://www.mouflon.cloud)
- direct link to a [trailer](https://www.youtube.com/watch?v=L_tjigfVmes)

### Description

Gotta Bounce is a crank-controlled side-scroller for the Playdate. Without ever stopping their bounce, the mysterious protagonist goes through levels, shooting through obstacles and trying to understand the world — in part thanks to being able to send the world text messages and music recommendations. Releasing after a delay in early 2024.

### Key Art

![gb-art](https://github.com/deepnight/ldtk/assets/1490543/f323a2c9-b38b-4206-aeb7-f8e6008f977d)

### GIF

![pewpew](https://github.com/deepnight/ldtk/assets/1490543/fb6237cf-7c6c-46de-a576-1b8dba43a75b)

### Static screenshots

![screen-gb](https://github.com/deepnight/ldtk/assets/1490543/af62dec3-2117-4f8f-b9f0-ea0f85ed4586)

**Comment by deepnight** [comment]
Thanks for your games, they were all added to the website :)
