### ISSUE TITLE
[Feature Request] Remember where you were in Windows Explorer

### ISSUE THREAD

**Issue by chosencharacters** [deepnight/ldtk#1030]
My folder structure has cutscene files in a folder that is far away from the LDTK folder, each time I make a cutscene trigger entity with a file path field, I must navigate to the top folder and search the unique file extension (in my case, .tasc files, which are unique to my game)

It'd save some time if LDTK remembered where I was just looking at when inputting file path fields in Entities

**Comment by deepnight** [comment]
This should work as expected in 1.5. The last path used for each field will be stored in App settings.
