### ISSUE TITLE
1.5 Rendered tiles from nearby levels stick around

### ISSUE THREAD

**Issue by GuvBubbs** [deepnight/ldtk#1045]
Hey Deepnight

I think I've found out how to recreate this issue.

1. Zoom into a room to have it's edges render in.
2. Rather than zooming out, click on a nearby room. _(Once or many times)_
3. Zoom out to the world view to see a bunch of tiles rendered in.

https://www.loom.com/share/5801dde63ae54f0e8200a24fd533676c

**Comment by deepnight** [comment]
Fixed
