### ISSUE TITLE
Request - Mac's Control-click should cause a right click

### ISSUE THREAD

**Issue by Geokureli** [deepnight/ldtk#1048]
Continued from my conversation with @hk0i on #278 

On Mac devices, Control+click is identical to a right click, this is sort of a relic from the days when mac had no right-click button, but appears to still be used by some people, particularly mac trackpad users (which are fantastic little input devices), though you can also right click on them via a two-finger click.

I've noticed that when my mouse is over level tiles, LDtk uses the Mac Control in the same way as the Command key and the Windows CTRL key. Typically mac programs use the Command key to mirror the behavior of the CTRL key in Windows versions of the same program, where Mac's Control key is usually reserved for system level functions, like the right click behavior mentioned above. It seems like LDtk is preventing these system-functions from happening which is causing hk0i issues with Control+clicking to erase.

My suggestion is for LDtk to simply ignore the Control key and let the system handle it, this may allow us to right-click via the Control key, which seems to work in other parts of LDtk, for instance I can Control+click the layer to show the context menu that allows me to toggle visibility or edit the layer's settings.

**Comment by deepnight** [comment]
Ctrl+left click should now properly emulate right click for editing tools & context menus
