### ISSUE TITLE
Feature Request: Option for Individual Instances of Entities to have Adjustable Width and Height

### ISSUE THREAD

**Issue by Ursa-Frank** [deepnight/ldtk#106]
That can also be adjusted in the level editor. This way you can easily make large invisible hitboxes on a map that, for example, can be used as death zones, activators for cut scenes and events and can also be used to limit npc, player or camera movement. 

Thank you

**Comment by deepnight** [comment]
Sure, it's on the roadmap :)

**Comment by Ursa-Frank** [comment]
That's fantastic! Cheers mate 👍

**Comment by deepnight** [comment]
Duplicate
