### ISSUE TITLE
L-Ed JSON Schema Suggestions

### ISSUE THREAD

**Issue by RPGillespie6** [deepnight/ldtk#114]
I don't know how set in stone the JSON schema for L-Ed is, however since it is still in beta I'm assuming schema could still change. As such I have a few suggestions that I believe would lead to quality of life improvements.

1. Provide grid coordinates for everything

Currently it seems like entities, grid tiles, and int grid, etc. all have different methods of conveying their location in the map.

For example, an entity looks like this:

```
{ "__identifier": "Player", "__cx": 2, "__cy": 11, "defUid": 46, "x": 40, "y": 192, "fieldInstances": [...]}
```

Here, `__cx` and `__cy` are the grid coordinates with (0,0) being top left corner while `x` and `y` are the pixel coordinates of the pivot point. So far so good.

However, for non-entities, coordinates are missing. For example:

```
"gridTiles": [
    { "coordId": 102, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 103, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 104, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 105, "tileId": 31, "__tileX": 16, "__tileY": 32 },
```

In the case of tilesets, it seems like I have to derive the grid coordinates `__cx` and `__cy` myself from `coordId` using modulo operations and grid dimensions found in the `#/defs/layers` sections. In my opinion something like this would be much more helpful:

```
"gridTiles": [
    { "tileId": 31, "__cx": 8, "__cy": 16 },
    { "tileId": 31, "__cx": 8, "__cy": 17 },
    { "tileId": 31, "__cx": 8, "__cy": 18 },
    { "tileId": 31,"__cx": 8, "__cy": 19 },
```

Then I can tell at a glance that it is a vertical strip of tile 31 starting at (8,16) on the grid.

2. Provide tile mappings in `#/defs/layers`

It seems wasteful to keep listing `__tileX` and `__tileY` coordinates over and over:
```
    { "coordId": 102, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 103, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 104, "tileId": 31, "__tileX": 16, "__tileY": 32 },
    { "coordId": 105, "tileId": 31, "__tileX": 16, "__tileY": 32 },
```

It seems like it would be better if this mapping between tileId and its x,y on the tileset image only happens once. For example, if layer "Walls" only utilizes tile ids 31, 32, and 33:
```
"defs": {
    "layers": [
        {
            "identifier": "Walls",
            "type": "Tiles",
            "uid": 10,
            "gridSize": 16,
            "displayOpacity": 1.0,
            "intGridValues": [ { "identifier": null, "color": "#000000" } ],
            "autoTilesetDefUid": null,
            "autoRuleGroups": [],
            "autoSourceLayerDefUid": null,
            "tilesetDefUid": 2,
            "tilePivotX": 0,
            "tilePivotY": 0,
            "tiles": {
                31: { "__tileX": 16, "__tileY": 32 }
                32: { "__tileX": 32, "__tileY": 32 }
                33: { "__tileX": 48, "__tileY": 32 }
             }
        },
```

I am still learning the L-Ed schema, so please correct me if I have misinterpreted or missed something.

**Comment by deepnight** [comment]
Hi! 

Thanks for your great feedback here. Yes the format will evolve as updates go on until 1.0 . 

1. Grid coords 

About `entities`: I provided __cx/__cy here because there's a trap :)

If you have an entity with pivot at the *bottom*, the actual "gridY" coord you get from `floor( pixelY / gridSize )` would be wrong, you need `floor( pixelY / gridSize ) - 1`. Notice the **minus 1** here which is a fix because of a corner case: the bottom pixel of a grid cell is also the top pixel of the cell beneath. To avoid users to have inconsistent grid coords in such cases, I added "fixed" grid coords myself.

About the `gridTiles`, they will change in next update. Because of the features introduced in next update, I will need pixel based coords for tiles more than grid-based ones. This will become even more true when I'll introduce freely positioned tiles (see #32 ).

The new format looks like this:
```json
   "autoTiles":[
      {
         "ruleId":101,
         "results":[
            {
               "coordId":90,
               "tiles":[ 
                  { "tileId":169, "__xOff":0, "__yOff":-8, "__srcX":8, "__srcY":112 },
                  { "tileId":181, "__xOff":0, "__yOff":0, "__srcX":8, "__srcY":120 }
               ],
               "flips":0
            }
         ]
      }
   ]
```

2. Tile mapping

I agree it would be cleaner, but "__"-prefixed fields are specifically designed to be avoid the necessity of accessing data stored in defs. I only added these ones (named __srcX/__srcY now) because transforming tileId to actual tileset image coords is a little bit more complex (because of tiles padding/spacing options).

Anyway, I'll think about your suggestion of mapping as I clean up my code before next update release :)

**Comment by RPGillespie6** [comment]
> If you have an entity with pivot at the bottom, the actual "gridY" coord you get from floor( pixelY / gridSize ) would be wrong, you need floor( pixelY / gridSize ) - 1. Notice the minus 1 here which is a fix because of a corner case: the bottom pixel of a grid cell is also the top pixel of the cell beneath.

Forgive my ignorance, but couldn't that be resolved by making sure pivot points are within bounds of sprite though? If you have a 16x16 entity at grid(0,0), the pivot points could be either:
```
0,0     7,0     15,0
0,7     7,7     7,15
0,15    7,15    15,15
```
or floating point since grid dimensions are even:
```
0,0     7.5,0     15,0
0,7     7.5,7.5   7.5,15
0,15    7.5,15    15,15
```

The way it is currently setup, the pivot points on the right and bottom edges of the entity are outside the bounds of the sprite by a pixel. Perhaps this is intentional though? I guess you have to chose between:
- pivot points not having equal spacing between them
- pivot points being outside the bounds of the sprite
- pivot points using floating point coordinates.

> I agree it would be cleaner, but "__"-prefixed fields are specifically designed to be avoid the necessity of accessing data stored in defs

Ah, I didn't realize that. So is the canonical way of determining the location of a tile on the grid to do:
```
grid_x = coordId % (pxWid / grid_size)
grid_y = coordId / (pxWid / grid_size)
```
?

**Comment by deepnight** [comment]
I started working on a documentation generator today. 

The result is available here: https://github.com/deepnight/led/blob/master/JSON_DOC.md

I unified some tile coords based on your suggestion in 0.3.0, I'll probably make another cleanup pass before 1.0

**Comment by RPGillespie6** [comment]
Thanks. You can close this issue unless you want to use it as the dedicated spot for schema discussion.
