### ISSUE TITLE
Add "Level reference" to FieldDefs

### ISSUE THREAD

**Issue by TheNeikos** [deepnight/ldtk#129]
In the name of type-safety, this would allow to create 'teleportation zones' that directly point to another level, so that none are forgotten. Using a string would lead to a possible mismatch on renames/deletion of levels. And having an extra type just for that would make it easier to catch.

**Comment by deepnight** [comment]
I agree, that would be very useful 😊

**Comment by deepnight** [comment]
Related #33

**Comment by deepnight** [comment]
After implementing Entity refs (see #33), it feels like Level refs are quite redundant. 
For the Teleport example, the way to do it is:

1. Add an Entity Reference field (eg. named "target")
2. Optionally make it symmetrical
3. Add a Teleport near your level exit,
4. Add a Teleport near the next level entrance, 
5. Set the exit "target" to point to the entrance "target" (entity references work between levels)

Feel free to comment if you want to continue the discussion, I'll re-open the issue if new relevant elements are added.
