### ISSUE TITLE
Discord / community?

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#138]
Should we have a dedicated Discord channel, or a community forum somewhere? 🤔

**Comment by sh-dave** [comment]
Maybe [GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)?

**Comment by TheNeikos** [comment]
I do think it would make sense, even if just for those simple questions that could potentially spam this repository.

**Comment by HeadClot** [comment]
I would like to see a discord :)

**Comment by kaiiboraka** [comment]
I wouldn't mind a Discord server to join!

**Comment by saint11** [comment]
I definitely would joint one :)

**Comment by Leukai** [comment]
Ditto

**Comment by deepnight** [comment]
Discord server is on its way, I will add a link everywhere for next LDtk update :)

Here is the current invite link, feel free to share (be careful, wet paint everywhere): https://discord.gg/rpfYf4sxbJ
