### ISSUE TITLE
New option to separate Levels from Project when saving

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#140]
- Big performance issues with a single large JSON to parse 
 - Many slow down issues with Haxe Macro API
 - Bad for team work (SCM merges)

**Comment by SecretPocketCat** [comment]
Do you a specific format in mind?  

I, for one, would welcome separate defs and then a file for each lvl. I'm playing around with Godot and trying to import LEd lvls during runtime and it would be a whole lot nicer to watch the specific level json rather than the whole thing.

**Comment by deepnight** [comment]
Exactly :) I plan to have one Json for all the defs, and 1 Json per level in subfolder named after the project (to support mixing multiple projects in the same folder without conflicts). 

This will need some testing though, but it's the idea.

**Comment by deepnight** [comment]
Done in 0.6.3
