### ISSUE TITLE
External enum and entity sources

### ISSUE THREAD

**Issue by SecretPocketCat** [deepnight/ldtk#170]
This's just a basic FR/proposal, feel free to split this into multiple issues.

I really like the idea of external enums.
Related to #20 - just plain JSON would be nice as a source. (Though I think I'll be able to transpile C# to haxe and the enum syntax is super simple anyway.  

As far as the UI goes, I'd welcome a more 'aggressive approach' - as soon as LEd detects a change a popup could show up. Ideally, this could be skipped for additions, which could be automatic (and possibly name updates if there's an underlying value like there could be for the aforementioned JSON source).  

I'd love external entities (JSON or what-have-you). They could be done similar to enums (of course change detection would probably be way harder) or just be allowing to change the entities defs and prompting the user to refresh if the project file changes (I smell a possibility of save/watcher cycle here). This's possibly related to #140.

**Comment by deepnight** [comment]
Thanks for the suggestions, I'll see what can be done here :)

**Comment by FuzzySlipper** [comment]
I was coming here to suggest this! I was hoping to send my level designers updated project config file of entities/enums while preserving whatever levels they've already created. 

It seems like at the moment they'd have to either overwrite their whole project file or go through the updated file by hand and change their entities/enums

**Comment by deepnight** [comment]
Related #20

**Comment by deepnight** [comment]
I added support for Text files and JSON files in 1.1.2 update :)
