### ISSUE TITLE
Feature request: Composing levels into worlds

### ISSUE THREAD

**Issue by jackwlee01** [deepnight/ldtk#171]
It would be really awesome if there was a "worlds" view. Each world is composed of levels. In this context, levels would be more akin to "rooms" in the Metroidvania genre. The worlds view could serve a few purposes.

1. Allow compositions of rooms by level designers.
2. Allow re-ordering of rooms in 2 dimensions.
3. Visually show the overall topology of each world, and how the rooms fit together within it.
4. Allow creation of rooms of varying sizes, allowing levels designers to "plug the holes" of the world map with rooms from within the world view.

**Comment by deepnight** [comment]
Hi! 
The world editing is on the roadmap and will probably be available before 1.0 release 👍 

See issue: #47

**Comment by deepnight** [comment]
I started working on this big new feature, it'll be in 0.6 update :)

**Comment by jackwlee01** [comment]
Sweet, I can't wait to try it out!
