### ISSUE TITLE
Rotate and Flip tiles

### ISSUE THREAD

**Issue by profexorgeek** [deepnight/ldtk#180]
It would be nice to be able to rotate and flip (mirror) tiles.

**Use case:**
I often create a layer for the "stage" which is mostly the world geometry. In a platforming game this would be the platforms, in a top-down this might be the dungeon floor and walls. The stage layer can be an autotiled/intgrid layer.

Then I create another layer where I place decor items such as crates, banners, tables, etc. This layer is hand-crafted and tiles are typically only created in one orientation.

Tiled allows this using the X and Z keys as quick shortcuts for rotation and flipping of tiles.

**Comment by profexorgeek** [comment]
Note: I'm part of the FlatRedBall game engine community and we just discovered this tool. In the short term we plan to export as TMX since the engine already supports that while we test this. Long term we'll explore direct parsing. So if rotation/flipping are an option it would be nice if that exported to TMX as well.

**Comment by deepnight** [comment]
It's on the roadmap for 0.5.x release :) Related #69 

Rotations are not planned for now but I'll think about it 🤔

You might also want to wait for 0.5.x release before implementing LEd Json parser as the file format might change along the way.

**Comment by profexorgeek** [comment]
That's awesome, and thanks for the rapid reply.

One consideration: if you add rotation you only need to mirror on the X axis. Flipping horizontally and rotating 180 degrees is identical to flipping vertically.

Feel free to close this issue as a duplicate.

**Comment by deepnight** [comment]
I'll keep it open to remember my future-self to test rotations ;)

**Comment by deepnight** [comment]
Tiles flipping (X/Y) are now support supported in latest git version (not released yet)

**Comment by deepnight** [comment]
Rotation were added to 0.6 roadmap (need some testing though).
Issue: #207

**Comment by system32uwu** [comment]
hey, what about 90° rotations?
