### ISSUE TITLE
Default values for enums

### ISSUE THREAD

**Issue by SecretPocketCat** [deepnight/ldtk#181]
The default value input is missing for enums. Why is that exactly?

**Comment by deepnight** [comment]
There was an obscure (probably lazy) reason for that, but I can't remember it 🤔 I'll see what I can do :)

**Comment by deepnight** [comment]
To be done, this would required disambiguation between possible states:
1. field is *required*, and "null" value should be displayed as an error,
2. field is *optional*, but it has a default value if omitted,
3. field can really be "null" because it has no default value.

Related #392

**Comment by eliasdaler** [comment]
#392 is marked as "wontdo" now. Does this issue have a chance?

**Comment by deepnight** [comment]
I'm not sure about the usefulness of #392, thus the "wontdo" tag. But if I happen to add a distinct "optional" flag from the current "nullable" flag, this could change. 

This current issue ("default enum value") is, imho, far more useful, thus its current state.

**Comment by eliasdaler** [comment]
I agree. So if "default enum value" is happening, I'm happy! :D

**Comment by JustusPan** [comment]
vote +1

**Comment by deepnight** [comment]
Added in 1.2.0 🥳
