### ISSUE TITLE
Feature Request: Export layer as png

### ISSUE THREAD

**Issue by Quentie** [deepnight/ldtk#186]
**Idea**: export individual layers as png files (e.g. useful for Tile and Auto Layers)

**Why**: Some GameEngines (e.g. GBStudio) load levels from images rather than data and then slice them automatically into tiles (https://www.gbstudio.dev/docs/backgrounds/). 

I would really like to use this editor to create some levels for a Gameboy game ;)
@deepnight You have developed a great tool to quickly create levels. Thanks for the hard work!

**Comment by deepnight** [comment]
I'll see what can be done for 0.7 update :) Closing duplicate

**Comment by deepnight** [comment]
Will be available as experimental feature in 0.6.3

**Comment by deepnight** [comment]
![image](https://user-images.githubusercontent.com/1671695/104619379-186be100-568e-11eb-89bc-86d790fe34e5.png)

**Comment by Quentie** [comment]
@deepnight Wow super cool. Thanks a lot!
