### ISSUE TITLE
Auto-tiling

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#2]
Add support for auto-tiling (see: https://kidscancode.org/godot_recipes/2d/autotile_intro/)

Various useful links:
 - http://www.cr31.co.uk/stagecast/wang/stage.html
 - https://opengameart.org/content/seamless-tileset-template-ii
 - https://manual.yoyogames.com/The_Asset_Editors/Tile_Set_Editors/Auto_Tiles.htm

**Comment by JoshLee0915** [comment]
If I may ask, doesn't the rule based tiles fill the use case for this or am I mistaken?

**Comment by deepnight** [comment]
It's similar, the RPG map auto-tiling could be some "generate many rules at once" system, but it also should work in real Tile layers, not auto-layers (ie. tiles in Tile layers should update as you paint, like in Tiled for example)

Also, you could replicate a full auto-tiling setup using rules, but this would require many many rules to do so. Users would probably get bored after the second set 😄

**Comment by JoshLee0915** [comment]
Ah, that is what I was curious about. I know I am using the tiling rules rn to replicate the behavior and while I love the control it offers you do have to define quite a few rules to replicate that functionality. Though being able to mirror rules is a life saver there as it helps a lot.

Thank you for answering my question!

**Comment by lmerriam** [comment]
Big +1 to this, or to having "template" rulesets for all the common tilesets. There is a lot of initial time cost to setting up standard autotiling rules that I know a ton of other users are also going to have to individually replicate.

**Comment by Manukineko** [comment]
Hello,
Is that still an upcoming feature ?
It is set for the 1.0 milestone but it is not there yet.
It's really hard to build a regular top-down 16-tiles ruleset currently. Is there any "template" someone could share ?

**Comment by agorgl** [comment]
Waiting for this too!

**Comment by BrunoDSL** [comment]
Considering how non-existent the documentation for the rules are, this feature would help quite a bit.

**Comment by CashWasabi** [comment]
The first link for the godot recipes stopped working. Here's the new working link: https://kidscancode.org/godot_recipes/3.x/2d/autotile_intro/

**Comment by deepnight** [comment]
Done in 1.2.0, through the new Assistant
