### ISSUE TITLE
Missing type declaration on LDTK compile of renderer.debug.hxml

### ISSUE THREAD

**Issue by jcmonkey** [deepnight/ldtk#202]
i updated all the old LED dependicies with proper git version, and installed the new ldtk git versions.
so on haxe remderer.debug.hxml 

gamedev@gamedev:~/Code/Git$ cd ldtk
gamedev@gamedev:~/Code/Git/ldtk (master)$ ls
app                JSON_DOC.md           README.md            src.data      tests
art                lastBuildVersion.txt  renderer.debug.hxml  src.doc
CHANGELOG.md       LICENSE               renderer.hxml        src.externs
doc.hxml           main.debug.hxml       res                  src.main
JSON_CHANGELOG.md  main.hxml             run.cmd              src.renderer

gamedev@gamedev:~/Code/Git/ldtk (master)$ haxe renderer.debug.hxml 

src.renderer/App.hx:35: characters 99-100 : Missing type declaration

gamedev@gamedev:~/Code/Git/ldtk (master)$ 

this is after all the reinstalling of new git packages, and the other instructions 

this looks to be the culprit, but it has Array<string>, so i dont know what the compiler wants here 

       // App arguments
           var electronArgs : Array<String> = try electron.renderer.IpcRenderer.sendSync("getArgs") catch(_) [];

just figure i would report this, not sure if the is really serious or not. but let me know what you think.

**Comment by deepnight** [comment]
I'll check that on Monday, thanks for reporting :)

**Comment by deepnight** [comment]
Could you please post your `haxelib list` result?

**Comment by jcmonkey** [comment]
actuate: [1.8.9]
box2d: [1.2.3]
castle: [git]
deepnightLibs: 1.0.50 1.0.52 1.0.53 [git]
domkit: 0.2.0 [git]
electron: git [dev:/home/gamedev/.haxe/lib/electron/git]
flixel-addons: [2.9.0]
flixel-demos: [2.7.3]
flixel-templates: [2.6.5]
flixel-tools: [1.4.4]
flixel-ui: [2.3.3]
flixel: [4.8.1]
format: [3.5.0]
hashlink: [0.1.0]
heaps: [git]
HIDE: [0.4.8]
hldx: [1.10.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]
hscript: 2.4.0 [git]
hx3compat: 1.0.3 [git]
hxbit: 1.5.0 [git]
hxcpp-debug-server: 1.2.4 [dev:/home/gamedev/.vscode/extensions/vshaxe.hxcpp-debugger-1.2.4/hxcpp-debug-server]
hxcpp: [4.1.15]
hxjsonast: [1.0.1]
hxnodejs: [12.1.0] git
json2object: [3.8.1]
layout: [1.2.1]
ldtk-haxe-api: [git]
led-haxe-api: [1.0.13]
lime-samples: [7.0.0]
lime: [7.8.0]
node-webkit: [1.0.7]
openfl-samples: [8.7.0]
openfl: [9.0.2]
redistHelper: [git]
systools: [1.1.0]
test-adapter: 1.2.10 [dev:/home/gamedev/.vscode/extensions/vshaxe.haxe-test-adapter-1.2.10/test-adapter]
zerolib-flixel: [git]
zerolib: [0.8.0]

**Comment by deepnight** [comment]
Maybe it's related to `hxnodejs` version? Try installing the one from git:

```
haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
```

**Comment by jcmonkey** [comment]
just tried that, no luck, still get the error. 
though when i comment it out and added 

// App arguments
//var electronArgs : Array<String> = try electron.renderer.IpcRenderer.sendSync("getArgs") catch(_) [];
//electronArgs.shift();
//args = new dn.Args( electronArgs.join(" "), true );
//LOG.add("BOOT", args.toString());
LOG.add("BOOT", "some string thing");

and it moved past that part to another issue

gamedev@gamedev:~/Code/Git/ldtk (master)$ haxe renderer.debug.hxml 
src.renderer/App.hx:88: characters 14-15 : Missing type declaration

// Restore settings
		LOG.fileOp("Loading settings...");
		dn.LocalStorage.BASE_PATH = JsTools.getExeDir();
		if( js.Browser.window.localStorage.getItem("session")!=null ) {
			// Migrate old sessionData
			LOG.fileOp("Migrating old session to settings files...");
			var raw = js.Browser.window.localStorage.getItem("session");
			var old : AppSettings =
				try haxe.Unserializer.run(raw)
				catch( err:Dynamic ) null;
			if( old!=null )
				try {
					if( old.recentProjects!=null )
						for(i in 0...old.recentProjects.length)
							old.recentProjects[i] = StringTools.replace(old.recentProjects[i], "\\", "/");
					dn.LocalStorage.writeObject("settings", true, old);
// this is my line 88				} catch(e) {}

			js.Browser.window.localStorage.removeItem("session");
		}

so i dont know what this means now.

though the 2 things in common with these errors is the try and catch statements. 
but im not a haxe master to know if that means anything.

**Comment by deepnight** [comment]
Hmmm that's really weird... What Haxe version do you use?

**Comment by jcmonkey** [comment]
gamedev@gamedev:~$ haxe --version
4.0.5

**Comment by deepnight** [comment]
I use 4.1.4, but I don't think it should make any difference...

Let's check everything:
 - update Haxe to latest available version (https://haxe.org)
 - update all haxelibs:
```
haxelib git heaps https://github.com/HeapsIO/heaps.git
haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
haxelib git electron https://github.com/tong/hxelectron.git
haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git
haxelib git castle https://github.com/ncannasse/castle.git
```

**IMPORTANT**: If you're building LDtk from branch **dev-0.6.0**, you should also switch `ldtk-haxe-api` to **dev-0.6.0** branch.

```
haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git dev-0.6.0
```

Build `main` electron part:
```
haxe main.debug.hxml
```

Build `renderer` electron part:
```
haxe renderer.debug.hxml
```

**Comment by jcmonkey** [comment]
i did all that, then i deleted all my stuff, then redid it, and still i get the missing type declaration.

im not sure what changed from LED, but i installed LED perfectly fine with out no issues.

**Comment by deepnight** [comment]
What's weird here is that the error is not pointing any actual error in code.

Are you on `dev-0.6.0` or `master` branch?

**Comment by deepnight** [comment]
Could you please try adding `Dynamic` type on the indicated line?

```haxe
try {
 // ...
} catch(e:Dynamic) {}
```

**Comment by jcmonkey** [comment]
i get this on master, and on dev-0.6.0 now, seems the dynamic thing allowed to bypass those first errors

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxe renderer.debug.hxml 
src.data/data/def/TilesetDef.hx:88: lines 88-112 : Object requires field averageColors
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int, pxHei : Int, padding : Int, opaqueTiles : Null<Array<Int>>, identifier : String } should be ldtk.TilesetDefJson
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int,... has no field averageColors
src.data/data/Level.hx:35: lines 35-41 : Object requires fields: worldY, worldX
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } should be ldtk.LevelJson
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } has no field worldX
/home/gamedev/.haxe/lib/deepnightLibs/1,0,53/src/dn/LocalStorage.hx:15: characters 12-13 : Missing type declaration
gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$

**Comment by deepnight** [comment]
If you use 0.6 branch on LDtk, you also need to switch to 0.6 branch for the LDtk-haxe-api :)

**Comment by jcmonkey** [comment]
gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ ls
genSamples.hxml  LICENSE    samples  tests
haxelib.json     README.md  src      tidy.cmd

**Comment by jcmonkey** [comment]
still same results :(

**Comment by deepnight** [comment]
Did you run the following command?

```
haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git dev-0.6.0
```
(notice the **branch name** right after the git url)

Should output something like:
```
Installing ldtk-haxe-api from https://github.com/deepnight/ldtk-haxe-api.git branch: dev-0.6.0
Library ldtk-haxe-api current version is now git
```

**Comment by jcmonkey** [comment]
`gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git dev-0.6.0
You already have ldtk-haxe-api version git installed.
Overwrite branch: <unspecified> with "dev-0.6.0" [y/n/a] ? y
Installing ldtk-haxe-api from https://github.com/deepnight/ldtk-haxe-api.git branch: dev-0.6.0
Library ldtk-haxe-api current version is now git
Installing dependency deepnightLibs 1.0.54
Downloading deepnightLibs-1,0,54.zip...
Download complete: 0.26KB in 0.6s (0.4KB/s)
Download complete: 2.39MB in 2.3s (1004.4KB/s)
Installing deepnightLibs...
Done

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxe main.debug.hxml 

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxe renderer.debug.hxml 

src.data/data/def/TilesetDef.hx:88: lines 88-112 : Object requires field cachedPixelData
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int,... has extra field opaqueTiles
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int, pxHei : Int, padding : Int, opaqueTiles : Null<Array<Int>>, identifier : String } should be ldtk.TilesetDefJson
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int,... has no field cachedPixelData
src.data/data/inst/LayerInstance.hx:76: lines 76-95 : error: { src : Array<Int>, px : Array<Int>, f : Int, d : Array<Int> } has no field t
src.data/data/inst/LayerInstance.hx:76: lines 76-95 :  have: Array<{ src, px, f, d }>
src.data/data/inst/LayerInstance.hx:76: lines 76-95 :  want: Array<ldtk.Tile>
src.data/data/inst/LayerInstance.hx:104: lines 104-115 : Object requires field t
src.data/data/inst/LayerInstance.hx:104: lines 104-115 : For function argument 'x'
src.data/data/inst/LayerInstance.hx:50: lines 50-121 : Object requires fields: __tilesetRelPath, __tilesetDefUid
src.data/data/inst/LayerInstance.hx:50: lines 50-121 : { seed : Int, pxOffsetY : Int, pxOffsetX : Int, levelId : Int, layerDefUid : Int, intGrid : Array<{ v : Int, coordId : Int }>, gridTiles : Array<ldtk.Tile>, entityInstances : Array<ldtk.EntityInstanceJson>, autoLayerTiles : Array<ldtk.Tile>, __type : String, __pxTotalOffsetY : Int, __pxTotalOffsetX : Int, __opacity : Float, __identifier : String, __gridSize : Int, __cWid : Int, __cHei : Int } should be ldtk.LayerInstanceJson
src.data/data/inst/LayerInstance.hx:50: lines 50-121 : { seed : Int, pxOffsetY : Int, pxOffsetX : Int, levelId : Int, layerDefUid : Int, intGrid : Array<{ v : Int, coordId : Int }>, gridTiles : Array<ld... has no field __tilesetDefUid
src.data/data/Level.hx:35: lines 35-41 : Object requires fields: worldY, worldX
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } should be ldtk.LevelJson
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } has no field worldX
src.data/data/Project.hx:64: lines 64-76 : Object requires field worldLayout
src.data/data/Project.hx:64: lines 64-76 : { nextUid : Int, minifyJson : Bool, levels : Array<ldtk.LevelJson>, jsonVersion : String, exportTiled : Bool, defs : ldtk.DefinitionsJson, defaultPivotY : Float, defaultPivotX : Float, defaultGridSize : Int, bgColor : String } should be ldtk.ProjectJson
src.data/data/Project.hx:64: lines 64-76 : { nextUid : Int, minifyJson : Bool, levels : Array<ldtk.LevelJson>, jsonVersion : String, exportTiled : Bool, defs : ldtk.DefinitionsJson, defaultP... has no field worldLayout
/home/gamedev/.haxe/lib/deepnightLibs/1,0,53/src/dn/LocalStorage.hx:15: characters 12-13 : Missing type declaration
gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ 
`

**Comment by deepnight** [comment]
Sorry to insist, but as you're trying to build from the latest daily version from Git. Therefore, you should **_always_**:

 - **pull** latest git changes on the LDtk repo (in your case, it seems it wasn't updated),
 - make sure you're using corresponding up-to-date haxelibs (see [README](https://github.com/deepnight/ldtk/blob/master/README.md))
 - update haxelibs everytime (`haxelib update`)

Please do _everything_ above and check again 🙏

**Comment by jcmonkey** [comment]
`
gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ haxelib list
actuate: [1.8.9]                                                            
box2d: [1.2.3]                                                              
castle: [git]                                                               
deepnightLibs: 1.0.50 1.0.52 [1.0.53] 1.0.54 git                            
domkit: 0.2.0 [git]                                                         
electron: git [dev:/home/gamedev/.haxe/lib/electron/git]                    
flixel-addons: [2.9.0]                                                      
flixel-demos: [2.7.3]                                                       
flixel-templates: [2.6.5]
flixel-tools: [1.4.4]
flixel-ui: [2.3.3]
flixel: [4.8.1]
format: [3.5.0]
hashlink: [0.1.0]
heaps: [git]
HIDE: [0.4.8]
hldx: [1.10.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]
hscript: 2.4.0 [git]
hx3compat: 1.0.3 [git]
hxbit: 1.5.0 [git]
hxcpp-debug-server: 1.2.4 [dev:/home/gamedev/.vscode/extensions/vshaxe.hxcpp-debugger-1.2.4/hxcpp-debug-server]
hxcpp: [4.1.15]
hxjsonast: [1.0.1]
hxnodejs: [12.1.0] git
json2object: [3.8.1]
layout: [1.2.1]
ldtk-haxe-api: [git]
led-haxe-api: [1.0.13]
lime-samples: [7.0.0]
lime: [7.8.0]
node-webkit: [1.0.7]
openfl-samples: [8.7.0]
openfl: [9.0.2]
redistHelper: [git]
systools: [1.1.0]
test-adapter: 1.2.10 [dev:/home/gamedev/.vscode/extensions/vshaxe.haxe-test-adapter-1.2.10/test-adapter]
zerolib-flixel: [git]
zerolib: [0.8.0]
gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ 

-------------------------------------------------------------------------------------------------------------

gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ git pull
Already up to date.
gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ haxe --version
4.1.4
gamedev@gamedev:~/.haxe/lib/ldtk-haxe-api/git (dev-0.6.0)$ 

------------------------------------------------------------

gamedev@gamedev:~/Code/Git/ldtk (master)$ git checkout dev-0.6.0

Branch 'dev-0.6.0' set up to track remote branch 'dev-0.6.0' from 'origin'.
Switched to a new branch 'dev-0.6.0'

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ git pull
Already up to date.

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ cd app

gamedev@gamedev:~/Code/Git/ldtk/app (dev-0.6.0)$ npm i
npm WARN ldtk@0.6.0-beta No license field.

audited 247 packages in 1.764s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

gamedev@gamedev:~/Code/Git/ldtk/app (dev-0.6.0)$ cd ..

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxe main.debug.hxml 

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ haxe renderer.debug.hxml 

/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/def/TilesetDef.hx:118: characters 25-39 : Class<dn.Color> has no field intToHex3_ARGB
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/inst/LayerInstance.hx:192: characters 8-18 : Type not found : dn.Version
src.data/data/inst/LayerInstance.hx:195: characters 8-18 : Type not found : dn.Version
src.data/data/inst/LayerInstance.hx:220: characters 10-20 : Type not found : dn.Version
src.data/data/inst/LayerInstance.hx:229: characters 10-20 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/def/TilesetDef.hx:149: characters 47-61 : Class<dn.Color> has no field hex3ToInt_ARGB
src.data/data/Project.hx:67: characters 48-58 : Type not found : dn.Version
src.data/data/Project.hx:69: characters 7-17 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/Definitions.hx:272: characters 27-40 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
src.data/data/def/EntityDef.hx:144: characters 28-41 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.renderer/App.hx:56: characters 31-40 : Class<dn.Process> has no field rprintAll
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.renderer/page/CrashReport.hx:23: characters 36-45 : Class<dn.Process> has no field rprintAll
src.renderer/App.hx:242: characters 38-47 : Class<dn.Process> has no field rprintAll
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.renderer/App.hx:167: characters 39-55 : dn.Args has no field getAllSoloValues (Suggestions: getSoloValue, getLastSoloValue)
src.renderer/WorldTool.hx:207: characters 23-36 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
src.renderer/WorldTool.hx:80: characters 28-41 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/Definitions.hx:354: characters 27-40 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
src.data/data/Definitions.hx:125: characters 25-38 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/def/LayerDef.hx:259: characters 27-40 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
src.renderer/display/WorldRender.hx:133: characters 15-21 : dn.heaps.TiledTexture has no field resize
src.renderer/display/LevelRender.hx:448: characters 25-43 : Type not found : dn.heaps.PixelGrid
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/Project.hx:154: characters 25-38 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.data/data/Definitions.hx:437: characters 24-37 : Class<dn.Lib> has no field getArrayIndex (Suggestion: getArrayIdx)
/home/gamedev/Code/Git/ldtk/src.renderer/import.hx:5: characters 8-18 : Type not found : dn.Version
src.renderer/display/WorldRender.hx:261: characters 25-43 : Type not found : dn.heaps.PixelGrid
src.renderer/display/WorldRender.hx:272: characters 25-43 : Type not found : dn.heaps.PixelGrid

gamedev@gamedev:~/Code/Git/ldtk (dev-0.6.0)$ 


`

**Comment by deepnight** [comment]
As you might notice in errors above, the dn.* classes seem to be out-of-date:

If you read carefully the haxelib list result, you'll see:
```
deepnightLibs: 1.0.50 1.0.52 [1.0.53] 1.0.54 git
```

Which means you're using 1.0.53 version, and not git. Run:

```
haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
```

See README: https://github.com/deepnight/ldtk#installing-haxe-libs

**Comment by deepnight** [comment]
By the way, you can safely remove led-haxe-api, as it's deprecated (not related, just tidying things up here):

```
haxelib remove led-haxe-api
```

**Comment by jcmonkey** [comment]
running this changed my version of deepnight lib from git to non git. 

gamedev@gamedev:~/Code/Git/ldtk/app (dev-0.6.0)$ haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git
You already have ldtk-haxe-api version git installed.
Updating ldtk-haxe-api version git ...
ldtk-haxe-api was updated
Library ldtk-haxe-api current version is now git
Installing dependency deepnightLibs 1.0.54
You already have deepnightLibs version 1.0.54 installed
Set deepnightLibs to version 1.0.54 [y/n/a] ? y
Library deepnightLibs current version is now 1.0.54
gamedev@gamedev:~/Code/Git/ldtk/app (dev-0.6.0)$ 


so i manually changed it back, and recompiled and it works now. 

what you should do is in the docs let ppl know that this will change from the git version to the non git version is they select yes 

originaly i had it set to git version. but thats ok, thats all figured out now and i can get back to game dev :D 

thanks for all the help with this.

**Comment by deepnight** [comment]
Great :) Glad I helped!
