### ISSUE TITLE
Crash on 0.5.1

### ISSUE THREAD

**Issue by sgbraunstein** [deepnight/ldtk#206]
My friend and I are experiencing a crashes with the latest version (0.5.1) on two different pcs -- 0.4.0 worked just fine for us, but after we updated in place (from within LED), our old files wouldn't open. We get an error like this:

![unnamed](https://user-images.githubusercontent.com/480743/98631713-f5a11180-2358-11eb-96ba-4d26ada63d19.png)

Here's a file that crashes when we try to open it: 
[boss_arena_billiard.json.zip](https://github.com/deepnight/ldtk/files/5515004/boss_arena_billiard.json.zip)

Making new files with 0.5.1 seems to work just fine, and they open nicely!
I can post the spritesheet if you need it, but it seems like that wouldn't be part of the issue.

Thanks for this FANTASTIC tool! Let us know if there's anything else we can do to help. Until then, we'll be on 0.4.0! Is there a link to download old versions somewhere?

Cheers

**Comment by deepnight** [comment]
Oh! Sorry about this one, I'll fix it asap!

**Comment by deepnight** [comment]
Ok found the culprit. A fix will be live today 👍

**Comment by sgbraunstein** [comment]
Hi! Sorry, the clipboard button didn't work as the application was hanging. Should have mentioned that!

OH MY GOD, WE LOVE YOU. Thanks for fixing our pipeline! We'll join the discord and be your loyal hounds!

**Comment by deepnight** [comment]
If you like & share the app, that's more than enough 😅😅

**Comment by deepnight** [comment]
The 0.5.2 is live, and should fix your crash
