### ISSUE TITLE
ldtk-0.5.2-beta - Object requires field averageColors

### ISSUE THREAD

**Issue by n67094** [deepnight/ldtk#208]
Hi,

When running **haxe renderer.hxml** this is what I got (Haxe 4.1.4):

$: npm run compile

> ldtk@0.5.2-beta compile
> cd ../  &&  haxe main.hxml  &&  haxe renderer.hxml

src.data/data/def/TilesetDef.hx:88: lines 88-112 : Object requires field averageColors
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int, pxHei : Int, padding : Int, opaqueTiles : Null<Array<Int>>, identifier : String } should be ldtk.TilesetDefJson
src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int,... has no field averageColors
src.data/data/Level.hx:35: lines 35-41 : Object requires fields: worldY, worldX
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } should be ldtk.LevelJson
src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } has no field worldX

**Comment by n67094** [comment]
Oh I didn't see but your pipline faild. Someone should bring croissants then,

**Comment by deepnight** [comment]
There's some cleanup that needs to be done in the way I manage branches between LDtk repo and HaxeAPI repo 🤔

**Comment by deepnight** [comment]
It should be fixed. 

- if you build LDtk using **master** branch, you should also use master for `ldtk-haxe-api`
- if you build LDtk using **dev-0.6.0** branch, you should also use dev-0.6.0 for `ldtk-haxe-api`
