### ISSUE TITLE
Recent project files list reset when updating

### ISSUE THREAD

**Issue by LeHaine** [deepnight/ldtk#212]
**Issue:**  A minor issue when updating to a new version after having already open project files previously, the list of recent files are removed from start screen. 
**What I expected to happen**: After updating I would figure I would still see my recent files I had just opened. 

Nothing major here. Just something I noticed when updating 0.5.2 just now.

Thanks!

**Comment by deepnight** [comment]
That's related to the fact `userSettings` are stored in the app folder 🤔  I'll see if I can actually fix that in some way...

**Comment by deepnight** [comment]
This will be fixed in 0.6 update :)

Unfortunately, the effect of the fix will only happen _after_ the update itself: user settings will be lost one last time 🤷
