### ISSUE TITLE
gridTiles json scheme doesn't match documentation

### ISSUE THREAD

**Issue by ArjunNair** [deepnight/ldtk#213]
While working on on importer for Godot, I noticed that the json exported schema (the .ldtk file) for gridTiles doesn't match the documentation.

For example, this is what the documentation says gridTiles should look like:
`"gridTiles": [
	{ "coordId": 55, "tileId": 15, "__x": 224, "__y": 96, "__srcX": 96, "__srcY": 64 },
	{ "coordId": 56, "tileId": 15, "__x": 256, "__y": 96, "__srcX": 96, "__srcY": 64 },
	{ "coordId": 65, "tileId": 11, "__x": 32, "__y": 128, "__srcX": 160, "__srcY": 32 },
	{ "coordId": 71, "tileId": 15, "__x": 224, "__y": 128, "__srcX": 96, "__srcY": 64 },
	{ "coordId": 72, "tileId": 15, "__x": 256, "__y": 128, "__srcX": 96, "__srcY": 64 },
	{ "coordId": 81, "tileId": 17, "__x": 32, "__y": 160, "__srcX": 160, "__srcY": 64 }
}`

However, the ldtk output was:
`"gridTiles": [
					{ "px": [64,80], "src": [496,0], "f": 0, "d": [139,31] },
					{ "px": [80,80], "src": [512,0], "f": 0, "d": [140,32] },
					{ "px": [96,80], "src": [528,0], "f": 0, "d": [141,33] },
					{ "px": [64,96], "src": [496,16], "f": 0, "d": [166,69] },
					{ "px": [80,96], "src": [512,16], "f": 0, "d": [167,70] },
					{ "px": [96,96], "src": [528,16], "f": 0, "d": [168,71] },
					{ "px": [64,112], "src": [496,32], "f": 0, "d": [193,107] },
					{ "px": [80,112], "src": [512,32], "f": 0, "d": [194,108] },
....
`

Some explanation on how these are remapped from previously would be useful.

Edit 1: Using version 0.5.2-beta
Edit 2: Attached full ldtk file for completeness.
[example_map_new.zip](https://github.com/deepnight/ldtk/files/5522359/example_map_new.zip)

**Comment by deepnight** [comment]
Hmm.. That definitely looks like some oversight on my side 🤔

**Comment by deepnight** [comment]
I'll update the doc today.

Note that the web manual is often less up-to-date than the automated markdown doc: https://github.com/deepnight/ldtk/blob/master/JSON_DOC.md
