### ISSUE TITLE
Build issue on mac (haxe renderer.debug.hxml)

### ISSUE THREAD

**Issue by teachtocode** [deepnight/ldtk#215]
When i try to execute haxe renderer.debug.hxml , I am getting this error.
src.renderer/App.hx:56: characters 31-40 : Class<dn.Process> has no field rprintAll
src.renderer/page/CrashReport.hx:23: characters 36-45 : Class<dn.Process> has no field rprintAll
src.renderer/App.hx:244: characters 38-47 : Class<dn.Process> has no field rprintAll
src.renderer/App.hx:165: characters 18-34 : dn.Args has no field getAllSoloValues (Suggestions: getSoloValue, getLastSoloValue)
src.renderer/App.hx:165: characters 13-36 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

**Comment by deepnight** [comment]
You should update haxe libs, from a command line:

```
haxelib update
```

**Comment by teachtocode** [comment]
Still the same issue

 haxelib update     
Checking hxnodejs
hxnodejs was updated
Checking deepnightLibs
deepnightLibs was updated
Checking format
Checking ldtk-haxe-api
ldtk-haxe-api was updated
Checking castle
castle was updated
Checking electron
electron was updated
Checking heaps
heaps was updated
Done
  ³ base  ~/D/ldtk-master 
 haxe renderer.debug.hxml               (base) 12.4s  Thu Nov 12 09:34:26 2020
src.renderer/App.hx:56: characters 31-40 : Class<dn.Process> has no field rprintAll
src.renderer/page/CrashReport.hx:23: characters 36-45 : Class<dn.Process> has no field rprintAll
src.renderer/App.hx:244: characters 38-47 : Class<dn.Process> has no field rprintAll
src.renderer/App.hx:165: characters 18-34 : dn.Args has no field getAllSoloValues (Suggestions: getSoloValue, getLastSoloValue)
src.renderer/App.hx:165: characters 13-36 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
 !   ³ base  ~/D/ldtk-master 
 haxe --version   
4.1.4

**Comment by deepnight** [comment]
Oh, it seems that you're not using the GIT versions for some important libs:

```
haxelib git heaps https://github.com/HeapsIO/heaps.git

haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git

haxelib git electron https://github.com/tong/hxelectron.git

haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git

haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git

haxelib git castle https://github.com/ncannasse/castle.git
```

**Comment by teachtocode** [comment]
Hi , thanks for your help , its working now . So i have one question , is there any build setup for mac like windows setup , or do i have to build it from the electron app ?

**Comment by deepnight** [comment]
There is a Github Action script that builds the Mac distrib, but I've never done that myself 🤔  

See: https://github.com/deepnight/ldtk/blob/master/.github/workflows/macos.yml
