### ISSUE TITLE
Exposing TileId directly in TileInstances

### ISSUE THREAD

**Issue by JoshLee0915** [deepnight/ldtk#217]
I am not sure if this is a duplicate of #114 but #114 seams a bit outdated.

A bit of background, I heard about LDtk earlier this week actually and have fell in love with the tool. I use Godot a lot for creating games and while its tile system is quite powerful, its UX has always been wanting and makes it a bit clumsy to work with. Along with that I tend to work with people who are used to RPG or Game Maker and tend to be hesitant to learn how to use the tools of a new engine, but seem very keen on LDtk. 

Due to this I decided to begin work on an import plugin for Godot to allow it to create scenes using LDtk. I am still in the research phase but I hit a small stumbling block while trying to figure out how to map the tiles and create the tileset resource in Godot using the info stored by LDtk. 

The main issue is LDtk seems to expect that you are going to be referencing an atlas directly, giving pixel coordinates for the tile in the tilesets. This is problematic for engines like Godot or Unity which use an intermediate data structure to reference tilesets and do not give easy access to the underlying image. Unity (unless it changed from when I last used it) treats every tile as an independent game object while Godot uses a structure called a TileSet which is really an array that contains the tiles and metadata for them that is referenced by an id or index.

I knew that LDtk had an underlying tileId it used internally and if I had access to that it would make it a lot easier to map the data (at least in Godot). After more digging I found out that we do in fact have the tileId exposed through the `d` field in the tile instances. I dismissed this field my first couple times through the doc since it is marked as for internal editor use.

And with all that I get to my point. I feel it would be very handy and beneficial to directly expose the tileId field on Tile instances instead of having it hidden in the d field. I know there would be some duplication of data since it is already in the `d` field, but I feel it would make the JSON more self describing and since `d` is for use in the editor it would allow `d` to be altered as needed without worry about breaking importers that may be using the tileId stored inside of it.

If this sounds like it may be a good idea I would be happy to work on adding the change in and submitting a PR for it.

**Comment by deepnight** [comment]
Hi! 
This will be changed in 0.6 :)
The new format will be:

Value | Type | Description
-- | -- | --
`d`<br/> ![Generic badge](https://img.shields.io/badge/Changed_0.6.0-green.svg)  | Array&nbsp;of&nbsp;Int | Internal data used by the editor.<br/>		For auto-layer tiles: `[ruleId, coordId]`.<br/>		For tile-layer tiles: `[coordId]`.
`f` | Int | "Flip bits", a 2-bits integer to represent the mirror transformations of the tile.<br/>		 - Bit 0 = X flip<br/>		 - Bit 1 = Y flip<br/>		 Examples: f=0 (no flip), f=1 (X flip only), f=2 (Y flip only), f=3 (both flips)
`px`  | Array&nbsp;of&nbsp;Int | Pixel coordinates of the tile in the **layer** (`[x,y]` format). Don't forget optional layer offsets, if they exist!
`src` | Array&nbsp;of&nbsp;Int | Pixel coordinates of the tile in the **tileset** (`[x,y]` format)
`t`<br/> ![Generic badge](https://img.shields.io/badge/Added_0.6.0-green.svg)  | Int | The *Tile ID* in the corresponding tileset.

**Comment by JoshLee0915** [comment]
Nice! I will make a note of that for when 0.6 releases. 

I do have one more question if you do not mind. Are there plans to allow metadata to be defined for tiles in a tileset? I wanted to make another issue discussing, it as even being able to set a human readable name for a tile could be handy for importers much less being able to do things like auto generate collision meshes/shapes, but I do not want to make a new issue if its already planned.

This is another feature I would be happy to attempt to implement myself and make a PR for if there is interest in including it into the tool.
