### ISSUE TITLE
Region Layer

### ISSUE THREAD

**Issue by Sipondo** [deepnight/ldtk#221]
One feature that I think is a bit of a low hanging fruit, yielding great benefit for low development time, would be to introduce a "region layer".
Regions are objects invisible to the player that can be used to define area-based events. For example, one can mark an area of the level as region which will trigger a cutscene when the player character enters this area.
A region layer would act very similar to an Entity layer, yet without set size of the regions and tile support.  A future improvement to this system would be to supplement rectangle regions with any n-polygonal regions.

As far as I know, the use of these (or something similar) is widespread among games. One particularly strong visual example would be from the RTS game Warcraft 3 (google image result): https://media.moddb.com/images/mods/1/22/21742/Advance_Wars_Steampunk_Rising_Regions.jpg

A visual example from within LDTK (here simulated with an entity):
![image](https://user-images.githubusercontent.com/6222286/99180797-b80e0100-2729-11eb-92ae-f1dd984cc3c7.png)

**Comment by deepnight** [comment]
That's a great idea :) 
I think the resizable entities (#106 ) will fit that need perfectly, especially with the ability to define custom typed properties per region 🤔

**Comment by Sipondo** [comment]
Adding this functionality to entities would certainly work! (as they act mostly the same in LDTK).
One concern I would have is that adding this and (possibly in the future) other functionality to the entity group is bloat, where there are so many entities in the entity list that the lovely UI is bloated with options. It might be a good idea (in the future) to be able to e.g. group entities for this purpose.

**Comment by deepnight** [comment]
Ogmo has a great (yet simple) tag system to categorize entities, and each entity-layer can limit its content to specific tags. That might be a good solution to achieve that 🤔 

My only issue with a pure area layer is that it might "collide" with the entity feature, but maybe that's not a big deal: I'll have to thing about it :)

**Comment by Sipondo** [comment]
Yeah I think your hunch on integrating it as entities makes more sense as it would be a more generic approach and thus more flexible.
The only issue that arises is that e.g. for my use case I wouldn't want entities in the layer I use for region entities.

**Comment by botolo78** [comment]
Great idea, I was just trying to understand how to use entities for a fall zone 😊

**Comment by deepnight** [comment]
It's done and working in 0.8 :) You can now:

1. create resizable entities, 
2. make them "hollow" by checking the new option (this will allow editor clicks to pass through, except on edges)
3. tag them (eg. "*area*"), 
4. create an Entity layer that only contains specifically tagged entities.

**Comment by deepnight** [comment]
![image](https://user-images.githubusercontent.com/1671695/108381786-71d4ac00-7208-11eb-9229-691090abc636.png)
