### ISSUE TITLE
Adding __autoTilesetDefUid in layer instances

### ISSUE THREAD

**Issue by BurgerBob** [deepnight/ldtk#222]
It is useful when you draw a layer to know which tileSet it s linked to.
To get that, you have to use layerDefUid to get to the layer def, then use autoTilesetDefUid to get to the tileSet def, then you can access the texture and identifier of the tileset.

I think an __autoTilesetDefUid on the layerInstances would be useful.
A __tileSetRelPath may also be useful, from a rendering perspective...

**Comment by deepnight** [comment]
Good idea, it will be added in 0.6 :)
