### ISSUE TITLE
Unable to add custom fields to Entity when having too many entities

### ISSUE THREAD

**Issue by LeHaine** [deepnight/ldtk#240]
Once you have about 12 entities created, `Field` and `Array` buttons are pushed down where we can't view them any more unable to create any new fields. On version `0.5.2-beta`.

![image](https://user-images.githubusercontent.com/4951150/99799680-0db72480-2b01-11eb-987f-41929615e0e7.png)

**Comment by deepnight** [comment]
Thanks for reporting, I'll fix that for 0.6 🤔
