### ISSUE TITLE
Add previous/next levels as neighbours in linear world layouts

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#243]

**Comment by BoldBigflank** [comment]
Is this really added in? In 1.5.3-64bits when I create a new .ldtk world, add a layer, set World layout to horizontal and add two more levels, each level data has an empty array for neighbours

**Comment by BoldBigflank** [comment]
I see in the release notes this feature was scrapped in 1.0.0. I'm still trying to figure out how to get a list of level names in order from the ldtk object.
