### ISSUE TITLE
Tileset metadata

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#253]
Customizable meta-data for tiles in tilesets (eg. collisions, properties etc.)

- [x] tag-based approach: custom tags to categorize quickly tiles (eg. "slope", "left", "right", "one-way-platform" etc.)
- [x] custom JSON editor per-tiles
- [x] move specific picker stuff to a dedicated picker class
- [x] remap tile ids when image size changes 
- [x] ~collision shapes?~

**Comment by deepnight** [comment]
Related:
 - #172 (collision geometry)

**Comment by dtori** [comment]
It would be a great addition, I am currently adding collision information for each tile in the tileset by hand in the json.
Thanks for this wonderful app!

**Comment by nyalloc** [comment]
Likewise, very much looking forward to this. It's possible to abuse IntGrid for collision data but more fine-grained control over per-tile collider shapes would be great in the future.

**Comment by deepnight** [comment]
As discussed on Discord, I'll use a mixed approach here:
 - allow the user to paint Enum values over a tileset (eg. Spike, Water, SlopeLeft, SlopeRight etc.), to quickly tag any tile 
 - allow the creation of a fully custom JSON object associated to a tile in the tileset to enter super-custom properties
