### ISSUE TITLE
Read Image Data Error

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#258]
I noticed an issue where tileset images are unable to be loaded, even if I try re-referencing them. My suspicion is from the tilde key in the path text between LDtk and windows explorer:
![image](https://user-images.githubusercontent.com/55564581/100429633-71ce7100-304a-11eb-89ed-a7cde3a69dd4.png)
![image](https://user-images.githubusercontent.com/55564581/100429408-1e5c2300-304a-11eb-8d7d-ecff39bc3d92.png)
Is the path having its tilde key changed to an underscore?
One more thing to note is that my Samples~ folder is referenced by a symbolic link higher up in the folder tree if that helps out.

**Comment by Cammin** [comment]
After some more testing, I have been able to fix it by moving the project file back to a former path that it was in, where it attempts to go through the symbolic link's path instead of the referenced path that includes a tilde. I'm thinking the tilde key is the main reason to be causing it.

**Comment by deepnight** [comment]
Hmmmm... That's definitely a very plausible problem. I don't think the `dn.FilePath` doesn't support `~`. Could you please provide me the faulty URL so I can add support for that before 0.6 release? 🤔

**Comment by Cammin** [comment]
My symbolic link is named `Samples` which points to the folder of `Samples~`, which is likely why it was able to work previously for me because I went down the symbolic link path instead of the real path which contains the tilde. So, I can fix it if I pick the symbolic link's path. 👍 

Here's the path value; When the file search goes up one level, it runs into the `Samples~` folder:
```"relPath": "../Sprites/SunnyLand_by_Ansimuz.png"```

![image](https://user-images.githubusercontent.com/55564581/100433104-6df11d80-304f-11eb-8778-588c7c546104.png)
![image](https://user-images.githubusercontent.com/55564581/100434136-e7d5d680-3050-11eb-8b6f-8dcf250126e1.png)

**Comment by deepnight** [comment]
I'm not sure to fully understand your file hierarchy here 🤔  Couldn't screen me the tree where the LDtk files & images are stored?

**Comment by Cammin** [comment]
Here's the folder tree; the LDtk project is stored in the `Data` folder, and the images are stored in the `Sprites` folder.
![image](https://user-images.githubusercontent.com/55564581/100436373-24570180-3054-11eb-8b59-0996ef50e1b3.png)
I've to go to bed now, but I hope I could help out 🙂

**Comment by deepnight** [comment]
Thanks I'll check that today :) Have a good night

**Comment by deepnight** [comment]
This should be fixed by latest git version of my deepnightLibs (if you build LDtk yourself), or will be in 0.6 update today.
