### ISSUE TITLE
Entities: changing grid size doesn't reposition points associated ?

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [deepnight/ldtk#262]
I have several entities linked to individual points and an array of points in some cases in the entity layer.
I changed the grid size to test something out, and the core entities are positioned correctly but the points aren't.

**Comment by JettMonstersGoBoom** [comment]
actually it looks like points and paths are in the same grid as the layer , not the entities ?

**Comment by deepnight** [comment]
Yes, Points are using grid coords while Entities are on pixel coords. So when changing the grid size, weird things might occur 🤔

**Comment by deepnight** [comment]
See #88
