### ISSUE TITLE
Levels enum

### ISSUE THREAD

**Issue by botolo78** [deepnight/ldtk#268]
I was playing around with a non linear gridvania map. Something like

[ Level1 ] --> [ Level2 ] --> [ Level2 ]
               --->[ Level2B ]

I'm not sure if it's clear by the example, but usually we (I do, at least) generate the level list parsing the json and creating an array to follow in a linear fashion.

Level1 -> idx0
Level2 -> idx1
Level3 -> idx2

Going to the next level is just a matter of incrementing the index and reloading the level.
That of course cannot be done with this non linear map, because LEVEL2B could be at the end of the JSON and may have idx15 for example.

I think (but feel free to correct me) the right way in this case would be to load the level using the **identifier** or **uid** , but to do it the level should include an entity (I'm using an hidden trigger) with the destination level.

I guess I can create an haxe file with a dynamic enum to attach to the entity in LDTK, but if my logic is sound it may be better to have an enum object inside the LDTK object/map. 

I hope this wasn't too confusing :D

**Comment by deepnight** [comment]
Hi,

You lay also use the __neighbours value in each level to detect nearby levels, with their direction 🤔

I plan to add some new value types in 0.7 to allow referencing and stuff like that 😊

**Comment by botolo78** [comment]
I did a quick check with
`trace(world.levels[curLevelIdx].neighbours);`

it's so neat :D 
I guess it's just a matter to check the hero direction/position when the trigger is hit.
