### ISSUE TITLE
Crash when Exporting Tiled TMX

### ISSUE THREAD

**Issue by dataEcto** [deepnight/ldtk#270]
Steps on what happened
- Created a project with an entities layer and an integer layer
- Clicked on Export Tiled TMX so that I can export the TMX onto Unity using SuperTiled2Unity (Will develop a parser for json later)
-saving work creates the TMX file
-added a layer for tiles. Created a tileset and then placed a tile
-attempting to save gives me this error

```
Cannot read property 'indexOf' of null (TypeError)
```

getting rid of the tile layer doesn't revert this issue-it is only by disabling Export Tiled TMX does it save. Still, would like to have the TMX file.

(this is the first time I sent a bug report, please let me know if I'm missing anything)

**Comment by deepnight** [comment]
Hi, thanks for reporting, I'll fix that in 0.6.1 :)

**Comment by dataEcto** [comment]
> Hi, thanks for reporting, I'll fix that in 0.6.1 :)

thank you so much!

Upon further inspection, it seems to be a bug that happened on my specific project. If I make a new one quickly and then save it and the tmx, the error doesn't appear.

**Comment by deepnight** [comment]
Hmm 🤔  Could you please mail me the faulty project so I can check this out? (ldtk@deepnight.net)

**Comment by deepnight** [comment]
Fixed in 0.6.1
