### ISSUE TITLE
Entity with bottom pivot deletes self when moved to bottom of level

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#271]
I had discovered an issue centring around the idea that if an entity is re-positioned to the bottom of the map, and the entity's pivot point is at the bottom of the entity's shape, then the entity despawns (deletes).

An entity sits correctly as expected if it's spawned at a bottom tile (left object in image), however deletes itself if moved to the bottom of a level. (right object in image)
I remember this bug was also around when the project was named LEd as well; just didn't know how to post issues at the time :)

It may be treating the entity as if it was placed outside the level.

![image](https://user-images.githubusercontent.com/55564581/100964462-8cd33200-34dd-11eb-8a2f-e614d7ab3aef.png)

Repro steps:
- Define an entity where it's pivot point is any of the three bottom options.
- Place the Entity anywhere but a bottom tile.
- Move the entity to a bottom tile of a level.

Wish the best for the bug to get fixed :)

**Comment by deepnight** [comment]
Thanks a lot for the very detailed report, it will be fixed in 0.6.1 :)
