### ISSUE TITLE
Aseprite format?

### ISSUE THREAD

**Issue by gusg21** [deepnight/ldtk#279]
Hi, I just thought I'd ask if anybody else thinks it would be a potentially useful feature to have aseprite .ase format support for tilesets. There's a haxelib for it which I've used in my game projects, and having a direct import from aseprite would help my workflow. If there's interest I could try to take a stab at it myself, too.

**Comment by botolo78** [comment]
I guess depends on how spread is the use of Aseprite.
I have it and I like the idea to use the default format instead of exporting, but other than that convenience what advantages do you see?

**Comment by gusg21** [comment]
Aseprite files are a pretty powerful format, but I don't know if we want to offer those features (layers etc) to only people with aseprite so it might not make sense to use them. Mostly I just want them to be handled as pngs or bmps or whatever.

**Comment by deepnight** [comment]
Aseprite is very commonly used in the indie scene, for sure :)

You can easily export a PNG in Aseprite from a single keypress, so I'm not 100% sure it would be super useful to support direct Aseprite file format. Also, it'll probably require some work to "flatten" the Aseprite layers to have 100% fidelity with what's on the app screen. LDtk would also become dependent on possible future Aseprite format changes (new blendmodes, future tile editor etc.). 

I think that, as long the app provides a very easy (and quick) way to get a PNG output, implementing a direct Aseprite wouldn't be super relevant, imho.

**Comment by gusg21** [comment]
That's a good enough reason for me, thanks for your response!
