### ISSUE TITLE
Allow IntGrid values sorting

### ISSUE THREAD

**Issue by di-effe** [deepnight/ldtk#284]
I did a quick search and I did not find this request.
Would be possible to add the possibility to rearrange the GRID VALUES in the IntGrid.
It's not a big issue, but it happens to start with something like

#0 Terrain1
#1 Terrain 2
#3 Platforms
#4 Something

and then add a new terrain type that will end up separate from the others.

**Comment by deepnight** [comment]
You're right, that should definitely be done at some point 🤔
That was not done before mostly because I was lazy implementing remapping of int grid values in existing layers 😅

**Comment by IrishBruse** [comment]
Omg yes this would be great but I can see how it would be trouble some to do the remapping guess just having messy ints will be fine for now :)

**Comment by deepnight** [comment]
It will be available in 0.10
