### ISSUE TITLE
Backgrounds?

### ISSUE THREAD

**Issue by SolarLune** [deepnight/ldtk#287]
Yo, 'sup! 

Have you given thought to implementing backgrounds within LDtk? It seems like it might be a good option to add.

Currently, you can already do backgrounds with the Tile layer, but you have to specify the tile size when defining the tileset, and the tile size is limited to the smallest image dimension (i.e. an image that is 512x256 can only have a tile size of 256). In addition, tiles can draw outside of the level, which isn't ideal for large "tiles", like for backgrounds. One could also do backgrounds with just an Entity, though visualizing them requires defining a Tileset anyway, so either way it's not quite perfect. 

Backgrounds being definable in some way seem like they could mix quite well with the planned parallax feature in #28.

However, I don't think this is enough of a sticking point to make them necessary, as it's possible to do currently, just not quite seamlessly. I am a fan of keeping LDtk as light and simple as possible as well, so either implementing backgrounds or leaving them out would be fine.

(P.S. Paid for LDtk; thanks a lot for the cool tool! Runs perfectly fine on Linux. Thanks for that, too, @VCSocial)

**Comment by deepnight** [comment]
Hi! I'm trying that for 0.6.3 :)

**Comment by deepnight** [comment]
![image](https://user-images.githubusercontent.com/1671695/105014750-1664a200-5a41-11eb-9c7f-a1377ee683b4.png)

**Comment by SolarLune** [comment]
Yoooo, let's go! Very nice; thanks for implementing.

**Comment by MoroXDev** [comment]
how to add multiple backgrounds like layers?
