### ISSUE TITLE
Add missing vars to Json doc

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#289]

**Comment by BanchouBoo** [comment]
### Things I've noticed so far

In entity definitions:
- missing `showName`

In field definitions:
- missing `editorDisplayMode`
- missing `editorDisplayPos`
- missing `editorAlwaysShow`
- `arrayMinLength` and `arrayMaxLength` don't mention that they're nullable

In tileset definition:
- missing `savedSelections`
- missing `cachedPixelData`

In enum definition:
- missing `externalFileChecksum`

In field instance:
- missing `realEditorValues`

I also remember noticing various other things that were nullable but not listed in the json reference as nullable that I don't remember.

**Comment by deepnight** [comment]
I updated the doc for 0.6.2 :)
If you remember/find nullable fields not marked as such, please feel free to open a new issue, or reopen this one.

**Comment by deepnight** [comment]
I also fixed all the nullable values that were not marked as such. The new Json schema is available here: https://ldtk.io/json/
