### ISSUE TITLE
Couldn't read project file: Cannot read property '_hx_index' of undefined

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#290]
I tried loading a simple project I had made and saved previously. However, I noticed I cannot open it, and it throws this error:    
![image](https://user-images.githubusercontent.com/55564581/102193938-8a73bf00-3e71-11eb-8969-e4f0d75c96d2.png)
It's a simple project with a single 3x3 size level containing an entity with all possible field types defined in it. 
Attached is the problematic JSON file.

[TestAllFields.txt](https://github.com/deepnight/ldtk/files/5694603/TestAllFields.txt)
(file is `.txt` to become sharable, change to `.ldtk`)

Unsure what may be causing the problem loading the project, but I wish the best 👍

**Comment by deepnight** [comment]
Thanks, I'll check this asap :)

**Comment by deepnight** [comment]
Sorry it took more time as expected with the holidays, it'll be fixed in 0.6.2 :)
