### ISSUE TITLE
FR: Non-square grid size

### ISSUE THREAD

**Issue by SecretPocketCat** [deepnight/ldtk#291]
Will it ever be possilbe to set a non-square the grid size?  

With my current project I kinda need that as well as resizable entities #252 , so I'm looking at the OgmoEditor to start off (since it has both of those) and once that's ready possibly switch back for the autolayers, the world-editor and whatever feature you put in I didn't realise I wanted 😄

**Comment by deepnight** [comment]
Duplicate #18

**Comment by deepnight** [comment]
Issue for resizable entities #252
