### ISSUE TITLE
Replacing a tileset image with a compatible but larger one breaks the tiles

### ISSUE THREAD

**Issue by keir** [deepnight/ldtk#300]
This happened to me when I extended my tileset image to make room for more tiles.

**Steps to reproduce:**
1. Create a tileset using an image NxM pixels (e.g. 160x160); file: tileset_small.png
2. Create rules to autotile based on the tileset
3. Create a level using those autotile rules.
4. Outside of LDtk, expand the canvas size of the tileset image from 160x160 to e.g. 160x320; file: tileset_big.png
5. In LDtk, open tileset dialog, click "Replace image", select tileset_big.png

**Expected behaviour**
Existing level remains exactly as before. Additional tiles are free for use in rules.

**Actual behaviour**
Tiles are scrambled. Appears to be because the tiles are not remapped preserving the location, and are instead mapped by a linear ID that assumes the image does not change dimensions.

**Comment by deepnight** [comment]
That's totally a bug, sorry about that!
I actually update tile IDs when the image changes, but it doesn't seem to work for AutoLayer rules 🤔  I'll patch that asap.

**Comment by deepnight** [comment]
Will be fixed with 0.6.3
