### ISSUE TITLE
File Path entity field doesn't work with Haxe API

### ISSUE THREAD

**Issue by jefvel** [deepnight/ldtk#301]
To reproduce:

* Create an entity with a File Path field
* Create an instance of that entity in a level
* Set the file path field of that entity
* Compile your Haxe project that uses the LDTK Haxe API
* Error:

![image](https://user-images.githubusercontent.com/494817/103813104-d6c0b200-505f-11eb-8445-c06e7b92077a.png)

**Comment by deepnight** [comment]
It will be fixed in 0.6.3. 
Extra bonus: you'll be able to access the actual file content (as `haxe.io.Bytes`) using `f_myFieldName_bytes`. The referenced file should be part of the app assets to work (in Heaps, it's inside the `res` folder)
