### ISSUE TITLE
Entity Field as entity list identifier

### ISSUE THREAD

**Issue by jefvel** [deepnight/ldtk#302]
It would be nice if it was possible to select one field in entities to be the identifier field. 
The selected field would be shown in the entity list, either instead of the Entity Identifier, or below it

![image](https://user-images.githubusercontent.com/494817/103815675-01ad0500-5064-11eb-938d-b35ba38cb067.png)

**Comment by deepnight** [comment]
I'm not sure to understand 🤔  
Should the list on the left show multiple "characters" (one per enum value)?

**Comment by jefvel** [comment]
Oh my bad, never mind this. I realized It was my misunderstanding of the UI
