### ISSUE TITLE
Long file path results in unreadable file name

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#303]
Visual bug, but if a `.ldtk` file is located in a deep folder hierarchy, then it becomes obscured in the recent projects menu.  
![image](https://user-images.githubusercontent.com/55564581/103825640-0fde2f80-502a-11eb-8ee6-abae8649512f.png)  
Could consider having a horizontal scroll bar?

**Comment by deepnight** [comment]
Fixed in 0.6.3
