### ISSUE TITLE
Unable to edit level size in World view

### ISSUE THREAD

**Issue by notbored** [deepnight/ldtk#309]
On the macOS distribution there is no transform knobs/area to change the size from the default 256x256. This is only the case when creating new projects but the works on the existing samples.

![Screenshot 2021-01-09 at 21 56 07](https://user-images.githubusercontent.com/42345404/104109453-03760300-52c6-11eb-940d-7733d0552711.png)

**Comment by notbored** [comment]
Apologies I was playing around with the editor before actually creating anything. 

Everything works once you have an initial layer defined. If you try to create new levels in the world before doing that you can't resize things.

**Comment by deepnight** [comment]
That's still a bug, I'll fix that in next update :)
