### ISSUE TITLE
Request: Backup Files

### ISSUE THREAD

**Issue by IrishBruse** [deepnight/ldtk#315]
On Save should create a backup of the .ldtk file and then save the new one similar how blender does it
![image](https://user-images.githubusercontent.com/14964651/104671895-9a7ff800-56d6-11eb-8977-ded3a4d5ea1d.png)
This would help with stability as currently I duplicate the file and then save the file would be a nice option to have.

**Comment by deepnight** [comment]
That's an interesting idea, I will see what can be done :)

**Comment by IrishBruse** [comment]
it will hopefully mitigate any corruptions that could happen early on :)

**Comment by zshoals** [comment]
Backing this one. Inevitably, someone's going to get screwed by file corruption. I have some bad memories of it myself with Hammer :/

**Comment by deepnight** [comment]
Actually, I move that to 0.7 release, as it sounds like a quite important feature 🤔

**Comment by deepnight** [comment]
Done for 0.7 :)
