### ISSUE TITLE
Name anonymous objects in JSON doc

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#319]

**Comment by Cammin** [comment]
I've also tested the commit's schema in Quicktype, but it does not work. The schema's commit before that one does work correctly so a change in that commit specifically is impacting its success. 
Excited to use this when it's ready to use fully :)

![image](https://user-images.githubusercontent.com/55564581/105100461-2771db00-5a62-11eb-9976-92dfe27926a0.png)

**Comment by deepnight** [comment]
Using the latest JSON schema, I seem to be able to generate the C# output on my side 🤔

**Comment by Cammin** [comment]
Ah, my mistake; I had tested only up to the commits through [this link](https://github.com/deepnight/ldtk/commits/b351290fa9ef16b1235e58b17e7db8096cc44360/docs/JSON_SCHEMA.json), so I had assumed that was the most recent one, where it did not generate specifically for that single commit 😅 

After checking the file's history through [this](https://github.com/deepnight/ldtk/commits/3510ef7b3ec1c660972b858a4ba9196880431ab8/docs/JSON_SCHEMA.json), I tested the schemas in those commits and they were working :)

**Comment by deepnight** [comment]
I updated the schema generation and added a "@inline" custom flag in my JSON haxe source. This flag will make the corresponding type fields "inlined" in the Markdown/HTML documentation (to avoid too many meaningless types), while keeping separation in the JSON schema.

**Comment by deepnight** [comment]
Updated schema:

[JSON_SCHEMA.zip](https://github.com/deepnight/ldtk/files/5841086/JSON_SCHEMA.zip)

**Comment by deepnight** [comment]
- [ ] Fix inlined fields naming
