### ISSUE TITLE
GPU / CPU optimizations

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#331]
- [ ] Adjust canvas FPS when app is inactive or nothing moves
- [ ] Check usage of dedicated GPU

Related #8

**Comment by jeremyfa** [comment]
Following the discussion here,

I noticed the app is not using dedicated GPU, but maybe that's not a problem in itself.
The use of discrete graphics could create more issues as well like consuming more battery etc...

My guess is that its probably a good idea to try first, before choosing an option (if there is actually a way to configure that) and see what works best (I can help with testing that, if needed!)

Refresh rate is probably the main reason why my laptop's fan is going crazy.

**Comment by jeremyfa** [comment]
It seems that's the answer on electron side: https://github.com/electron/electron/blob/master/docs/api/command-line-switches.md#--force_high_performance_gpu

**Comment by jeremyfa** [comment]
I can confirm adding ```app.commandLine.appendSwitch('force_high_performance_gpu');``` to electron app is working on my side with another electron app I have.

**Comment by deepnight** [comment]
Great! I'll update that in a hot-fix next week :)
