### ISSUE TITLE
Can not properly launch LDtk 0.7.1

### ISSUE THREAD

**Issue by dataEcto** [deepnight/ldtk#346]
Hello

i updated to 0.7.1 but found I can't open LDtk anymore. I managed to semi-work around this by opening a .ldtk file.

The file would open as expected, and I was able to make changes to it. However, open saving and closing the project, I was presented with 

"Cannot read property 'length' of undefined (TypeError)"

Selecting restart leads back to the file, and I can close it again, but it leads to the same error screen.

side note: I reported a bug that happened on a specific file of mine (Crash when Exporting Tiled TMX #270). i used this same file for this bug. Upon using another file though, the same error also appears.

**Comment by deepnight** [comment]
This should be fixed in 0.7.2, could you please confirm? 🤔

**Comment by dataEcto** [comment]
Thank for the wait! Downloaded 0.7.2 and it worked out just fine, although I only added a few blocks before saving and quiting. Thanks!
