### ISSUE TITLE
Add a few more default Entity visualizations

### ISSUE THREAD

**Issue by zshoals** [deepnight/ldtk#356]
I've been working with some trigger volumes, using entities as their representation, and in some cases have found myself wanting two more visualizations provided by default that I think would represent these regions a bit better:

Rectangular Outlines
Elliptical Rings

Hopefully, this isn't one of those things that is "my use case only" and has some generic application. Either way, thanks for looking the request over.

**Comment by deepnight** [comment]
Related to #252

**Comment by deepnight** [comment]
More is needed here, I agree :)

**Comment by deepnight** [comment]
I added customizable line and fill opacities in 0.8, which allows "hollow" or semi-transparent rects and ellipses.

**Comment by deepnight** [comment]
Also, entities will be resizable in 0.8, and can be assigned tags (to filter them per-layer) making Region layers possible 👍

**Comment by zshoals** [comment]
Even better than what I was hoping for, thanks! Looking forward to it.
