### ISSUE TITLE
Whats the difference between Int grid and auto-layer?

### ISSUE THREAD

**Issue by IrishBruse** [deepnight/ldtk#359]

**Comment by deepnight** [comment]
You have 2 kind of auto-layers:

- IntGrid layer with an attached tileset. 
- a "pure" auto-layer which uses data provided from another IntGrid layer.

Example: you may have an IntGrid to place wall collisions, with some rules to paint the wall textures, and have a second "pure" auto-layer using the same wall collisions, but this time to paint background textures

**Comment by IrishBruse** [comment]
I just havent found anything the autolayer can do that the int grid cant.
like if i want collision data i can just use the int grids data and if i want auto tile i can still use the int grid and set up rules
also for my renderer i made i render both the same 
![image](https://user-images.githubusercontent.com/14964651/106208171-df1d9000-61ba-11eb-8495-f7e7b0d50fb2.png)

**Comment by deepnight** [comment]
They are identical, except:

 - one is "source + rendering" (IntGrid)
 - the other is "rendering" only (pure auto-layer)

This allows to have a single data source, and multiple different layers of rendering. For example: one pure auto-layer for the walls, another in front of that for various vegetation props, and on in the background for props in the background.

There are examples of that in samples:

 - `Typical_2D_platformer_example`: walls can be in *front* of the player character, while bg walls are behind. Both use a single collision data in the intGrid layer.
 - `WorldMap_GridVania_layout`: shadows are rendered in a separate layer, on top of everything, so player will go behind in game for example.

**Comment by IrishBruse** [comment]
Oh that makes sense you can change the rendering order of tiles even tho you use 1 int grid thats really handy thanks for clarifying :)

**Comment by deepnight** [comment]
👍 Feel free to come by on the discord if you have any other question :)
