### ISSUE TITLE
Possible Memory Leak in Rules Editor Screen

### ISSUE THREAD

**Issue by SeiferTim** [deepnight/ldtk#362]
While working on setting up the rules for my map, I found that, over time, the program became less and less responsive, and would not respond to inputs for long periods of time - getting to the point where it locked up completely and I had to terminate it.
I assumed I had added too many rules, but after reloading the project, even with 30+ rules, it was back to being super fast and responsive.
Over time, again, it would slow down the more rules I added, but relaunching would fix it immediately.
I was ONLY working on the rules for a single tilesheet at the time, and it happened every time I worked in the project long enough.. about 30-45 minutes I would need to quit and re-launch.
[maps.zip](https://github.com/deepnight/ldtk/files/5897613/maps.zip)
I have attached the project I was working in.

**Comment by RPGillespie6** [comment]
I noticed this today as well. I left rules open and forgot about it, and when I came back to the window later it was completely frozen

**Comment by deepnight** [comment]
I tried to optimized things in 0.9.0 update. Please feel free to re-open this issue if the problem still occurs 🙂
