### ISSUE TITLE
Won't let me create a new room in an exactly-sized opening

### ISSUE THREAD

**Issue by gusg21** [deepnight/ldtk#366]
![Issue](https://user-images.githubusercontent.com/14032977/106368426-5a945400-6317-11eb-9dd3-87a715d0fdd1.gif)

When I use the right-click method (on the level editor view, not the world view) to add a new room in a metroid-vania style world, it won't let me create one if the opening is exactly one room. Am I missing something? This seems like a bug.

Running 0.7.2 on latest Windows 10

**Comment by deepnight** [comment]
This issue should be fixed in 0.8.1 :)
