### ISSUE TITLE
(Suggestion) Rules per room?

### ISSUE THREAD

**Issue by gusg21** [deepnight/ldtk#368]
Same issue as before - as my world grows, it's getting harder to manage. I wish I could have certain autotiling rules only apply to certain rooms (think biomes). I'm not sure what the best way to implement that would be, maybe tagging rooms and having groups of rules have a matching tag? That might be too complicated, but a feature like this would be greatly appreciated.

**Comment by deepnight** [comment]
Hi! It's available in 0.9.0, in the form of "Optional rule groups" :) Feedback are welcome.
