### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by dtori** [deepnight/ldtk#369]
Hi,

Ldtk It is constantly using a lot of CPU even when nothing is done, just by having the app open. I realize when I use the computer without being connected to the electrical network, the battery drains right away. 

OSX 10.15 MacBook Pro (Retina, 13-inch, Mid 2014)
Ldtk 0.7.2

![Screen Shot 2021-01-31 at 21 52 06](https://user-images.githubusercontent.com/19737932/106403812-213f0f80-640f-11eb-9735-b45ede0c9c4b.png)

Cheers :)
Diego.

**Comment by deepnight** [comment]
- [ ] Optimize Cursor postUpdate()

**Comment by deepnight** [comment]
This last commit should fix most of this issue: the CPU usage is still around 25% when the app is open **and** focused (related to how the canvas rendering happens), but will drop to ~3% when the app isn't focused anymore (but still open).

**Comment by deepnight** [comment]
I also added a "smart CPU throttling" setting (**enabled** by default) which will reduce CPU usage when doing some "not too demanding" actions.
