### ISSUE TITLE
Feature Request: Store layer visibility property

### ISSUE THREAD

**Issue by SamHellawell** [deepnight/ldtk#377]
This issue is quite simple, in LDTK we can turn layers off in the editor, but that value is never stored in the JSON. It would be ideal, for sake of not having to re-toggle the layer when I load ldtk and for in-engine purposes to be able to mark that layer as visible or not in its instance definition.

One example use case is collision tile painting, which for some is preferred. I think that this should be considered basic functionality of a 2D level editor (you can see it in Tiled and such). Happy to address this myself and submit a PR if its just been overlooked, or do you have any reasoning for not including it?

**Comment by deepnight** [comment]
That's an old design decision, but there's no reason to keep it as it is today 🤔 
I'll change that in 0.8: you'll have a `visible` boolean in LayerInstance JSON.

**Comment by deepnight** [comment]
And... done.

**Comment by SamHellawell** [comment]
Awesome, thanks for the quick turnaround! Will check it out when 0.8.0 is released
