### ISSUE TITLE
(Suggestion) Option to display Array<Point> as a looping path

### ISSUE THREAD

**Issue by nyalloc** [deepnight/ldtk#402]
Hello! I was delighted to see LDtk can display arrays of points on an entity in the editor. It would be great if there was an option to display these points as a loop, adding a new line from the final point back to the first point.

![image](https://user-images.githubusercontent.com/7504843/109578858-dbe62e80-7aef-11eb-8772-b68d7100b5df.png)

This path is intented to loop back onto itself, forming a rectangle that the Guard entity will patrol. That isn't very readable at the moment - you need to add an extra point at the end that exists on the same grid as the first element, which is a bit fiddly in-editor. In cases like this, it would be great if there was a checkbox that enables displaying the path as a loop in-editor.

Cheers again, this is a wonderful tool.

**Comment by deepnight** [comment]
Good idea, I'll add that 👍

**Comment by deepnight** [comment]
Done in 0.8.2

**Comment by nyalloc** [comment]
Awesome! Thanks for your hard work.
