### ISSUE TITLE
__tileSrcRect is null in Entities.ldtk Sample But Not Nullable According to JSON Schema

### ISSUE THREAD

**Issue by zicklag** [deepnight/ldtk#415]
In the Entities example, we there are some `__tileSrcRect` fields that are null:

https://github.com/deepnight/ldtk/blob/03d51ec1b19275554f0b67b8e56370baca230a44/app/samples/Entities.ldtk#L993-L995

But according to the schema that field is required:

https://github.com/deepnight/ldtk/blob/03d51ec1b19275554f0b67b8e56370baca230a44/docs/JSON_SCHEMA.json#L1251-L1254

My Rust crate failed to validate the Entities sample because of the difference. It turns out the Rust crate makes a good test-case for the schema. :smile:

**Comment by deepnight** [comment]
Thank you, I'll check that :)
