### ISSUE TITLE
Microsoft Defender SmartScreen prevents LDtk Setup from opening

### ISSUE THREAD

**Issue by photonstorm** [deepnight/ldtk#416]
This isn't an issue, as such, because it's easy to bypass (depending on how your PC is configured), but it may be alarming to newcomers?

![image](https://user-images.githubusercontent.com/164476/110670551-6c460280-81c5-11eb-9f33-1f7aead12b88.png)

**Comment by deepnight** [comment]
Yes this should be fixed with #52 👍
