### ISSUE TITLE
Suggestion: Update existing level names based on position if using numbering system

### ISSUE THREAD

**Issue by LeHaine** [deepnight/ldtk#426]
## Context

Currently when you have a level that ends in a number, the next level that is created, that number gets incremented automatically.

![image](https://user-images.githubusercontent.com/4951150/111661810-bd697e00-87e5-11eb-82d8-5b5356584fd1.png)

Now lets say you want to add a new level between two existing ones (using horizontal or vertical world layout) that number still gets incremented.

![image](https://user-images.githubusercontent.com/4951150/111662000-e984ff00-87e5-11eb-9ce4-ad9512926285.png)

## Suggestion
Have an option (can be off by default) that allows new level names to be updated to their current list index and to update any levels that follow the new level to their new index.

As an example with the two images above, I inserted a new level, "Level 10" in between "Level 4" and "Level 5". It would be nice if that "Level 10" would instead be named to "Level 5" and the old "Level 5" and the levels that follow it would be updated to "Level 6" and so on.

No real functional reason why to do this but it just bothers me when it is out of order :)

**Comment by deepnight** [comment]
Hi, I'll see what can be done here :)

**Comment by deepnight** [comment]
Done in 0.8.2 :) Changelog: 

> **Auto level naming**: you can let LDtk name your level identifiers automatically using a **custom pattern**, as defined from the Project settings panel. For example, with the pattern `MyLevel_%gx_%gy`, each level will be named using the world grid X/Y coordinates (only applies to GridVania world layouts).
