### ISSUE TITLE
Question of the editor color of an entity

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#430]
On the subject of what the colour of an entity's editor visual is determined by. 
There is a default colour which is the first determinant. 
And I noticed (in the Entities example) that if an entity defines a field for a colour or colour array, that field's colour is used (or the first element in the array if it's a colour array).

But I was wondering; what determines the colour of an entity's editor visual when an entity defines multiple colour fields?

While experimenting with this, I created+changed the ordering of my colour fields hoping that the first-ordered colour field would be used for its editor visual. But it seems to continue using the original field's colour. (I expected green to be the new colour for the light's editor visual)

![image](https://user-images.githubusercontent.com/55564581/112776163-bf0c2080-8ff3-11eb-82c7-dd9f7572a0e8.png)

I looked into the JSON to see what could make that one colour field the exact one used, but my guess is the def UID ordering? (speculation, the highest UID determines which field's colour to use?)
![image](https://user-images.githubusercontent.com/55564581/112776438-815bc780-8ff4-11eb-9e59-8b9915f8030c.png)

**Comment by deepnight** [comment]
I will update that to make sure that the **first** color found is always used, following fields order (or defaults to entity definition).

**Comment by deepnight** [comment]
Fixed: it now properly uses the *first* color value found among fields, in order of appearance, otherwise it defaults to entity main color.
