### ISSUE TITLE
Bigger default entity size

### ISSUE THREAD

**Issue by Nichts-Games** [deepnight/ldtk#431]
When defining an entity, you can not enter a bigger default size than 256.

_I try to enter 300_
![before](https://user-images.githubusercontent.com/75997923/112895564-96605580-90dd-11eb-8b5f-d93cdfea8989.png)

_It automatically changes to 256_
![after](https://user-images.githubusercontent.com/75997923/112895571-98c2af80-90dd-11eb-9b0b-deb7be64b5ed.png)

**Comment by deepnight** [comment]
Done
