### ISSUE TITLE
[Suggestion] World Layers

### ISSUE THREAD

**Issue by FaultyFunctions** [deepnight/ldtk#435]
It would be nice if the world itself could have layers. That would make constructing vertical maps that are stacked on top of each other like the Tower of Hera from A Link to the Past easier, for example.

**Comment by deepnight** [comment]
I kind of struggled how to implement this properly, without breaking JSON too much, but this should finally happen soon :)

Hopefully in 0.10 or 0.11 update.

**Comment by FaultyFunctions** [comment]
Yesssss, can't wait!

**Comment by deepnight** [comment]
A new basic "world layer" system was added in 0.10, which should make management of "stacked" levels much easier.
![layers](https://user-images.githubusercontent.com/1671695/149810864-f7ace342-d2a1-4acd-b72a-f62efa832899.gif)
