### ISSUE TITLE
Baked result of auto-layer is different from the original auto-layer

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#438]
version
0.8.1

Description
I have to bake the auto layer "Ground" in the sample "Typical_TopDown_example",
But it get different result comparing to the original auto-layer.

original
![image](https://user-images.githubusercontent.com/10916383/113891341-935d1780-97f7-11eb-907b-3364d812b3e6.png)

baked
![image](https://user-images.githubusercontent.com/10916383/113891425-a53eba80-97f7-11eb-92e7-2913d1ff78d8.png)

**Comment by deepnight** [comment]
That's definitely a bug. I'll see what happens here & fix it.

**Comment by deepnight** [comment]
Fixed in 0.8.2
