### ISSUE TITLE
Bug Report: Rule Editor creates multiple groups while clicking button "+Group"

### ISSUE THREAD

**Issue by yuiwong** [deepnight/ldtk#440]
Version: 0.8.1

Reproduce Steps:
   1. Create an empty project. Create a intergrid layer, give it a random tileset.
   2. Open Rule Editor. 
   3. Click "+Group" once.
   4. Try to undo with "Ctrl+Z".(nothing happened)
   5. Click "+Group" again, there are two newly created groups while there should be only one.

In my machine, this can be reproduced constantly.
And I found that the additional groups added are related to how many times you press undo.

I'll provide gif or vid if necessary.

~~PS: I just notice that undo is not valid for editing levels. Perhaps this is a feature in future?~~
PS: undo does work when editing levels. Maybe give a tip when it doesn't?

**Comment by deepnight** [comment]
Sorry about that! **This bug will be fixed in next update 0.8.2** .
Right now, you can just close/reopen the Rules panel to avoid this bug.
