### ISSUE TITLE
Wacom stylus issues

### ISSUE THREAD

**Issue by stickynoteme** [deepnight/ldtk#451]
When trying to draw out maps with a wacom stylus LDtk doesn't recognize the input correctly and acts strange, eg: You can't draw straight lines, and the path of the line jumps around seemingly randomly. You can tap out one tile at a time, but you can't paint tiles like you can by using a mouse.

**Comment by stickynoteme** [comment]
Accidentally stumbled on the fact that disabling windows Ink in the Wacom tablet properties for the system fixes the issue. So this seems to be an issue with Windows ink.

**Comment by deepnight** [comment]
I'll check what happens here and see if I can fix it. Thanks for reporting :)
