### ISSUE TITLE
Keyboard Shortcuts (numbers) for Layers vs. IntGrid Values

### ISSUE THREAD

**Issue by kaiiboraka** [deepnight/ldtk#454]
(Issue from [this Discord question](https://discord.com/channels/761549092677353513/778168731036549130/832507904174063636)) 
There are keyboard shortcuts to switch between the active layers, numbers 1,2,3 etc. There should be a similar shortcut for cycling up and down through the list of tiles as well.

When I first saw these numbers, it looked like I'd be able to hit 1 2 3 to swap between the different tiles. I hadn't even seen the numbers on the layers yet, so that kind of caught me off guard.
![image](https://user-images.githubusercontent.com/7596816/114990949-465fed80-9e56-11eb-8c52-f43a3043ac4a.png)

I realize the alt-click dropper workflow is very common, and it's sometimes useful for me, but for tiles it'd be really nice if there could be a dedicated slew of hotkeys for, for instance, Tiles 1-10. I realize there's a problem with that as you can have (i'm pretty sure) countless tiles, so if not something like that, then alternatively it could be 2 hotkeys: one to cycle the selection up/previous, and another to cycle it down/next.

As per deepnight's explanation, there are two main approaches to consider:
* Keep 1-9 shortcuts for layers, use ARROWS for tool value selection
* Find another shortcut for layers, use 1-9 for first 9 values in current tool (won't work well with tilesets, but quite intuitive to use)
  * Possibly use a modifier (Shift/Control/Alt) for layers. This presents a UI challenge.
  * Possibly use Page Up/Page Down to go up and down Layers one at a time.

**Comment by deepnight** [comment]
> Keep 1-9 shortcuts for layers, use ARROWS for tool value selection

Arrows are currently reserved for future Selection movements (eg. move around a selection of tiles/entities)

> Find another shortcut for layers, use 1-9 for first 9 values in current tool (won't work well with tilesets, but quite intuitive to use) 

As you mentioned, 1-9 numbers are only relevant for IntGrids, but won't work for any other layer types, so it's not a consistent solution 🤔  

I was thinking about having a quick shortcut to pop up possible values of current tool near the mouse cursor (like a wheel or something). But this solution would still involve using either a mouse or multiple key strokes (ie. one to pop the wheel, followed by arrows/numbers to pick a value). 

What do you think?

**Comment by kaiiboraka** [comment]
Hm. That seems like a fair compromise, although it's not a totally elegant solution, as the added layer of input kind of retains some of the clunk keybinds are trying to avoid in the first place.

On some level it's not really much different than this idea from before. It's almost like combining them.

> Possibly use a modifier (Shift/Control/Alt) for layers. This presents a UI challenge.

> [...] a quick shortcut to pop up possible values of current tool near the mouse cursor (like a wheel or something). [...] one [key press] to pop the wheel, followed by arrows/numbers to pick a value).

So press or hold some modifier-key (or just... any key, I guess?) to open up a context menu near your cursor, and then numbers are mapped to all of the options of that menu, in some kind of order. Something like that? I don't know how feasible prototyping a solution like this is but it's definitely something I'd love to try and test out and see if it feels good enough.

**Comment by kaiiboraka** [comment]
Just had a new idea while I was using it today. What if you held shift and scrolled the mouse wheel to go up and down in the list? Probably would NOT loop back around to the other end if you scrolled up at the top or down at the bottom... What do you think?

**Comment by deepnight** [comment]
1.2.0 introduces WASD shortcut support which works very well for all layer types (IntGrid, Entities or Tiles). I'm closing this one as duplicate, but feel free to re-open if you feel there's still a need for it.
