### ISSUE TITLE
Bug 0.9.0 Tileset preview shrinks as you pan

### ISSUE THREAD

**Issue by IrishBruse** [deepnight/ldtk#459]
Panning downwards in the tile set shrink the preview to this 
![image](https://user-images.githubusercontent.com/14964651/115038400-6a0f4c00-9ec7-11eb-9192-d38e76f75039.png)
from this 
![image](https://user-images.githubusercontent.com/14964651/115038481-7c898580-9ec7-11eb-90c9-00d26942f319.png)

**Comment by deepnight** [comment]
Fixed in 0.9.2
