### ISSUE TITLE
Bug 0.9.0 Creating new file fails on windows 10

### ISSUE THREAD

**Issue by IrishBruse** [deepnight/ldtk#460]
![image](https://user-images.githubusercontent.com/14964651/115077266-a8bbfb00-9ef5-11eb-9db0-7eca8bb10414.png)
![image](https://user-images.githubusercontent.com/14964651/115077292-b2ddf980-9ef5-11eb-9c01-a5682306866b.png)

**Comment by deepnight** [comment]
Fixed in 0.9.1, sorry!
