### ISSUE TITLE
Blank screen in 0.9.1

### ISSUE THREAD

**Issue by fennicfox** [deepnight/ldtk#465]
I tried to open the latest version of ldtk 0.9.1 the menu won't show up. I hope it fixed the bug -Eyebrow

**Comment by deepnight** [comment]
I added extra logging information in 0.9.2, to help finding the exact problem 🤔 
Please update to 0.9.2 when it's available and tell me if you get something new :)

**Comment by fennicfox** [comment]
sorry for my bad english lol. 

> I added extra logging information in 0.9.2, to help finding the exact problem 
> Please update to 0.9.2 when it's available and tell me if you get something new :)

sorry for my bad English. thank you for correcting it

**Comment by fennicfox** [comment]
> > I added extra logging information in 0.9.2, to help finding the exact problem
> > Please update to 0.9.2 when it's available and tell me if you get something new :)
> 
> sorry for my bad English. thank you for correcting it

yeah I check it out. also love your work it's amazing.

**Comment by lublak** [comment]
I have the same issue. Where can I find the logs?

Loading:

![grafik](https://user-images.githubusercontent.com/44057030/128680891-24a83845-06bb-455a-bde9-ccf422e9548c.png)

After loading:

![grafik](https://user-images.githubusercontent.com/44057030/128681335-db94c375-391d-41db-aaca-f193df0c7ccb.png)

**Comment by deepnight** [comment]
Duplicate #498

**Comment by fennicfox** [comment]
Hey long time no see again I know is get embarrassing. I did change the
settings in properties In Windows 7 actually is not supported Service pack
3 of XP then I change Win Vista or 7 and it works I'm such big moron. Sorry
😔.
