### ISSUE TITLE
Error when deleting last world map

### ISSUE THREAD

**Issue by willianholtz** [deepnight/ldtk#483]
Application closes when deleting a map that is the last one in world mode. For example. If I have only a few instances of the map, and try to delete the error and close the program

![last](https://user-images.githubusercontent.com/23488207/115941936-00221400-a47e-11eb-98da-fa0dc4bb2c3c.png)
![delete](https://user-images.githubusercontent.com/23488207/115941934-ff897d80-a47d-11eb-9ac2-05361408ff15.png)

**Comment by joeld42** [comment]
Happened to me as well.

**Comment by deepnight** [comment]
You shouldn't be able to delete the last level in the first place 🤔 Looks like some code regression to me, I'll fix that next week :)

**Comment by deepnight** [comment]
Duplicate #501
