### ISSUE TITLE
Pressing Cmd-R on macOS restarts LDtk, losing unsaved changes

### ISSUE THREAD

**Issue by DagAgren** [deepnight/ldtk#486]
If you press Cmd-R, I guess the whole UI reloads, which causes any unsaved changes you have to be lost without warning. This is especially treacherous if you are developing with Xcode at the same time, where Cmd-R is the "Run" action.

**Comment by deepnight** [comment]
Hi! Sorry about that 😶  Did this happen on the release build, or did you have the issue on a version you compiled by yourself?

**Comment by DagAgren** [comment]
Release build. Luckily I had only one or two tiny changes so no big deal this time, just want to avoid a bigger accident in the future!

**Comment by deepnight** [comment]
Ok, thank you, I'll check that :)
