### ISSUE TITLE
Add "empty" as a case in rules.

### ISSUE THREAD

**Issue by DagAgren** [deepnight/ldtk#487]
Currently, there is no way I can figure out to use the empty state of IntGrids in a rule. I can have a rule that says "not this specific type" but one that says "this tile is empty". I can add a type that represents empty cells, but that seems a bit pointless.

**Comment by deepnight** [comment]
You can use the _Anything_ value, with right click, which will then mean _Nothing_.

**Comment by DagAgren** [comment]
Oh, of course. A bit tricky to discover but makes sense!

**Comment by deepnight** [comment]
I'll see if I can make that easier to understand :)
