### ISSUE TITLE
Win7 empty window at startup

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#498]

**Comment by harshetmaruff** [comment]
I have this same issue in 0.9.3 in my linux computer

**Comment by FloatingBanana** [comment]
Same issue here, but I've found a solution by running it in compatibility mode

**Comment by flamendless** [comment]
Hi, Linux user here, same issue. ive compiled from source. I just get a blank window with only `Debug Tools` in the toolbar.
there was no error/issue during compilation and building.

Specs:
OS: Manjaro Linux x64
WM: i3
RAM: 3GB
OpenGL: OpenGL 2.1

**Comment by runkanrenchu** [comment]
I have the same issue in Windows 7 64 bits; solved by applying compatibility mode (windows vista).

**Comment by deepnight** [comment]
This issue will need to be re-checked after update 0.10.0

**Comment by deepnight** [comment]
Seems fixed in 0.10
