### ISSUE TITLE
Feature: Simpler Json schema structure in TilesetDefinition

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#506]
In `TilesetDefinitions` for `enumTags` and `customData`, I was wondering if there could be a special named definition structure to these instead of having quicktype handle the object structure?

Currently, I would need to traverse the object's internal data to get what I'm looking for, which is slightly more difficult than normally getting data by traversing deeper (in my case for c#, both the  `enumTags` and `customData` are of type `Dictionary<string, object>[]` from QuickType), so I'd be interested in making this data easier to access.

I'm open to clarification or discussion if needed 🙂

**Comment by Cammin** [comment]
Example of what they look like in c#:
![image](https://user-images.githubusercontent.com/55564581/149499973-1132565d-129f-41dd-b6c9-bfdf2a2edc2e.png)

**Comment by deepnight** [comment]
Fixed in 0.10
