### ISSUE TITLE
Entity Layer offset doesn't apply visually

### ISSUE THREAD

**Issue by KikooDX** [deepnight/ldtk#512]
Hello. I started a project that uses offset on the entity layer, and figured than meanwhile the contouring, movement preview and the grid have the offset applied, placed entities and placement preview do not have the offset applied on drawing.

*Screenshots bellow showcase the issue with a -8 X offset on a 16×16 grid.*

![image](https://user-images.githubusercontent.com/30863886/121358170-ae045780-c932-11eb-938e-5be94a8b9fec.png)
![image](https://user-images.githubusercontent.com/30863886/121358348-d9874200-c932-11eb-8c7f-a5f6019e6c9f.png)
![image](https://user-images.githubusercontent.com/30863886/121358467-ef950280-c932-11eb-9109-e2b3be418c6f.png)

Thank you for your attention.

**Comment by marcus-robinson** [comment]
I've raised a PR with a fix for this issue: https://github.com/deepnight/ldtk/pull/541

**Comment by deepnight** [comment]
Merged :) Thanks!
