### ISSUE TITLE
Interface bug - Can't fully access +Field nor +Array buttons 

### ISSUE THREAD

**Issue by stickynoteme** [deepnight/ldtk#525]
Even in full screen I can't fully access the  +Field buttons nor +Array Buttons:

Display Details: 1920 x 1440 @175 DPI

![2021-07-31_082712](https://user-images.githubusercontent.com/43216581/127744722-494ff8e8-ab16-4a26-a442-df07bde0d5eb.jpg)

**Comment by stickynoteme** [comment]
Even worse when you get more fields then the box can handle no scrolling can be done and they just become inaccessible.

![2021-07-31_165526](https://user-images.githubusercontent.com/43216581/127754980-d28c524e-cf1a-459f-a215-df033996c151.jpg)

**Comment by deepnight** [comment]
Until the fix, you can reduce the size of the general UI from the settings:

 - press `F12`,
 - adjust `General UI scale`
