### ISSUE TITLE
Ldtk destroy layer content

### ISSUE THREAD

**Issue by ironpowertga** [deepnight/ldtk#526]
When i open my map with ldtk, i have this message : 
![image](https://user-images.githubusercontent.com/24843378/128595423-c4f17566-c013-4515-b4f4-c8010645d6c4.png)

INFO : If i put my all torch image everything work

Map result draw with LDtk:
![image](https://user-images.githubusercontent.com/24843378/128595460-a9ae2edd-f7a9-49d7-ab55-6e4837fc22ae.png)

Map result draw with my program
![image](https://user-images.githubusercontent.com/24843378/128595394-00adc4f7-25f6-4107-8aa5-67165a719738.png)

So now if i save the map with ldtk i will lose all my work.

**Comment by deepnight** [comment]
This is fixed in 0.10
