### ISSUE TITLE
Mac redist

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#53]
Help needed here :) 

It seems that, in order to build an Electron app on Mac, you need an actual Mac computer. Anyone could help about this? Any alternative solution?

**Comment by sangohan** [comment]
I have a mac that I can run the distribution build on, if that's all that's needed!

**Comment by sangohan** [comment]
I don't have a mac developer license (don't want to pay for it...) but i can build a working version that's self signed. I suppose anyone downloading it will have to just trust me (and that my machine isn't compromised with malware). 

I have made a test release on my clone: feel free to use, or link it. https://github.com/sangohan/led/releases/tag/cdcdd31

**Comment by wolfgraphicsllc** [comment]
I have an idea I own a game publishing studio have not released anything other than a build for a game jam on simmer.io
https://simmer.io/@Reds088/lone-shark. and have some in production i also am trying to get a blog spot going on my site you can see a few i have on there is your game is free for users i could put it on my site or if you sale it i could do that too and just do a agreed upon % from it and i have a lic for the google play store and thinking about doing a steam one when production work gets further along.

**Comment by qkdreyer** [comment]
https://github.com/deepnight/led/suites/1267659522/artifacts/19486321 works 💯

**Comment by jminor** [comment]
@qkdreyer that build didn't work for me until I ran this fixer script. It looks like the zip archive you made lost the executable bits, and turned the symlinks into just text files. This script restores them. Note you have to cd into the LED.app/Contents folder first.

```
#!/bin/sh

# first cd into LED.app/Contents
# then run this script

chmod +x MacOS/LEd

chmod +x Frameworks/*.app/Contents/MacOS/*

for i in Electron\ Framework Squirrel Mantle ReactiveCocoa
do

	rm "Frameworks/$i.framework/Versions/Current"
	ln -s A "Frameworks/$i.framework/Versions/Current"

	rm "Frameworks/$i.framework/$i"
	ln -s "Versions/Current/$i" "Frameworks/$i.framework/$i"

	rm "Frameworks/$i.framework/Helpers"
	ln -s "Versions/Current/Helpers" "Frameworks/$i.framework/Helpers"

	rm "Frameworks/$i.framework/Libraries"
	ln -s "Versions/Current/Libraries" "Frameworks/$i.framework/Libraries"

	rm "Frameworks/$i.framework/Resources"
	ln -s "Versions/Current/Resources" "Frameworks/$i.framework/Resources"

	chmod +x "Frameworks/$i.framework/$i"

done
```
