### ISSUE TITLE
Add support for rectangle of tiles to Entity display options

### ISSUE THREAD

**Issue by niccolofavari** [deepnight/ldtk#533]
Hello!
while placing pickups and other entities in my level, I noticed the visual representation isn't optimal. I can only select one tile even if the entity is bigger.

<img width="455" alt="Capture3" src="https://user-images.githubusercontent.com/183181/133929015-5bb1fc15-c4c1-4ed4-9501-4f344cd04fe1.PNG">

<img width="998" alt="Capture" src="https://user-images.githubusercontent.com/183181/133929017-5be11c23-0baa-4c86-939a-872b8bc2bf2a.PNG">

<img width="756" alt="Capture2" src="https://user-images.githubusercontent.com/183181/133929018-2d7d8cce-2b14-4c54-991a-a73231af8e9d.PNG">

Are you planning on supporting multiple tiles for entity representation?

**Comment by deepnight** [comment]
Yes, that's planned :)

**Comment by deepnight** [comment]
Done in 0.10
![tileRect](https://user-images.githubusercontent.com/1671695/150143449-eab7081b-f4ae-4df7-8860-d1e73be2ea5e.gif)
