### ISSUE TITLE
Zoom without mouse wheel

### ISSUE THREAD

**Issue by Riato-Yagami** [deepnight/ldtk#536]
It would be great to have a way to **zoom in and out without using the mouse wheel**, as an **accessibility** feature _(also mine is broken)_

**Comment by b-jam** [comment]
Adding to this, an alternative to mouse wheel click+hold to pan would be much appreciated

**Comment by deepnight** [comment]
> Adding to this, an alternative to mouse wheel click+hold to pan would be much appreciated

For this one, you can use the Photoshop style shortcut: hold `SPACE` + `left mouse click`

**Comment by deepnight** [comment]
Done in 0.10.0
