### ISSUE TITLE
Touchpad Support

### ISSUE THREAD

**Issue by alterae** [deepnight/ldtk#537]
I'm using LDtk for a project at the minute, and due to circumstances I have to do a substantial amount of work on a MacBook without access to a mouse.

**Expected behavior:**

Scrolling with the trackpad should work as expected—panning the view.  Pinching with two fingers should zoom in and out.

**Actual behavior:**

Scrolling vertically with the trackpad zooms.  Scrolling horizontally or pinching has no effect.

I appreciate LDtk immensely, but at present it is quite difficult to use without a mouse.

**Comment by orangy** [comment]
Same here. Also, I'd like to erase with something like Ctrl+LMB, instead of two-finger which is RMB

**Comment by deepnight** [comment]
Duplicate #278
