### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by runkanrenchu** [deepnight/ldtk#549]
Even without any background apps open, LDtk takes up about **96%** a of the CPU (~2.20 GHz) by itself. This is reduced to 0 whenever the app runs in the background (e.g whenever i switch to the desktop, etc), but rockets again as soon as i focus on it. I don't have the best setup at all, so I perfectly understand this might be a hardware issue more; but if this is not a bug/doesn't really have a solution, i think it's still a good way to hint at more optimisation ideas.

OS: Windows 7 64 bits (SP1)
Processor: Intel Pentium 2.20GHz.
RAM: 4GB.
LDtk version: 0.9.3.

I perfectly understand that running LDtk with a damn pentium and 4gb of RAM is probably not the best idea. But it still kinda surprises me how i can run Adobe Animate, Spotify, and Chrome at the same time but not LDtk alone. so this kinda gives me the idea it might be a software related thing too. i sadly dont have the option to move to a better setup or even update my OS; apologies.

Thank you!

**Comment by deepnight** [comment]
This might be partially addressed in 0.10.0, as this update includes lots of various optimizations & fixes. If you're able to build from source, you may want to try latest update by yourself, or I can prepare a test build for you.

**Comment by deepnight** [comment]
Needs testing with 0.10

**Comment by deepnight** [comment]
Seems fixed in 0.10, closing. Feel free to re-open if anything suspicious still happen after update.

**Comment by keithclark** [comment]
I'm running into high CPU usage on my Mac.

Using LLDB I managed to [start the app with debugging](https://stackoverflow.com/questions/45485262/how-to-debug-electron-production-binaries) and using Chrome devtools I can see the WebGL canvas context is continually repainting itself. This happens even if the canvas content hasn't changed and also when the app is idle.
