### ISSUE TITLE
Glitchy graphics

### ISSUE THREAD

**Issue by HolyBlackCat** [deepnight/ldtk#552]
![pic](https://user-images.githubusercontent.com/20289055/147786740-06da3c73-6b39-46f6-8921-7e529813e583.png)

This glitch isn't constantly visible, but flashes randomly for a single frame, somtimes several times in a row, always in the same pattern.

The OS is Ubuntu 20.04, and I'm using the Linux build. The videocard is AMD Radeon RX 580, with the open-source Mesa drivers. No other applications show this behavior, and my videocard isn't dying, as far as I know. I'm using a 144hz monitor.

**Comment by HolyBlackCat** [comment]
Replacing Ubuntu 20.04 with 21.10 seems to have fixed it. Possibly an AMD driver bug?

**Comment by deepnight** [comment]
Ok, thanks for reporting this :)
