### ISSUE TITLE
"Duplicate all selected elements" ignores entity max count rules

### ISSUE THREAD

**Issue by JarrodDoyle** [deepnight/ldtk#561]
**Version:** 0.9.3

**Expected behaviour:**
Any duplicated entities stick to their max count behaviour (as they would when placing a new entity).

**Actual behaviour:**
Max count rules are ignored.

**Comment by deepnight** [comment]
Thanks for reporting this one :)

**Comment by deepnight** [comment]
Fixed in 1.2.0
