### ISSUE TITLE
Allow to set entity/level position/sizes in "cells" units

### ISSUE THREAD

**Issue by eliasdaler** [deepnight/ldtk#562]
Related to #514 
It would be good to be able to quickly make levels of "16x9 cells", for example (same for positioning and sizes for entities).

Ideally px/cells unit should also be selectable in "CURRENT LEVEL" menu for "World coords" and "Size".

P.S. And maybe even add an option to specify "use "cells" by default"? Because I very rarely want to specify something on pixel level and operate in "cells" units most of the time. Another option would be to "remember" the last selected unit and have it be a default one in all menus if you switch from "px" to "cells".

**Comment by deepnight** [comment]
Done in 0.10 

![image](https://user-images.githubusercontent.com/1671695/149754230-f57d7b89-1e8c-4000-a963-2ec793588982.png)
