### ISSUE TITLE
Can't select entities on current level if they overlap with another level

### ISSUE THREAD

**Issue by eliasdaler** [deepnight/ldtk#563]
For example, if I move "LevelC_enter" entity from "LevelC" like in the screenshot:
![image](https://user-images.githubusercontent.com/1285136/149530707-40ed3028-f08b-4249-84a9-fcbc982fe000.png)
... then I can no longer select it, because selecting levels has higher priority than selecting levels, "LevelB" gets selected if I click on the entity:
![image](https://user-images.githubusercontent.com/1285136/149531236-14ba6574-28ff-475f-969c-21e6b6e69a5f.png)

**Comment by deepnight** [comment]
Duplicate #523 (solving this issue will address both problems)
