### ISSUE TITLE
Canvas is turning dark after loosing focus for some time.

### ISSUE THREAD

**Issue by azagaya** [deepnight/ldtk#569]
Hi!
I've started working with ldtk today, with Ubuntu 21.04 and a GeForce 1650ti gpu. Sometimes, after loosing focus, the canvas turns dark blue and i have to restart ldtk. See image below
![image](https://user-images.githubusercontent.com/46932830/150174897-13b42d1e-005c-46b6-aa05-77d402b1cc44.png)

It doesnt happen every time i loose focus, its been a bit hard to reproduce but it happened to me three time this morning.
Thanks

**Comment by deepnight** [comment]
After some verification, it seems like after a webGL context loss, you can't do much apart from re-initializing everything. 

So I added various new warning messages to explain what happened and recommend to save & restart.
