### ISSUE TITLE
0.10.0: Field definition's type is an object instead of an enum string

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#581]
In 0.10.0 branch:

While setting up c# code from the json schema file, I wasn't able to deserialize the entity def's `LevelFieldType` `type`. The json reader is expecting a single string value to then convert to an enum, but it was an object composed of 2 values instead. (See example text)

I'm thinking that the type `LevelFieldType` might also be a misleading name since this is also able to be used for entity field defs too. 🤔 

Being able to access this new `type` value will solve my multi-lines issue from here (#503), as that was what I was looking for to discern if it's a string or multi-lines type. 👍 
Though I wonder if that `__type` type is still labelled as string even though it's multilines over in that issue.

Example:
`"type": { "id": "F_Enum", "params": [5] },`
```
{
	"identifier": "weapon",
	"__type": "LocalEnum.ItemType",
	"uid": 29,
	"type": { "id": "F_Enum", "params": [5] },
	"isArray": false,
	"canBeNull": false,
	"arrayMinLength": null,
	"arrayMaxLength": null,
	"editorDisplayMode": "NameAndValue",
	"editorDisplayPos": "Above",
	"editorAlwaysShow": false,
	"editorCutLongValues": true,
	"editorTextSuffix": null,
	"editorTextPrefix": null,
	"useForSmartColor": false,
	"min": null,
	"max": null,
	"regex": null,
	"acceptFileTypes": null,
	"defaultOverride": null,
	"textLanguageMode": null,
	"symmetricalRef": false,
	"allowOutOfLevelRef": true,
	"allowedRefs": "OnlySame",
	"allowedRefTags": [],
	"tilesetUid": null
},
```

There is a possibility that this has already been fixed, as I'm using a commit from roughly when entity chaining was added.

**Comment by deepnight** [comment]
As mentioned on discord, `type` is an internal field. It can be a simple string or an object, depending on the enum type (without or with arguments).
I'll fix the multi lines in another way :)

**Comment by Cammin** [comment]
Because quicktype has an issue with it being an object that isn't explicitly typed, I needed to work around this by defining a type myself, but I need to make sure this isn't overwritten whenever I regenerate my quicktype type definitions.
![image](https://user-images.githubusercontent.com/55564581/155893725-c4f1695e-ea0a-480a-859f-f90d3dad0a17.png)

Perhaps in the json schema file, this `type` could be an explicitly typed value in the schema?

**Comment by deepnight** [comment]
I tried a fix in beta 6 where the `type` value is now _always_ exported as a `String`. 

Your example would now be, in the JSON:
```json
"type": "F_Enum(5)",
```
Instead of:
```json
"type": { "id": "F_Enum", "params": [5] },
```


Beta 6 will be here very soon:
https://ldtk.io/files/beta

I hope this will fix this problem.

**Comment by Cammin** [comment]
This new workaround is on the right track. 👍 
However I tried this, and it throws an exception. 
This is because the generated schema converter file is strictly set up to only accept these string values, otherwise it throws an exception:
![image](https://user-images.githubusercontent.com/55564581/160343472-3b117f09-1649-4276-9e88-6dd54235ba07.png)

My current hack fix is to remove the text after the first round bracket, but could still be more ideal. It's certainly better to work with though :)
![image](https://user-images.githubusercontent.com/55564581/160344119-6375d0f4-ddd9-4257-984c-574e21054ea7.png)
I will think of some ideas, but it's a tricky little puzzle here 🤔

**Comment by deepnight** [comment]
Hmmm... This one will definitely much complicated to fix. Not sure it could be done through Quicktypes/Schema fixes.

**Comment by deepnight** [comment]
Do you it would pose any issue if I changed the "value type" of `type` to be `dynamic` (ie. untyped)?
As it's an internal field and __type if already here for human readable value, I guess it's ok?

**Comment by deepnight** [comment]
To "fix" the problem, the `type` value type will now be `String` instead of Enum, but the description will keep the listing of possible String values.

I attached the C# quicktype file: [quicktype.zip](https://github.com/deepnight/ldtk/files/8361340/quicktype.zip)

**Comment by deepnight** [comment]
Here is the JSON schema section for this one:

```json
"type": {
	"description": "Internal enum representing the possible field types. Possible values: F_Int, F_Float, F_String, F_Text, F_Bool, F_Color, F_Enum(...), F_Point, F_Path, F_EntityRef, F_Tile",
	"type": [
		"string"
	]
},
```
