### ISSUE TITLE
0.10.0: EntityReferenceInfos doesn't appear to exist after quicktype

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#582]
In the latest 0.10.0 commit, the Json Schema file doesn't appear to output this type of definition. `EntityReferenceInfos`

There appears to only be one match found, which is in the description of the value field: (Image)
![image](https://user-images.githubusercontent.com/55564581/151507309-ccb905cf-2da4-4768-b477-e939271e4237.png)

**Comment by Cammin** [comment]
It's interesting because I do see that defined in the schema file itself. Must be a loss in translation in some way

**Comment by deepnight** [comment]
Hmm, I'll check if there's some quicktype option to not discard unused types

**Comment by Cammin** [comment]
Just to validate the reason was that the unused type was being discarded, I tried testing that it was being included by inserting an explicit value reference to test (In field instance):
![image](https://user-images.githubusercontent.com/55564581/151953697-9e98ce62-cd1a-4d73-b584-40ab77e86ce4.png)  
Then in the schema result, it does include it. 
![image](https://user-images.githubusercontent.com/55564581/151953535-9d73a8ce-226c-4d2c-a138-10103b6b6c7f.png)  
So yes, it does seem like the reason that it's not being included is that there is no explicit type being specified in the field instance's `__value`.

Maybe a solution could be to have `__value` use the keyword `oneOf` to add the explicit possible type? Just a possible idea, but I'd be interested in trying this out myself to see if that might work.

If I discover something that works, then I'll submit a pull request 🙂

**Comment by deepnight** [comment]
So I'm stuck here: the schema JSON is correct, but we have either:
 - __value is untyped, so no reference to the classes such as EntityReferenceInfos, and the quicktype files don't have them
 - __value is typed, but only the first class is present in the quicktype file

**Comment by deepnight** [comment]
I'm closing the issue for lack of a better solution for now 🤷‍♂️  
Feel free to comment if you think we should keep this open.

**Comment by Cammin** [comment]
The only solution I can think of right now is to make the value an explicity typed object, but I understand it would affect existing importers.

**Comment by Cammin** [comment]
There is a possible solution, but the cons are that is the json becomes larger in size, and would break the json for backwards compatibility.

The `__value` could be changed into an explicitly typed structure like `FieldInstanceValue`, and it can contain many values like:
`intValue`, `floatValue`, `stringValue`, `entityReference`, `point`, etc.
Then that way, the custom types values are explicitly typed, and would be able to auto-include inside the generated quicktype data.

**Comment by Cammin** [comment]
Another option could be to only make all of the complex types into one data type so that it conforms with `oneOf`'s single-class rule.
For example, there could be a complex type that contains 3 other types: 
```
class ComplexType 
{
   GridPoint,
   FieldInstanceTile,
   EntityReferenceInfos,
}
```
And then only the complex type is included for the `oneOf`:
```
"oneOf": [
    { "type": ["integer"] },
    { "type": ["number"] },
    { "type": ["boolean"] },
    { "type": ["string"] },
    { "$ref": "#/otherTypes/ComplexType" },
]
```

**Comment by deepnight** [comment]
I tried a fix by adding an object value in the root of the JSON (which isn't really used): `__FORCED_REFS`


```json
"__FORCED_REFS": {
	"description": "This object is not actually used by LDtk. It ONLY exists to force explicit references to all types, to make sure QuickType finds them and integrate all of them. Otherwise, Quicktype will drop types that are not explicitely used.",
	"properties": {
		"TilesetRect": {
			"$ref": "#/otherTypes/TilesetRect"
		},
		"FieldInstance": {
			"$ref": "#/otherTypes/FieldInstance"
		},
		"EntityInstance": {
			"$ref": "#/otherTypes/EntityInstance"
		},
		"Definitions": {
			"$ref": "#/otherTypes/Definitions"
		},
                "..."
```

This value is optional, so it shouldn't mess up with your parser. 

Schema.json
[JSON_SCHEMA.zip](https://github.com/deepnight/ldtk/files/8340766/JSON_SCHEMA.zip)

Quicktype files
[quicktype.zip](https://github.com/deepnight/ldtk/files/8340767/quicktype.zip)

Could you please check if it works for you?

**Comment by Cammin** [comment]
I've tested this and can conclude that this works! Awesome that we were able to figure this out. Quite a clever workaround to quicktype's limitation.

**Comment by deepnight** [comment]
Thanks 🙇
