### ISSUE TITLE
Fix entity reference rendering

### ISSUE THREAD

**Issue by nyalloc** [deepnight/ldtk#591]
The entity reference doesn't take the entity origin into consideration.

![image](https://user-images.githubusercontent.com/7504843/151895896-640076d9-40eb-46c4-b5d9-8703d5315ee2.png)
![image](https://user-images.githubusercontent.com/7504843/151895931-a2f1e6ca-4187-4c97-a2af-e5ad4ba1fd36.png)

Strangely, it does take the entity origin into consideration with the preview!
![image](https://user-images.githubusercontent.com/7504843/151896033-9f45e0c8-0ff4-4669-a047-5ba8e00ace36.png)

**Comment by deepnight** [comment]
I added a distinct display mode for refs, because in some case, linking "centers" looks better :)

![image](https://user-images.githubusercontent.com/1671695/151972635-175baac1-5c20-4279-8523-ef9816f4b846.png)
