### ISSUE TITLE
0.10.0: Multi-worlds support doesn't set levels in the World class

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#599]
By choosing to turn on multi-worlds and saving, it seems to not set to the levels array in the `World` class.

```
"levels": [],
"worlds": [{ "iid": "a704c9f0-66b0-11ec-9a10-0760715c45bf", "identifier": "World", "worldGridWidth": 256, "worldGridHeight": 256, "worldLayout": "Free", "levels": [] }]
```

As a result, it seems to also further affects the LDtk UI from functioning properly after re-opening the .ldtk file:
![image](https://user-images.githubusercontent.com/55564581/152305166-cc72be3c-4122-42cf-baac-5cf56589a749.png)

App built from commit e7cb0f1311e874d74ad6b0fc86a7b4b50f4fa1a2
appBuildId: 456607 (Let me know if this value is helpful)

**Comment by deepnight** [comment]
Thanks, I'll fix that :)
No need for the appBuildId in general, it's mostly an internal info, unless I'm investigating on a code regression somehow 👍

**Comment by deepnight** [comment]
That's fixed in the `multiWorldsInternals` branch. I will merge it after testing.
