### ISSUE TITLE
0.10.0: Multi-worlds support breaks deserializing json

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#600]
By choosing to turn on multi-worlds, it affects the json file from deserializing correctly.
The reason is coming from these values being null instead of expecting an int in the `LdtkJsonRoot`:
```
"worldLayout": null,
"worldGridWidth": null,
"worldGridHeight": null,
```

A solution I found was to make these values nullable. 
Perhaps that be considered a change into the Json Schema to fix.

App built from commit e7cb0f1311e874d74ad6b0fc86a7b4b50f4fa1a2
appBuildId: 456607

**Comment by deepnight** [comment]
All right, I'll see how to fix these

**Comment by deepnight** [comment]
Fix in `multiWorldsInternals` branch, merge coming after testing.

**Comment by deepnight** [comment]
Note: those fields are now `nullable`, and I also moved the `defaultLevelWidth` and `defaultLevelHeight` to the worlds array because they were more relevant as world related fields.

**Comment by Cammin** [comment]
Thanks for addressing these. Glad I could help, and thanks for the effort 🙂
