### ISSUE TITLE
Adjust order of UI Tabs (top left)

### ISSUE THREAD

**Issue by kaiiboraka** [deepnight/ldtk#603]
As a bit of organizational feedback, I feel like the order of the tabs could be improved. Right now it's World, Project, Current Level, then the rest. 
![image](https://user-images.githubusercontent.com/7596816/152593841-609e7801-c03a-4523-b4bd-c7df3fb97c31.png)

However I feel like it would make sense for Project to come first, followed by world, then level, as that's the hierarchy of those elements. I realize, however, that part of the reason it's in the current order is because World has a different hotkey than the rest of the tabs which use the Func. keys.

While we're at it, I think it makes sense to put the quit and settings up in the left corner like how many programs have the "File" menu first in the list. Here's a mockup of my revised order. This also puts the App Settings next to the Project Settings, and leaves the tips out where they're most visible. I also recolored, switching Project and World to match World to Level, and made Project unique/stand out.
![image](https://user-images.githubusercontent.com/7596816/152594908-f33854f9-0126-42f1-98e9-39a3ea8954a3.png)

**Comment by deepnight** [comment]
I agree with many aspects, so here are the changes:
 - F1->F6 shortcuts weren't that great and lead to some bad UI design choices, as you mentioned (eg. project/level button orders). So I replaced them with more intuitive ones:
   - `P`: project panel
   - `L`: layers definitions
   - `E`: entities definitions (previously "Toggle Select empty spaces")
   - `U`: enums definitions
   - `T`: tilesets definitions (previously "Toggle Tile stacking")
 - This also frees F1-F12 shortcuts for layer selection, which frees 1-9 numbers for something else, like IntGrid value selection (related #454)
 - to be consistent with **Home** screen UI, "App Settings" and "Exit" are to stay on the right side ; see this screen:
  ![image](https://user-images.githubusercontent.com/1671695/152681404-504b1d25-9a87-479d-b55a-49257ef119f1.png)


New layout:
![image](https://user-images.githubusercontent.com/1671695/152681698-b3ff22e5-2dab-400c-8474-442540d6086c.png)

New layout (compact):
![image](https://user-images.githubusercontent.com/1671695/152681707-f6f844e7-d526-4a35-9b14-f8cbee5bf515.png)

**Comment by Cammin** [comment]
This is how I envisioned it. Looks great! 🙂

**Comment by deepnight** [comment]
Available in latest build.
