### ISSUE TITLE
Difficult to read text

### ISSUE THREAD

**Issue by nyalloc** [deepnight/ldtk#606]
These are 8x8 entities with string fields that are set to display in editor. Their text is so small that it can't be read. Maybe there needs to be a minimum text size set?

![image](https://user-images.githubusercontent.com/7504843/152657112-8ccc7fe7-b717-45be-a1ae-ca69528d6b45.png)

![image](https://user-images.githubusercontent.com/7504843/152657179-f273fd98-d8f4-46fe-82d7-eb5ce8374e62.png)

This also seems to be an issue in the "All features" sample. Quite a lot of the text is illegible at the initial zoom level, and even fully zoomed it is difficult to read some of the text.

![image](https://user-images.githubusercontent.com/7504843/152657323-2ad66dc5-a142-4de0-b179-028c0f4e0bdc.png)

![image](https://user-images.githubusercontent.com/7504843/152657351-5b28b06f-cf45-4e64-9a7f-1d63117e4ab8.png)

**Comment by deepnight** [comment]
Thanks!
This should be fixed in latest build:
 - I fixed how "String" fields affect entity visual fields
 - if you adjust the Editor UI scaling in App Settings, this should now properly affect the size of these visual blocks.
