### ISSUE TITLE
New __tile field to FieldInstance

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#610]
Was discussed on discord.
![image](https://user-images.githubusercontent.com/55564581/153557390-48c935ec-09b4-4252-bfa2-959643f5149b.png)

So maybe the idea could be that this field would be similar to data like for `FieldInstanceTile`, where it's an object that contains `tilesetUid` and `srcRect`?

Of course, it's only an idea and could be discarded if it's more of a json size cost vs benefit, but would make accessing a field instance's enum tile much easier.

**Comment by deepnight** [comment]
Done in latest build. Online doc was also updated: https://ldtk.io/json/next/
