### ISSUE TITLE
Path resolution issues when opening level from command line argument

### ISSUE THREAD

**Issue by NeoRaider** [deepnight/ldtk#611]
I'm not sure if this is a supported feature, but it is possible to open an `.ldtk` file by passing it as a command line argument to the LDtk binary. However, it seems that path resolution is broken when the level file is specified as just a filename without a directory (to open a file from the current directory):

- Referenced tile images are not found, even when they exist and are loaded fine when opening the level through the file open dialog
- The "Locate the file" button in the subsequently displayed "File not found" dialog is nonfunctional, only printing the following message on the terminal:
```
Error occurred in handler for 'openDialog': TypeError: Default path must be a string
    at openDialog (electron/js2c/browser_init.js:45:2322)
    at Object.showOpenDialogSync (electron/js2c/browser_init.js:45:4024)
    at /tmp/.mount_LDtk 0yEqlWB/resources/app.asar/assets/main.js:895:40
    at electron/js2c/browser_init.js:189:558
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8739)
    at WebContents.emit (events.js:310:20)
```
As soon as any directory component is included in the path, the issue disappears. Specifying the file as `./level.ldtk` can be used as a workaround.

Version: 0.9.3
Platform: Arch Linux

Both the 0.9.3 official build and a local build from the Arch User Repository are affected. I have not tried the current master.

**Comment by deepnight** [comment]
Thanks, I'll try to fix that one :)

**Comment by deepnight** [comment]
Fixed
