### ISSUE TITLE
SmartColor for EntityInstance in json

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#618]
~~I have no particular need for it myself~~ but could be useful in case an entity instance has a certain colour set for itself, or if it was set up from a colour field instance.
This would be a similar scenario to how the entity instance has a TilesetRectangle setup for it, where it's a convenient field to access.
In fact, levels have a `SmartColor` in their json, so it would be very fitting to also include this with entity instance.

**Comment by deepnight** [comment]
Right 🤔 I'm adding it!

**Comment by deepnight** [comment]
Done
