### ISSUE TITLE
intGridValues is not null for non IntGrid layers

### ISSUE THREAD

**Issue by Madour** [deepnight/ldtk#626]
I was testing the version 0.10.0-beta2, and noticed that all the layers that are not IntGrid have a `"intGridValues"` field with the following array `[{ "value": 1, "identifier": null, "color": "#000000" }]`.

Since this field is IntGrid layers only, I was expecting it to be null or empty for other layer types.

**Comment by deepnight** [comment]
Thanks for reporting, I'll check this out 🤔
