### ISSUE TITLE
Recursive rules?

### ISSUE THREAD

**Issue by drhayes** [deepnight/ldtk#627]
A wild feature request appears: recursive rules!

I was looking for something to help me make waterfalls and ladders, and maybe decorative stalagmites and stalagtites, that kind of thing. They all have a kind of base case, a variable length, and an endstate.

So you could imagine that I have a ceiling, and a rule that runs with a percentage (like 10%) that puts down the first tile of a stalactite. Then one of the recursive rules picks it up; maybe it has a percentage chance associated with it as well that determines how long the stalactite is.

Or maybe I have a bunch of ground and water tiles, and when a water tile has no ground tile beneath it it keeps putting down water tiles until it finds ground or finds water? Something like that?

**Comment by deepnight** [comment]
This is more the kind of things done by TileKit (https://rxi.itch.io/tilekit) and it's whole different level in term of content generation :) 

Right now, rules in LDtk are only used to generate visual elements, and not data to be reused in generation loop.

**Comment by drhayes** [comment]
Sorry I didn't respond sooner!

I understand the complexity it would bring and appreciate maintaining the right (good!) UX. Worth a shot. :)
