### ISSUE TITLE
Grouped autotiles extend outside level

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#628]
I see in the entities example that when it's built into my game engine, the auto tiles that are 2x2 seem to extend outside the bounds of the level.  (downwards and rightwards)  
![image](https://user-images.githubusercontent.com/55564581/155494375-61c1dd8d-e986-428b-8389-77dd7bcd1f29.png)

I'm wondering what could be the explanation for it, like if there are extra tiles being included in the layer instance auto tiles array.
Is this intended? Or could be an issue on my side?

(Tested using the sample files from 0.10.0-beta3 tag, but this was also observed in earlier versions)

**Comment by Madour** [comment]
This happens because the rule that renders these tiles uses a rectangle of tiles

![image](https://user-images.githubusercontent.com/11854124/155520390-f3c372ee-24de-4b38-8809-ddf564833753.png)

So you see 4 tiles are rendered, but they all have the same coordId (the one of the purple tile)
