### ISSUE TITLE
Bug : __neighbours array not updated after deleting levels

### ISSUE THREAD

**Issue by Madour** [deepnight/ldtk#629]
After deleting a level in the editor and saving, the __neighbours array of the other levels still contains the Iid/Uid/dir data of the deleted level.

The bug affects levels that are on the same world depth or on different world depth.

Slightly related question :  shouldn't __neighbours array contain only neighbours from the same world depth ?

**Comment by deepnight** [comment]
Woops, still happening. Needs another fix.

**Comment by deepnight** [comment]
Fixed
