### ISSUE TITLE
[Feature Request] Smart Repeat option for tile rects

### ISSUE THREAD

**Issue by TomatechGames** [deepnight/ldtk#630]
similar to standard repeat, but without repeating corner tiles, only repeating horizontal edge tiles on the y axis, and only repeating vertical edge tiles on the X axis.

This selection of tiles (48px X 48px) when applied to an entity that takes up a (64px X 80px) space...
![image](https://user-images.githubusercontent.com/51051235/155711234-6b944358-df00-4ae9-8592-583daf07e789.png)

would show as
![image](https://user-images.githubusercontent.com/51051235/155711539-ef0f9ef9-4210-4128-8f38-43d1b1c83f22.png)

there could also be an option to set the edge boundary to take up more or less space (for example, a tree with adjustable height could be set up to not repeat the area with leaves)

**Comment by deepnight** [comment]
Interesting 🤔 This is known as 9 slicing and it's fairly easy to produce. I'll see what could be done.
