### ISSUE TITLE
Quicktype Fixes

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#634]
Hi, I wanted to discuss again the JSON schema and quicktype generating scripts.

The amazing part about Quicktype+JsonSchema is how easily it can be to update LDtk's JSON data and I am very grateful that this is possible.

But in its current state (beta3), it requires some manual tweaking after regenerating the schema text in the respective code language (c# in my case).
Because of this, it can discourage updating the schema data often, as it can become an undertaking of adding workaround fixes. The ideal expectation after generating quicktype data is that "It just works".

There were a couple github issues that were closed, but still present these issues:
- FieldDef's type issue. (Possibly could need an explicit type defined in the schema to fix. I commented on it, and was wondering if it could be re-opened) 
https://github.com/deepnight/ldtk/issues/581
- Some types do not exist due to implicit references (More of a quicktype issue, but possibly able to be worked around) https://github.com/deepnight/ldtk/issues/582

I've also gotten some messages from others asking me about this too, where they were wondering why the c# deserializing threw an error for FieldDef's type not being a string. So it could end up spinning into a problem that more than one user are facing.

Of course, I personally care a lot about the quicktype feature because of how convenient it can be for anyone, and it's such an amazing feature to have a json schema to generate all types with XML comments for types/fields so quickly. 
Especially for the peace-of-mind that it's all exact and updated data+documenation without human error.

But right now, it requires upfront fixes to make it deserialize successfully, and requires monitoring that any workarounds aren't overwritten after regenerating the schema data.

I hope that these couple issues could possibly be checked over again to make the schema generation flawless 🙂

**Comment by Sipondo** [comment]
Running into the same issue - generated Quicktype python bindings crash when trying to load levelfieldtypes.

**Comment by deepnight** [comment]
I tried a fix for `type`, see #581

**Comment by deepnight** [comment]
Also tried to fix #582

**Comment by Cammin** [comment]
#582 is good to go, but #581 is still in need of resolution. I really appreciate the fixes coming through so far though 🙂

**Comment by deepnight** [comment]
This should be good now, feel free to close if that's also ok for you :)

**Comment by Cammin** [comment]
Tried it out, and good to go, awesome! 😄
