### ISSUE TITLE
Importing "Test_file_for_API_showing_all_features"  with a C# Quicktype generated loader (dev-0.10.0)

### ISSUE THREAD

**Issue by codefrommars** [deepnight/ldtk#635]
When trying to import the "Test_file_for_API_showing_all_features" file with the C# loader generated using the schema defined at:  ldtk/docs/JSON_SCHEMA.json (dev-0.10.0), there's a runtime problem with the property "type" of a FieldDef. This property is defined in the schema as an enum of ['F_Int', 'F_Float' ... ] but inside the file it might also take an object, e.g. { "id": "F_Enum", "params": [21] }. This gets the import process to fail.

This issue has been mentioned in #634 and #581.

In order to make it work in my project, I modified the JSON_SCHEMA.json file to define the `#/otherTypes/FieldDef/properties/type` as
```
"type": {
	"description": "Internal type enum Possible values: `F_Int`, `F_Float`, `F_String`, `F_Text`, `F_Bool`, `F_Color`, `F_Enum`, `F_Point`, `F_Path`, `F_EntityRef`, `F_Tile`",
	"anyOf": [
		{
			"enum": [
				"F_Int",
				"F_Float",
				"F_String",
				"F_Text",
				"F_Bool",
				"F_Color",
				"F_Enum",
				"F_Point",
				"F_Path",
				"F_EntityRef",
				"F_Tile"
			]
		},
		{
			"$ref": "#/otherTypes/LocalType"
		}
	]
},
```

And added a new structure "LocalType"

```
"LocalType": {
	"description": "Reference to a type defined in the ldtk file",
	"title": "Local Type definition",
	"required": [
		"id"
	],
	"additionalProperties": false,
	"properties": {
		"id": {
			"description": "",
			"type": [
				"string"
			]
		},
		"params": {
			"description": "",
			"type": [
				"array"
			]
		}
	},
	"type": [
		"object"
	]
}
```
Also, `#/otherTypes/TilesetDef/properties/relPath/type` doesn't allow the relPath to be null, but it is null for "Internal_Icons".

In my setup I made the type nullable in the schema.

With these two changes the json file validates against the schema (tested at https://www.jsonschemavalidator.net/ ) and re-generating the Quicktype loader with the modified schema allows to import the file without any problem.

**Comment by deepnight** [comment]
This should be fixed with #581
