### ISSUE TITLE
Support for PNG 24bits

### ISSUE THREAD

**Issue by ldurniat** [deepnight/ldtk#638]
Hi,

I get an error :

> Couldn't read image file:
> tilesets/background.png

Another images from the same folder work fine. After change 24-bit pallete to 256 colors error don't occur.

tilesets/background.png
![background](https://user-images.githubusercontent.com/22639656/156942139-58206733-329c-4b90-8105-43e862bd39f1.png)

I use ldtk v0.9.3-64bits and Windows 10.

Have a nice day:)

**Comment by deepnight** [comment]
The limitation comes from the haxe `format` library which doesn't support PNG with 16bits color depth. 

https://github.com/HaxeFoundation/format/blob/318e49a55f45a836b3fd8ab41215f3649046dfa8/format/png/Tools.hx#L501

Unfortunately, unless someone adds support to the lib, I won't be able to support that 🤷
