### ISSUE TITLE
very slow with 380 to 390 rules

### ISSUE THREAD

**Issue by morganholly** [deepnight/ldtk#644]
if my counting is correct, 351 enabled and 9 disabled on one intgrid layer, and 25 on another intgrid layer. i have a large level for testing all the rules, i had made a small level for seeing it on a realistic map, and i created a large one that i was going to use for procedurally pasting smaller rooms within in godot. over time it has slowed down noticeably and at this point is basically unusable, even with the autotile rendering off. i'm ok with it taking time to preview with the autotiling, but having a way to draw in maps with that turned off that was more performant would be much appreciated. additionally it would have a significant bit of lag when reordering groups.

**Comment by morganholly** [comment]
i am on 0.9.3 on macos catalina 10.15.7 (19H1715). i do not think it is a hardware issue, this is a 2019 high end macbook pro

**Comment by morganholly** [comment]
basically i'd like a mode where i draw in the intgrid values and then manually have it autotile it

**Comment by deepnight** [comment]
Thanks for reporting the problem! 
I have some reworks to be done on then "rendering" side of the app, specifically with AutoLayer rules, which tend to be super slow when you have many ones.

In 1.0 beta 7, the undo/redo was rewritten completely and is about 50 times faster for complex maps. I've also optimized lots of things in 1.0, so this will probably help. Unfortunately, there's no macOS beta for now, only a Win build.

So it would help me a lot if you could send me a copy of your current LDtk project, if you're ok with that. I won't redistribute anything, it's only to have a good example of the "target".

**Comment by morganholly** [comment]
ok i sent an email, hopefully that helps you with optimization

**Comment by deepnight** [comment]
You can check Beta 8 here: https://ldtk.io/files/beta

Please tell me if things are better for your project.

**Comment by morganholly** [comment]
Cool I will try this out soon

Thanks,
Morgan

**Comment by deepnight** [comment]
@morganholly 
Is this issue fixed for you?

**Comment by morganholly** [comment]
So it looks like the beta zip only contained a windows installer. I’m on mac so I unfortunately can’t try out the beta with the current download link

Thanks,
Morgan

**Comment by deepnight** [comment]
> So it looks like the beta zip only contained a windows installer. I’m on mac so I unfortunately can’t try out the beta with the current download link Thanks, Morgan
The 1.1 update is out, with macOS support :) You can download it here: https://ldtk.io

**Comment by morganholly** [comment]
oops i forgot to download and try the beta, i will do that in a moment

Thanks,
Morgan

**Comment by morganholly** [comment]
Yes, this is much much better, thank you!

Thanks,
Morgan

**Comment by deepnight** [comment]
Related #8

**Comment by deepnight** [comment]
Related #984

**Comment by deepnight** [comment]
Things should now run smoother, closing this for now
