### ISSUE TITLE
Fill color on hollow entities not empty when tile

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#658]
When selecting hollow on an entity's editor visual, it means that there should be no fill color as described from the hollow tooltip.

Hollow entities are correctly empty for ellipse and rectangle, but there is still a fill color when choosing a tile which is unexpected.
This behaviour is observable in the GridVania example:  
![image](https://user-images.githubusercontent.com/55564581/161472881-f07ae0ce-0c00-476a-9cdf-f9fcb7f8fc24.png)

**Comment by deepnight** [comment]
This will be fixed in 1.1.1
