### ISSUE TITLE
Duplicating levels also duplicates `iid`s

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#659]
When duplicating levels, the `iid` of entities appears to remain the same.

Repro steps:
-Right-click a level.
-Select duplicate.
-Observe that the iids of entities are the same.

Note:
-Level `iid`s appear to be correctly unique
-The dupe `iid` issue also appears to happen with layers in addition to entities

![image](https://user-images.githubusercontent.com/55564581/161489407-711395e8-dc68-425d-82e5-a5a449fd7c56.png)  
Original level:
![image](https://user-images.githubusercontent.com/55564581/161489594-a030ab6e-b51a-452f-a5f0-5beca5b97a4e.png)  
Dupe level:
![image](https://user-images.githubusercontent.com/55564581/161489617-4a1254b9-917c-4b87-bd26-30b6a8272f11.png)  

Using LDtk 1.1.0

**Comment by deepnight** [comment]
This will be fixed in 1.1.1
