### ISSUE TITLE
External Enums not working properly

### ISSUE THREAD

**Issue by ysaml** [deepnight/ldtk#677]
It returns an error **"Couldn't find any simple Enum in this source fileContent."** when I import an hx file for enums like this

          package util;
          enum Rarity
          {
	          test1;
	          test2;
          }

but when I change it to 
`
          enum Rarity { test1;  test2; }
`
it does not return the error, and it also does not load the enums.

**Comment by ysaml** [comment]
it works when the enums are compressed/ has no spaces or tabs like this:
`enum Rarity{test1;test2;test3}`
I use auto indent on vscode so it's really a bummer

**Comment by deepnight** [comment]
Thanks for reporting!

**Comment by deepnight** [comment]
This should now work in 1.2.0
