### ISSUE TITLE
[Feature Request] Store a `__` property for overlapping world layer neighbors

### ISSUE THREAD

**Issue by spindlebink** [deepnight/ldtk#678]
My single favorite feature in LDtk is the way it handles worlds and levels. Automating neighbor connections in a Metroidvania-style game is a cinch with the `__neighbors` table.

My request is for a similar `__overlappingNeighbors` or a similar property name associated with the neighbors that overlap in world space. Since world layers are a feature enabling stacking levels on top of each other for the purpose of, say, making rooms or tunnels that a player can enter, it seems like a good idea to give levels information about which other levels it overlaps with.

**Comment by deepnight** [comment]
Good idea :) Thanks for the suggestion.

**Comment by deepnight** [comment]
Done in 1.3.5
