### ISSUE TITLE
Default level background color not persisting to external levels

### ISSUE THREAD

**Issue by Trouv** [deepnight/ldtk#679]
LDtk 1.1.3, arch linux

### steps
1. use a project with multiple levels, all using the default background color
2. turn on "Save levels to separate files" in project settings, save
3. Change default level bg color, save project

### expected
The `__bgColor` value in the each level of the `.ldtk` file and in every separate `.ldtkl` file should update to the new default level bg color. 

### actual
None of the levels, or sometimes only a couple, update their `__bgColor` to the new default level bg color. It seems inconsistent how many levels get the changes. The first time it happened, levels 0-3 of my project updated to the correct background color, but not all. When I tried to reproduce, only the 1st level updated. Then when doing it again in the same session, none of the levels updated.

**Comment by deepnight** [comment]
Thanks for reporting.

It seems related to the new cache system introduced in 1.0 🤔

**Comment by deepnight** [comment]
Fixed in 1.2.0
