### ISSUE TITLE
[Feature Request] Allow a toggle for removing out-of-bounds entities

### ISSUE THREAD

**Issue by spindlebink** [deepnight/ldtk#684]
When an entity moves out of bounds, it's currently deleted. This is a helpful feature for some types of games, but others may require out-of-bounds entities. In my current project, I need out of bounds entities for several purposes--portal objects that may be positioned slightly offscreen, background objects which reach only partially into the frame, etc. With that in mind, it'd be good to have a world settings toggle for whether or not out-of-bounds entities get deleted.

**Comment by Cammin** [comment]
I think it would be nice also, however, it might be hard to tell which entity exists on a certain level because it could look like it exists in another.
 Ex. An entity is outside the level bounds, but is now essentially overlapping a neighbouring level.

Maybe entities should automatically be moved to a level if dragged over it, but live within the nearest level when out of bounds and overlapping no level.

**Comment by spindlebink** [comment]
I don't think that's a great idea. If levels are next to each other, that wouldn't solve the original issue of needing entities to be outside of bounds, not in a different level. The point isn't that entities move from one place to another, it's that they sit partially within or fully outside the level.

If telling which level an entity is in is too complicated, entities could be clipped to level boundaries when in world mode, or perhaps faded. While editing a given level, they could be displayed normally as they are.

**Comment by Cammin** [comment]
Yeah, I think that it would be right to make entities live within their respective levels. It would just be visually confusing which level an entity is in as soon as they are displayed out of bounds is my concern, at least. Maybe the blur filter that is applied to non-selected levels can also be applied to entities in this case to communicate that information effectively.

**Comment by deepnight** [comment]
Done in 1.5
