### ISSUE TITLE
[Feature Request] Arrow Key/WASD Navigation on Tilesheet

### ISSUE THREAD

**Issue by chosencharacters** [deepnight/ldtk#689]
This is a really useful feature from OGMO that became a huge part of my workflow. Could we get an option for WASD or Arrow Key Navigation on Tile Sheets? I know there are a lot of keys attached to WASD, but it is the preferred option for right handed users :x Maybe this is a toggle that'd disable the W/A keys if full key rebinding is not possible?

**Comment by deepnight** [comment]
I will see what could be done to support that :)

**Comment by deepnight** [comment]
Done in 1.2.0
