### ISSUE TITLE
[Suggestion] Allow fully customizable pivot point for entities

### ISSUE THREAD

**Issue by FaultyFunctions** [deepnight/ldtk#693]
Hello, I would like to suggest that we be able to enter integers for the pivot point instead of selecting from just the 9 options we have.

I use GameMaker as my game engine and I would like the origin point of the sprite to match the pivot point of the entity in LDtk. This way, things placed in LDtk appear at the appropriate place in GameMaker instead of being slightly off if the origin in GM isn't exactly at one of the 9 pivot locations in LDtk.

**Comment by deepnight** [comment]
Hi,
By "integers",you mean pixel coordinates of the pivot point?

**Comment by FaultyFunctions** [comment]
Yes exactly!

**Comment by deepnight** [comment]
Ok :)

**Comment by deepnight** [comment]
Done in 1.2.0
