### ISSUE TITLE
References do weird things on undo/redo

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#705]

**Comment by MondayHopscotch** [comment]
We have been experiencing a bug where when drawing on a tile layer, upon pressing Ctrl-Z (undo) an entity reference that was recently added gets removed in addition to undoing the most recent change on the tile layer.

Repro looks like:
1. Set entity reference on some entity
2. Switch to tile layer
3. Do some painting
4. Undo
5. Observe that entity reference has been removed

**Comment by deepnight** [comment]
Fixed in 1.2.0
