### ISSUE TITLE
[Bug] name generation for `level depth in world` results in an incorrect name

### ISSUE THREAD

**Issue by gotenxds** [deepnight/ldtk#717]
When adding `level depth in world` the name generated for the level will end with the word "EPTH" for some reason
![ezgif com-gif-maker](https://user-images.githubusercontent.com/3519520/182040757-467e8b2d-dc5b-46c3-a59a-0480610abebe.gif)

**Comment by gotenxds** [comment]
@deepnight Hya, just a reminder, this is still happening, would love a fix for this.

**Comment by deepnight** [comment]
Fixed in 1.5.1
