### ISSUE TITLE
Adding a level in the middle breaks level identifiers

### ISSUE THREAD

**Issue by zommerfelds** [deepnight/ldtk#729]
Repro steps:

1. Create a world with horizontal layout
2. Create a few levels and leave "Level identifier" at "auto"
3. Click add a new level in the middle of some levels
4. Save and load the project in Haxe

This leads to `game/src/LdtkProject.hx:1: characters 24-93 : Duplicate field declaration : Level_2`
If I inspect the `.ldtk` file indeed there are duplicate keys.

If you tick and untick "auto" for all levels, the problem is resolved, as the level names are updated.

Maybe some code is missing to invalidate the names?

**Comment by zommerfelds** [comment]
OK, clicking on every level for each new level is getting annoying for me, so here is another workaround if someone is interested:

![image](https://user-images.githubusercontent.com/1260622/196616712-f7fee660-9148-4b24-ae83-0606928dabd4.png)

Go to the Project Settings, modify the `Default level identifiers` field, save, change it back, save again. All levels should be saved with the correct ID now.

Regarding the issues: the level names are updated correctly in the UI, but maybe there is an issue with the cache. I looked a bit into the code and maybe one way to fix it would be to add something like:

```
level.clearJsonCache();
```
to
https://github.com/deepnight/ldtk/blob/076c2fb9864f58270f9902ad0fede73111ab597f/src/electron.renderer/display/WorldRender.hx#L914

**Comment by deepnight** [comment]
Fixed in 1.2.0, sorry for the inconvenience!

**Comment by zommerfelds** [comment]
Thanks for fixing and the great editor!
