### ISSUE TITLE
haxe renderer.debug.hxml fails

### ISSUE THREAD

**Issue by kgish** [deepnight/ldtk#755]
```
$ haxe renderer.debug.hxml
/home/kiffin/haxelib/deepnightLibs/1,0,72/src/dn/heaps/PixelGrid.hx:53: characters 22-35 : Not enough arguments, expected a:Float

```

**Comment by deepnight** [comment]
Hi,
Make sure you are using the GIT version of my libs:
```
haxelib remove deepnightLibs
haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
```

Does this solve the issue? 🤔

**Comment by kgish** [comment]
See attached screenshot!

Have you documented in more detail the architecture for gameBase and how 
it works?

The current explanation is a bit minimal (for beginners), and I was 
hoping that there would be more structured description about how it all 
fits together.

Perhaps just studying the code would be the best approach. I could 
document it myself and have you review it.

Also, would you recommend using GASM-heaps or would I be better off just 
implementing a simpler ECS?

Regards,

Kiffin

Gishtech
Advanced Software Development for the Web
https://www.gishtech.com

**Comment by deepnight** [comment]
Sure :) 
You will find a 3 parts tutorial about GameBase and Haxe right here: https://deepnight.net/tutorials/

I personally use some simple ECS, which gamebase is based on, but it's really up to your own preferences! My general approach is to recommend to keep things simple.

**Comment by kgish** [comment]
Thanks, I don't know how I could have missed that!

Gishtech
Advanced Software Development for the Web
https://www.gishtech.com

**Comment by deepnight** [comment]
You're welcome!
Is the initial HXML problem solved?

**Comment by kgish** [comment]
Yes it was, thank you.

Gishtech
Advanced Software Development for the Web
https://www.gishtech.com
