### ISSUE TITLE
* symbol in regular expression will cause hang and have to forcely quit if you input something to that field

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#758]
It's reasonable don't to use * symbol because we already apply this regular expression for each letter?
But it will be better to avoid this kind of hang issue.
![image](https://user-images.githubusercontent.com/10916383/206102037-c25c0c3f-0d55-4aea-bf69-5f9381123c6a.png)
![image](https://user-images.githubusercontent.com/10916383/206102052-2d438b8b-bdef-4f8c-ac93-4aebdbdf92a3.png)

**Comment by deepnight** [comment]
Fixed in 1.2.3
