### ISSUE TITLE
[Feature Request] Support group-level Out-of-bounds policy 

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#769]
I have a group which contains 47 rules, for some reason I change my decision and want to change the out-of-bounds policy for each rule. Then I have to change it 47 times.
Could we support a group-level policy which will override all policys of its children rules.
![image](https://user-images.githubusercontent.com/10916383/207373275-e0fb52a8-ac96-46bb-87d0-068939462b33.png)

**Comment by deepnight** [comment]
Done in 1.2.0
