### ISSUE TITLE
[Feature Request] Document/ comment fields

### ISSUE THREAD

**Issue by MichelVGameMaker** [deepnight/ldtk#778]
Hello,
The suggested feature is for the user to have the ability to add comment / documentation to a field for the sake of collaboration.
When the dev. modifies the code within the engine, he/she often needs to adjust field in LDtk and some fields maybe tricky to use for the level designer. So while adding the field, it would be nice to be able to write some comments (like maybe an additional attribute for field... As it is less important, it would be at the end of the list).
As an option, maybe it could show a tooltip in the edition window when selecting an entity in a layer.
If the mouse hovers a field name (nae not value) a tooltio would show. Not sure about the tooltip because it could take some space on screen.... But this is where the level designer needs the doc.   Or it could be a (?) button that triggers a popup
Thanks

**Comment by deepnight** [comment]
Done in 1.2.0
