### ISSUE TITLE
Fix macOS build script

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#783]
YML script: https://github.com/deepnight/ldtk/blob/master/.github/workflows/package-macos.yml
GitHub action: https://github.com/deepnight/ldtk/actions/workflows/package-macos.yml

**Comment by keithclark** [comment]
The [build error](https://github.com/deepnight/ldtk/actions/runs/3823699229/jobs/6505139307#step:10:45) suggests that python is missing.

Looks like [Python 2 was removed from OSX in 12.3](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python) and the Github action is [running in OSX 12.6.2](https://github.com/deepnight/ldtk/actions/runs/3823699229/jobs/6505139307#step:1:4).

This similar issue suggests updating `electron-builder` may fix the problem: https://github.com/electron-userland/electron-builder/issues/6606

**Comment by deepnight** [comment]
Fixed in 1.2.1
