### ISSUE TITLE
[Feature request] Add support for two INTGRID values for the auto-layer assistant 

### ISSUE THREAD

**Issue by gotenxds** [deepnight/ldtk#786]
Hya, I think it would be a great addition if you could define two INTGRID values when generating rules with the auto-layer assistant for when you need specific rules between two values.

It could look like this 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3519520/210384234-3db658ef-73cb-4f55-88b5-6fffeaf11b3f.png">

**Comment by deepnight** [comment]
Done in 1.2.2
