### ISSUE TITLE
[LDtk 1.2.1]Add an option allow us use old style of field value display.

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#788]
I like the new style, but it didn't show difference color between "field name" and "field value", it will have better feeling if we only show one field.
But when we need show several fields or show fields for levels, the old style is far more clear and readable like a "table".
Could we have an option to choose which style globally or entity specifically? As for the level fields, add an global option allow us choose style.
![image](https://user-images.githubusercontent.com/10916383/210496555-25f0c535-36f6-46b1-ad85-4651c3c7ae65.png)

**Comment by deepnight** [comment]
Added in 1.2.2
