### ISSUE TITLE
[Feature Request] Add repeating color cycle for enum default color

### ISSUE THREAD

**Issue by hyperkvlt** [deepnight/ldtk#790]
I wonder whether is it just me or the color palletes used as default color for enum is not exactly repeating in a cycle? 
I tested both color blind mode and normal color mode on **version 1.2.1**, and the results are the following:
- The first default color used is not the first color from the pallete.
- Seems like the default color used is randomly choosen from the pallete.
- **ISSUE** : Sometimes same color reappearing event though it appeared not long before. **(crossed enums in the _screenshot_)**
- **ISSUE** : Sometimes some color hue is more dominant. **(green and purple are dominant in the _screenshot_)**

I think it would be nice if the default color for enum would repeat in a cycle. It just kind of weird to see similar colors appearing frequently.

### SCREENSHOT:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/PG3Crm1/color.png" alt="color" border="0" /></a>

**Comment by Cammin** [comment]
Is this only a problem when entering the hundreds of enum values? I couldn't imagine any project going above maybe 30 enum values, let alone 200+

**Comment by hyperkvlt** [comment]
> Is this only a problem when entering the hundreds of enum values? I couldn't imagine any project going above maybe 30 enum values, let alone 200+

Ah. the enum name is actually Enum2. So it actually just 30 enums. I kinda screenshot it in a rush. Sorry about that.

**Comment by hyperkvlt** [comment]
> Is this only a problem when entering the hundreds of enum values? I couldn't imagine any project going above maybe 30 enum values, let alone 200+

Ah. the enum name is actually Enum2. So it actually just 30 enums. I kinda screenshot it in a rush. Sorry about that.

**Comment by deepnight** [comment]
Current internal palette : 
 ![image](https://user-images.githubusercontent.com/1671695/211013417-9e9bb9eb-2fc2-4167-8732-ea6c083aa970.png)

**Comment by deepnight** [comment]
I tried a different approach in 1.2.3 which should now respect the palette order, while still giving higher priority to "different" colors. Feel free to reopen the issue if this doesn't work as expected :)
