### ISSUE TITLE
Improve world parsing time by using a different file format

### ISSUE THREAD

**Issue by NitroPlum** [deepnight/ldtk#794]
Users with large projects have performance issues parsing them. Could we investigate improving these times by using another format such as BSON or Protocol Buffers? 

You may want to do your own digging but Protocol Buffers seems like a really interesting candidate for parsing speed improvement and has a fairly popular [Haxe library available](https://github.com/nitrobin/protohx)

More research about BSON makes me unsure if the performance would be that much better, but if the JSON parser is that bad in Haxe, maybe BSON would be a huge improvement.

**Comment by baptiste0928** [comment]
BSON is a format created for MongoDB and is not fully compatible with JSON (e.g. it has some additional data types). [MessagePack](https://msgpack.org/) or [CBOR](https://cbor.io/spec.html) would be a better choice.

**Comment by NitroPlum** [comment]
> BSON was created specifically for MongoDB and is not fully compatible with JSON (e.g. it has some additional data types). [MessagePack](https://msgpack.org/) or [CBOR](https://cbor.io/spec.html) would be a better choice.

MessagePack is another option but it seemed like the parsing performance might not be a huge improvement massive improvement. That's why ProtocolBuffers was an interesting solution. The sad truth is we would need to pick one, try it with a large level and see how much it helps.

**Comment by deepnight** [comment]
I've made some quick tests for BSON and it's not a good candidate when it's about parsing speed (it's even worse than JSON in some cases!).

After some thoughts, I came to the conclusion that a binary output would probably not be a good solution to fix the parsing time issue.

The `external levels` option does a *much* better job at fixing parsing time, as it allows parsing of data only when it's actually needed.

Which leads to the main related issue: if you need, say, to find which level contains your "Player start" entity in the world, you are forced to parse almost all levels to find it. Broadly speaking, various cases force the dev to parse everything to find the needle in the haystack.

A good sub-solution to this last problem would be to able to store a "table of content" of some elements somewhere, which makes "locating element X" very fast. See: #806

**Comment by deepnight** [comment]
Table of content added in 1.2.4

![image](https://user-images.githubusercontent.com/1671695/211592628-805728d9-4f19-40fb-b8d3-a597f7a9f043.png)
