### ISSUE TITLE
Auto-layer rules assistant is missing the guide images

### ISSUE THREAD

**Issue by wendelscardua** [deepnight/ldtk#799]
This is how it shows on the release notes gif:

![image](https://user-images.githubusercontent.com/3289356/211216709-042865ea-ccb1-4210-abd1-22013fcc7b2e.png)

But this is what I see on the actual software (version 1.2.3):

![image](https://user-images.githubusercontent.com/3289356/211216729-e26c5bfa-9715-403f-a839-99c960563c2b.png)

**Comment by wendelscardua** [comment]
(for now I've managed to infer some of them by trial-and-error)

**Comment by deepnight** [comment]
Thanks for reporting this bug!

**Comment by deepnight** [comment]
Fixed in1.2.4
