### ISSUE TITLE
Tileset not being properly updated from left menu.

### ISSUE THREAD

**Issue by NitroPlum** [deepnight/ldtk#800]
I removed a tileset that was in use, then replaced it with a new one using the left menu. It seemed fine but the haxe macro broke due to a Null Access Exception. This is because the Default Tileset field was set to null for the Tile layer.

Steps:
1) create a level using some tileset.
2) delete that tileset
3) choose a new tileset for that level from the left menu
4) open tile layer and notice it is set to null.

**Comment by deepnight** [comment]
This should be fixed if you update the Git `master` version the Haxe API.
