### ISSUE TITLE
Performance significatively worsened with version 1.2

### ISSUE THREAD

**Issue by BurgerBob** [deepnight/ldtk#803]
We have a world of roughly 180 small levels.
Performance and input lag were not great with version 1.2.3, with the cursor in editor delayed almost half a second behind the windows cursor, and scrolling fluidity dropping when zoomed out on the world.

From version 1.3, performance and input lag worsened a lot, but only in the case when we are zoomed out on the world, WITH details shown, and there are a lot of text due to world custom properties. So it seems there are performance issues with the changes on text rendering.

**Comment by deepnight** [comment]
Thanks for reporting the issue. 
Please note that you can disable the visibility of some level fields in the world view, which is definitely recommended, even if performance are decent :)

Have you tried switching to the "Table" mode for fields in app settings?

![image](https://user-images.githubusercontent.com/1671695/211287560-1876ba00-7b79-4222-82fb-587f1a51e44a.png)


I'll see what could be done.

**Comment by deepnight** [comment]
Ok I found a few culprits, this should be much better in 1.2.4. 
Do you want a quick build to check the changes?

**Comment by BurgerBob** [comment]
Hi, thanks for the quick response.
Putting entity fields aspects to opaque table solves the problem, so no need for quick build, thanks :)
The input lag issue seems to be separated, so I will create a separate issue.

**Comment by deepnight** [comment]
Ok! 
In 1.2.4, you will be able to use the Outline Text mode again, and it should actually be faster in world view than the Table mode.

**Comment by deepnight** [comment]
My bad, I closed too quickly: what was the input lag issue exactly?

**Comment by BurgerBob** [comment]
I created a separate issue:
https://github.com/deepnight/ldtk/issues/804
