### ISSUE TITLE
[Feature Request] Add "Documentation" field to entity details

### ISSUE THREAD

**Issue by Geokureli** [deepnight/ldtk#810]
Much like how entity fields have a documentation field, I think the entity itself should have information on how it's supposed to be used, particularly how the size of the entity is used. This would be good for teams, and projects that have a rotation of interns or devs.

I imagine it would go here, in extr entity details
<img width="703" alt="Screenshot 2023-01-11 at 2 48 40 PM" src="https://user-images.githubusercontent.com/2609513/211914622-3275d357-0648-4439-a782-0abadb782b89.png">

and much like how documentation works for fields, via mouse hover:
<img width="534" alt="Screenshot 2023-01-11 at 2 52 32 PM" src="https://user-images.githubusercontent.com/2609513/211915481-47e262e0-1820-4395-aef9-3020b68487e1.png">

This would also show via hover, but in the side bar, or perhaps in the property editor, next to the "edit" button (or in both places)
<img width="299" alt="Screenshot 2023-01-11 at 2 53 29 PM" src="https://user-images.githubusercontent.com/2609513/211915528-851e9b5a-4da9-4a81-a2cb-27918aa91a5a.png">

**Comment by Geokureli** [comment]
Additionally, would be nice to be able to customize the coords documentation
 
<img width="578" alt="Screenshot 2023-01-11 at 3 06 25 PM" src="https://user-images.githubusercontent.com/2609513/211917867-569c3d24-33d3-4c29-ad92-97e9c6cdd21a.png">

**Comment by deepnight** [comment]
Good idea! 
This will be in 1.2.5. I added user doc to Entities and Layers.

![image](https://user-images.githubusercontent.com/1671695/212055467-12f26687-0a82-487c-83e3-a93f9e9d0ae7.png)

**Comment by deepnight** [comment]
Added in 1.2.5
