### ISSUE TITLE
Default Entity size should not be the minimum size

### ISSUE THREAD

**Issue by Geokureli** [deepnight/ldtk#812]
I want the default size of my camera focus areas to be half the screen size, because that's just most common use case, but by setting this as the default size, it prevents me from resizing it to be any smaller, which I do not want. If resizing is enabled I should be able to make it any size.

When I saw "Size" I assumed it meant default size, I just realized hover info says "the minimal size" which seems like an odd choice, and doesn't fit how other entity fields behave.

**Comment by deepnight** [comment]
You're right, there's no reason for this default size to act as bounds as well 🤔

**Comment by deepnight** [comment]
Fixed in 1.2.5
