### ISSUE TITLE
[Bug] Entity Icon visual glitch after upgrade to v1.2.5 from v1.1.3

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#825]
![image](https://user-images.githubusercontent.com/10916383/213859046-ef6372cd-3a99-4f06-9641-e0922aa1d747.png)

**Comment by deepnight** [comment]
Thanks for reporting!
Duplicate #817

**Comment by deepnight** [comment]
Fixed in 1.2.6
