### ISSUE TITLE
[Feature Request] Support for decals/sprites

### ISSUE THREAD

**Issue by chosencharacters** [deepnight/ldtk#830]
The ability to drop a static image as a parameter into an entity that replaces the full size (and resizes it to the size of the image) like in Ogmo3 would be really useful. Currently the only method is to make it a tileset and drop it in a reference layer. This is useful for massive static objects like non-tiled foliage and pre-rendered non-tiled rooms.

**Comment by deepnight** [comment]
Closing duplicate #68
