### ISSUE TITLE
Redundant (?) world ID generation causing excessive git diffs

### ISSUE THREAD

**Issue by chosencharacters** [deepnight/ldtk#838]
This has been a longstanding issue, but if possible, can LDTK avoid changing WorldID on regular saves. This was a non-project changing save (no changes to entities and such) and was just a save on one level with no repositioning of the level.

![image](https://user-images.githubusercontent.com/22716528/216714212-a1b21029-4f48-487d-9436-48fdacb3af2b.png)

In past cases this has been up to 300 diffs :(

**Comment by deepnight** [comment]
Hi,
Thanks for reporting this issue.
It's already fixed in upcoming 1.2.6
