### ISSUE TITLE
Inconsistent field ordering between the docs and actual json

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#839]
In the docs for the field instance, the fields are ordered in a particularly nice way. However, in the actual json, the fields are ordered like this, which feels inconsistent:
```json
{ 
"__identifier": "LevelTile", 
"__value": { "tilesetUid": 149, "x": 96, "y": 32, "w": 32, "h": 16 }, 
"__type": "Tile", 
"__tile": { "tilesetUid": 149, "x": 96, "y": 32, "w": 32, "h": 16 }, 
"defUid": 164, 
"realEditorValues": [{"id": "V_String","params": ["96,32,32,16"]}]
}
```
![image](https://user-images.githubusercontent.com/55564581/216795643-67b1a837-de22-4bcd-b4c2-c5ff0079bbaa.png)

If possible, I'd prefer to have the ordering just like how it's shows in the docs, as I'm parsing the json on an individual token basis from top to bottom and it would be convenient for me to check what the `__type` is before the `__value` so that I can exit early if I'm dealing with a field type that doesn't concern me 🙂

**Comment by deepnight** [comment]
Done in 1.3

**Comment by Cammin** [comment]
Awesome! Thanks :)
There was a minor bug with my importer related to this because my code scans through the json values in a specific order, but it's resolved :)
