### ISSUE TITLE
Disable Tile Picker Pop Up if tileset fits in sidepanel

### ISSUE THREAD

**Issue by zissakos** [deepnight/ldtk#840]
My tileset is positioned and zoomed such that it perfectly fits in the side panel:

![screen1](https://user-images.githubusercontent.com/24368712/216815540-67234915-2c03-4dc5-8abf-8abb04b05ad6.jpg)

Yet when I hover over it with the mouse to select a tile, the Pop Up still opens, obsucring half of my level.
Can this be disabled OR only popup if tileset doesn't fit in side panel?
And if it needs to pop up, could it maybe dynamically calculate its width so that the tileset juuust fits ?

![screen2](https://user-images.githubusercontent.com/24368712/216815577-080f58fc-b8d3-4104-902c-d0af27374eb1.jpg)

**Comment by deepnight** [comment]
Done in 1.3.1
