### ISSUE TITLE
Feature request: an option not to display hatches when window is not focused

### ISSUE THREAD

**Issue by jeremyfa** [deepnight/ldtk#850]
It's silly, but as I'm adding support of LDtk to [Ceramic](https://ceramic-engine.com), I often put LDtk editor window and a Ceramic app window side by side to compare their display. But currently, as soon as I lose focus of the LDtk window, I get the hatches overlay that makes looking at the contents rather difficult.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/164094/222978642-d33f8494-1657-434c-9b66-4b3456853277.png">

It would be nice to be able to turn this off in a way or another.

**Comment by deepnight** [comment]
Done in 1.3.1

**Comment by jeremyfa** [comment]
❤️
