### ISSUE TITLE
[Feature request] Make double clicking an entity in an entity layer open the definition for it

### ISSUE THREAD

**Issue by Miepee** [deepnight/ldtk#861]
It would be neat if I double click on the entity here in this list:
![grafik](https://user-images.githubusercontent.com/38186597/224124106-0f481188-7b5d-465c-9577-51b105e332de.png)
That it would open up the entity definition with it selected.

A current workaround is to select it first, and then manually open the entity definition as it will already be selected by default.

**Comment by deepnight** [comment]
In 1.3.0, you can right click an item from the list to open a context menu (including the Edit Entity option)
