### ISSUE TITLE
[Feature Request] Make LTDK localizable / translatable

### ISSUE THREAD

**Issue by Miepee** [deepnight/ldtk#863]
Currently LDTK is only available in English. It would be nice if the tool's text would be available in other languages as well.
Obviously low priority, since the project basically only has one maintainer and no real translation team.

**Comment by deepnight** [comment]
That's a very important and complex thing to do unfortunately. LDtk has some basic support for localization for texts in code, but the whole template system hasn't any. 

So that will probably not happen, sorry :(
