### ISSUE TITLE
[Bug] Long "object" names clip

### ISSUE THREAD

**Issue by Miepee** [deepnight/ldtk#864]
Not sure how to call them properly, since this happens for entities/tilesets/enums, altho the result is *slightly* different for each
entity:
![grafik](https://user-images.githubusercontent.com/38186597/224138672-bd31ab65-6c64-4465-abb3-e7ce96018e1f.png)

enum:
![grafik](https://user-images.githubusercontent.com/38186597/224138925-5b8868d4-4c9d-4988-bc07-bf5c2abcc3a3.png)

tileset
![grafik](https://user-images.githubusercontent.com/38186597/224138757-2874249e-74eb-4861-bc28-7bdb8797d7c7.png)

layer
![grafik](https://user-images.githubusercontent.com/38186597/224138888-d6e83025-490d-41bc-9619-0c3b63c9ae5f.png)

**Comment by deepnight** [comment]
Fixed in 1.3.0
