### ISSUE TITLE
[Interface Soft Lock] Can not remove a value in a Array<Entity ref>

### ISSUE THREAD

**Issue by BurgerBob** [deepnight/ldtk#867]
There is no "garbage can" or "back arrow cross" button to remove a value in a Array of Entity references.

![image](https://user-images.githubusercontent.com/4925468/224350886-e04194d0-922f-441a-a906-767d377286dc.png)

![image](https://user-images.githubusercontent.com/4925468/224351708-86f256d1-a68a-4413-9879-728fc45b985c.png)

**Comment by deepnight** [comment]
Fixed in 1.3.0
