### ISSUE TITLE
Don't enforce Identifiers to start with an uppercase letter

### ISSUE THREAD

**Issue by Miepee** [deepnight/ldtk#877]
For some reason, the LDTK tool enforces all identifiers to start with an uppercase letter. Is there any reason for this? I personally prefer some stuff to start with lowercase letters, and this is a bit irritating.

**Comment by deepnight** [comment]
Hi, you have a setting  for that:
![image](https://user-images.githubusercontent.com/1671695/227252568-e690be49-ef24-49ad-a3d8-a37ed0ef3b9c.png)
