### ISSUE TITLE
[Feature Request] Entity Ref "Allowed References" Should Have an Option to Choose a Specific Entity Type

### ISSUE THREAD

**Issue by Rybadour** [deepnight/ldtk#880]
When creating an entity ref field on an entity I would like to choose an "Allowed References" setting that restricts the reference to only entities of a certain type.

The UI would be similar to "Any entity with one of the specified tags" except you have a dropdown to select an Entity type.

## Reference Screenshot:
![image](https://user-images.githubusercontent.com/305423/227534450-40b08de9-83de-48a6-9962-eed8c96ed9ac.png)

**Comment by BumfuzzledGames** [comment]
As a workaround, I create a tag with the same name as the type and only give entities of that type that tag. But I would also like this feature.

**Comment by deepnight** [comment]
Added in 1.2.6
