### ISSUE TITLE
Project rename operation request

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#910]
LDtk offers a way to rename projects and is the recommended way to rename files as it needs to update with many other assets, like moving level files, or anything else.

For my case with Unity, I have an issue where a companion file of the project file is not additionally renamed when I try renaming a project inside LDtk which results in all objects that reference this asset's GUID being lost.
![image](https://user-images.githubusercontent.com/55564581/236271795-b89b8c49-d537-4e1b-b146-2b14acf2cb66.png)

An explanation:
Unity makes all assets contained in a unity project have a meta file generated alongside, which contains various info, the biggest piece being its object reference. when a meta file is not renamed alongside its source asset, it's deleted and a new one is regenerated which resets its object reference and any other custom info that's configured in the inspector for the asset importer.

I'm not sure if I have any control over this procedure to make this work from my end since the rename operation is handled inside LDtk.
Levels have their meta files maintained just fine in Unity if that's a clue towards a solution to the project rename.
Or, if possible, you could have some code in LDtk that attempts a rename operation for a .meta file if it exists?

**Comment by deepnight** [comment]
> Or, if possible, you could have some code in LDtk that attempts a rename operation for a .meta file if it exists?

That's an easy fix, I'll add that in 1.3.3

**Comment by Cammin** [comment]
Thanks! I'll keep this posted.
And just to be completely sure, like in the image above, the file name to check is the entire source file's name, including the extension(.ldtk), then a `.meta` to the end of it.

Example of a meta file:
`GameProject.ldtk.meta`
I also attached one here so you can experiment with it :)
[GameProject.ldtk.zip](https://github.com/deepnight/ldtk/files/11403048/GameProject.ldtk.zip)

**Comment by deepnight** [comment]
Have all the project files a `.meta` sibling? Specifically, `.ldtkl` separate level files?

**Comment by deepnight** [comment]
Done in 1.3.3

**Comment by Cammin** [comment]
Thanks! I understand that it's a request specific to a game engine, so it might seem like it's not LDtk's responsibility to perform this, but it may be an exception this one time :)
