### ISSUE TITLE
Unexpected overlapping tiles

### ISSUE THREAD

**Issue by jeremyfa** [deepnight/ldtk#912]
I used the auto-layer assistant on a tileset I have, but then when it is rendered from an IntGrid, it seems to overlap multiple tiles so the rounded corners with some transparent pixels don't get rendered as expected.

See attached screenshot and project.

<img width="966" alt="Capture d’écran 2023-05-06 à 17 52 41" src="https://user-images.githubusercontent.com/164094/236634440-52aaaf9d-c20a-4d1c-850a-0c4eb3af7b82.png">

<img width="579" alt="Capture d’écran 2023-05-06 à 17 52 57" src="https://user-images.githubusercontent.com/164094/236634444-82980996-4ccb-4941-9919-0fef532d753c.png">

[Archive.zip](https://github.com/deepnight/ldtk/files/11412706/Archive.zip)

Am I missing something or is this a bug ? 😄

(using LDTK 1.3.2)

**Comment by jeremyfa** [comment]
One additional note:

If I _expand_ the rules to edit them manually, the issue seems resolved if I "stop on match" on the related corner rules:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/164094/236635165-c2209753-92d8-4b68-80d0-7bdabef68af3.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/164094/236635188-f9f041bf-67d4-4de4-99d0-f5b0e8997ba5.png">

Maybe this should be the default when using the assistant?

**Comment by deepnight** [comment]
Thanks for reporting this one!

Hmm, that's due to an important change in 1.3.x 🤔  I'll need to investigate this further and see if it could be fixed automatically. 

I don't think that asking the user for a quite obscure setting like "Stop on Match" would do the job, as it's hard to understand the implications of this option 🤔

**Comment by jeremyfa** [comment]
Nice! Out of curiosity, in what kind of use case we would want the overlap when using the assistant?

**Comment by deepnight** [comment]
Taking advantage of transparency + rules overlapping can drastically reduce the amount of tiles needed in complex situations.

For example, to produce this image (see TopDown sample in LDtk):
![image](https://github.com/deepnight/ldtk/assets/1671695/e806ffa1-0546-4f09-a209-070d4fcae7c6)

You only need this basic tileset: 
![image](https://github.com/deepnight/ldtk/assets/1671695/cb658d53-63e1-494c-bc92-90bdde64226e)

**Comment by jeremyfa** [comment]
I see, thanks a lot for the quick explanation!
