### ISSUE TITLE
Rule value selector broken

### ISSUE THREAD

**Issue by zommerfelds** [deepnight/ldtk#921]
I somehow can't select values to edit my rules anymore. I only see "Anything/nothing":

![image](https://github.com/deepnight/ldtk/assets/1260622/16d7220c-6bee-48e5-9230-05e26f6f8ca5)

The rule is still working, though:

![image](https://github.com/deepnight/ldtk/assets/1260622/627b8245-149e-42dd-8c7c-cf127ab45f4f)

Reloading LDtk doesn't help. Maybe I got to this state by copying a rule from an IntGrid to another AutoValue, but not sure. Will update here if I find more hints. Here is a snippet of my file:
https://gist.github.com/zommerfelds/6b0823ba120df9cf13e5293dca010866

**Comment by zommerfelds** [comment]
Ah, here is a much simpler way to repro:

https://github.com/deepnight/ldtk/assets/1260622/01e0925c-c9da-42e5-905a-5afd90650808

My expectation is that AutoLayer should be able to pick up the values from the IntGrip for the rules.

**Comment by deepnight** [comment]
Fixed in 1.3.4
