### ISSUE TITLE
IntGrid values don't show up on AutoLayer rules when referencing IntGrid. 

### ISSUE THREAD

**Issue by Snowdrama** [deepnight/ldtk#925]
Using 1.3.3 

When you create an AutoLayer that references and IntGrid you can't use the IntGrid values. 

## 1) Create an IntGrid, IntGrid values show up on rules.
![image](https://github.com/deepnight/ldtk/assets/1271916/7308b0b9-e316-4f45-89cf-e4a6a6ecb267)

## 2) Create an AutoLayer that references the IntGrid
![image](https://github.com/deepnight/ldtk/assets/1271916/b165b756-f1cf-4589-9e98-a833ab364dab)

## 3) Create a rule and notice that the IntGrid values are not present
![image](https://github.com/deepnight/ldtk/assets/1271916/8847946f-6b57-4e84-832c-a4a432556c21)

Example Project:
[DemoLevelTest.zip](https://github.com/deepnight/ldtk/files/11560952/DemoLevelTest.zip)

**Comment by deepnight** [comment]
Hi,
Thanks for reporting this one: the bug will be fixed in 1.3.4, probably released by next week.
Sorry for the inconvenience!
