### ISSUE TITLE
Rework or provide examples for custom commands

### ISSUE THREAD

**Issue by GuvBubbs** [deepnight/ldtk#933]
> Custom Commands
> 
> You can now define custom commands to be executed at various moments (when the project is loaded, saved etc.). These commands can be used for whatever your own production pipeline requires. Here are some typical examples:
> 
>     After saving, run a script that parses the JSON and extract all the texts for future localization.
>     When pressing CTRL-R, run your game.
>     After saving, parse the project JSON and check if all levels are properly connected, from your game logic perspective.
> 
> For obvious security reasons, LDtk will always ask you first if you trust the project and want to allow commands from it.

Despite many efforts, I've not been able to run custom commands on PC.

When I run this command in the command prompt.
`pdc "C:\Playdate Dev\Comet SDK\Comet\source" "C:\Playdate Dev\Comet SDK\Comet\build\Comet" `

It build my game from source and dumps it in the correct folder.

The same command in LDtk gives this error.
![image](https://github.com/deepnight/ldtk/assets/22435318/a551c023-d54e-4a08-b4a9-7cbee9007eba)

Running from an EXE or batch file also doesn't work.
If i  add  cmd  to  the start  I get this, and it looks like its thinking, but shows no progress.
![image](https://github.com/deepnight/ldtk/assets/22435318/c8ea8d1e-fc01-4b99-bad3-d504742ceed2)

When I raised this on discord, @deepnight said...
<img width="512" alt="image" src="https://github.com/deepnight/ldtk/assets/22435318/61cd567d-b3af-448f-bedc-30fe209df16d">

I'm looking to speed up my iteration time so I would love for this to be fixed or for me to be told where i'm going wrong.

Regards

**Comment by Cammin** [comment]
I am able to make this work by specifying just a file in LDtk for the command to run.  
The batch file was in the same path as the LDtk project.  
I imagine that then, the batch file could try to execute something else that's more complex.  
I imagine that this would also work for running an .exe file, but I have not tried that.

![image](https://github.com/deepnight/ldtk/assets/55564581/43ed4261-1e04-4499-b2c0-a172a3d69066)  
![image](https://github.com/deepnight/ldtk/assets/55564581/1217e225-c10c-4def-8362-82b3cd05a445)  

And then when I ctrl+r:  
![image](https://github.com/deepnight/ldtk/assets/55564581/4afd3836-03bf-4990-ae41-24ac9682de63)

**Comment by Cammin** [comment]
I can confirm that running applications also works! And the working directory works also.
Unfortunately, it only supplies the working directory, and there is no ldtk file path as an environment variable or command line arg.  
![image](https://github.com/deepnight/ldtk/assets/55564581/080c517f-d1ec-4315-a71d-c5258fb17eed)  

@deepnight This would be a great thing to add to the custom commands: Supply the path of the LDtk file that's currently open.

**Comment by GuvBubbs** [comment]
Confirmed this is working.

Forgive the long delay.
