### ISSUE TITLE
Problem with [Color Selection] position

### ISSUE THREAD

**Issue by hyperkvlt** [deepnight/ldtk#937]
This is something that's been bothering me for quite a long time, but I forgot to bring this up.

When you open the color selection window, its position sometimes feels not quite right. I know that its window position is based on the position of the command icon that bring it up, maybe it sometimes didn't calculate its position properly.

As you can see in the first screenshot, the window position is too low, making it impossible to access the existing color template. And the second screenshot is when its position is right. Well, this happens on me on Window10, I am not sure whether this happens on other system. 

### **When the position too low**
![color selection on bottom](https://github.com/deepnight/ldtk/assets/110368818/483b95d7-ef33-496a-b7ec-525ebd18f65d)

### **When the position is right**
![normal](https://github.com/deepnight/ldtk/assets/110368818/45441a04-5a48-4b82-ad47-4fd0c489fc49)

**Comment by deepnight** [comment]
Thanks for reporting this one! I keep forgetting about it on every updates 😅

**Comment by deepnight** [comment]
Fixed in 1.3.5
