### ISSUE TITLE
UI breaking

### ISSUE THREAD

**Issue by carrascodev** [deepnight/ldtk#942]
the UI i breaking a lot in Mac. Here is a video showing this weirdness:
https://github.com/deepnight/ldtk/assets/4949310/36bc9b1d-0a08-4131-9007-ba59054336c3

**Comment by deepnight** [comment]
Hi,
Is this fixed in 1.4 update?

**Comment by deepnight** [comment]
Last call before closing the issue: any update on the issue?

**Comment by carrascodev** [comment]
Hey, just checked... it's not happening anymore!
