### ISSUE TITLE
作者是否开始考虑提供多国语言版

### ISSUE THREAD

**Issue by hataisx234** [deepnight/ldtk#947]
因为在不同国家，所使用的语言不同，文化的差异造成在使用软件的时候造成困扰，所以希望作者能考虑添加多国语言功能，我知道您忙于软件的完善和新功能的开发，没有时间在这个上面，所以是否将语言部分单独做成外部文件，供不同国家的人根据需要自己翻译自己国家的语言，希望作者能尽快看到我的建议，并采纳，谢谢。

**Comment by deepnight** [comment]
你好，
（谷歌翻译如下，我不会说中文）

目前还没有将 LDtk 翻译成其他语言的计划：我是一个只有 1 人的团队，无法承担支持更多语言所需的技术更改。

我希望你明白  🙂
