### ISSUE TITLE
deepnightLibs/git/src/dn/js/NodeTools.hx:100: lines 100-102 : Too many arguments

### ISSUE THREAD

**Issue by hp951167027** [deepnight/ldtk#957]
deepnightLibs/git/src/dn/js/NodeTools.hx:100: lines 100-102 : Too many arguments

**Comment by hp951167027** [comment]
haxe main.debug.hxml  Error reporting deepnightLibs/git/src/dn/js/NodeTools.hx💯 lines 100-102 : Too many arguments

**Comment by pcloves** [comment]
> haxe main.debug.hxml Error reporting deepnightLibs/git/src/dn/js/NodeTools.hx💯 lines 100-102 : Too many arguments

Hi, how do you solve this issue?
