### ISSUE TITLE
recommendation: add the playdate-metroidvania repo to your API list

### ISSUE THREAD

**Issue by headwinds** [deepnight/ldtk#958]
You can add a Playdate logo near that Lua Love one 

[list of LDTK APis](https://ldtk.io/api/)

I'd like to recommend listing [playdate-metroidvania](https://github.com/colingourlay/playdate-metroidvania). It might help to increase adoption - that's how I learned about LDTK! 

I've only just begun exploring LDTK,  and discovered that when I save my changes in LDTK, the result will almost instantly appear in Playdate simulator. The author of the metroidvania repo provides some nice hooks that watch the files and recompile automatically. So awesome!

**Comment by deepnight** [comment]
Thanks for mentioning that one, I'll have a look :)

**Comment by deepnight** [comment]
Related #273

**Comment by deepnight** [comment]
Added to the website
