### ISSUE TITLE
macOS: Cmd+H does nothing instead of letting OS hide the LDtk window

### ISSUE THREAD

**Issue by beetrootpaul** [deepnight/ldtk#962]
I'm happy for the change made in #960 💛 

Sadly, I am coming back to report two related issues:
1. Right now the `Cmd+H` does nothing. Is it possible LDtk does not pass the shortcut further to the OS?
2. Minor: the shortcut shown in the help sheet still shows cmd/ctrl instead of shift (see screenshot)

<img width="304" alt="screenshot 2023-09-22 at 16 23 40" src="https://github.com/deepnight/ldtk/assets/92947323/e275042d-31ce-480b-9c3c-c98915aa734a">

Note: I can help with debugging on macOS if needed, just let me know 👍

**Comment by deepnight** [comment]
Hi! Thanks for reporting.
Does this issue happens with any other OS wide `Cmd` shortcut, or is this only for `Cmd+H`?

**Comment by beetrootpaul** [comment]
> Does this issue happens with any other OS wide `Cmd` shortcut, or is this only for `Cmd+H`?

(all below run when the LDtk is in focus)

Some macOS default shortcuts (sadly, only 3 of them are in form of `Cmd+letter`, I am unaware of others):

- ✅ Cmd+Space - opens Spotlight on top of all windows
- ✅ Cmd+Ctrl+Q - locks the screen 
- ✅ Cmd+Q - closes the app
- 🛑 Cmd+M - should minimize the window to the Dock, but does nothing in LDtk
- 🛑 Cmd+H - should hide the window (this one we know about already)
- ❓ Ctrl+Cmd+F - should make LDtk full screen, but is not required to be supported (according to this [randomly googled Apple support page (link)](https://support.apple.com/en-us/HT201236))
- ✅ Cmd+Tab - opens app switcher
- ✅ Cmd+Shift+4 - initiates a screenshot region flow

Some shortcuts that I have no idea if are handled by macOS or by LDtk itself (probably the latter):

- ✅ Cmd+W - closes the currently open project

Some shortcuts that work, but are handled by Rectangle app and might have been customized by me:

- ✅ Ctrl+Opt+Left/Right - moves LDtk to the left/right half of a screen
- ✅ Ctrl+Enter - makes LDtk occupy entire screen

Some shortcuts that work, but are handled by AltTab app (if running):

- ✅ Cmd+Tab - opens AltTab app switcher

**Comment by deepnight** [comment]
This should be fixed in 1.5, but some testing is needed to confirm that this issue is solved :)

**Comment by beetrootpaul** [comment]
> This should be fixed in 1.5, but some testing is needed to confirm that this issue is solved :)

Great! Let me know if you need me to check it on my machine 👍

**Comment by beetrootpaul** [comment]
Not sure if related, but sounds like: I saw you info about a fix for Cmd shortcuts in another issue 👉 https://github.com/deepnight/ldtk/issues/1024#issuecomment-1872515559

So I built ldtk locally (for the first time) from `dc348af58d846554cb3bafb9452f245aec275196` commit (the one which checked out by default). 

Cmd+H and Cmd+M both work OK ✅ 👍 

BTW the misleading shortcut info is still there (I scroll up in this issue and see it was supposed to be shift, but is still shown as cmd):

![screenshot 2023-12-30 at 13 20 54](https://github.com/deepnight/ldtk/assets/92947323/4cf58131-e102-4db5-a536-749abd4ffb6e)

But yeah, the main topic of this issue seems fixed, at least on my machine 😄

**Comment by deepnight** [comment]
This should be fixed in last commit: https://github.com/deepnight/ldtk/commit/caebfe14538cc9658fe1a4508add4eef79b23c26

Also, it seems like your CSS wasn't rebuilt from the SCSS (Sass) in your local version (the "CTRL" black shadow should no longer be here) 🤔

**Comment by deepnight** [comment]
Fixed in 1.5

**Comment by beetrootpaul** [comment]
(continuing the discussion only out of curiosity; no expectations on my side)

> This should be fixed in last commit: https://github.com/deepnight/ldtk/commit/caebfe14538cc9658fe1a4508add4eef79b23c26

ah, so I was checking out the wrong one 🙈 Then: interesting that Cmd+H worked OK for me 🤔 May it be the commit I checked out (dc348af58d846554cb3bafb9452f245aec275196) was from before the issue was introduced? 

> it seems like your CSS wasn't rebuilt from the SCSS (Sass) in your local version

How do I rebuild CSS?

What I did:
1. cloned fresh git@github.com:deepnight/ldtk.git
2. looked at https://github.com/deepnight/ldtk#compiling-master-branch
3. tried `haxe` and realized I have no such command
4. downloaded and installed Haxe from its homepage
5. run `haxe main.debug.hxml`, which resulted twice or thrice with an error, each one with an info what to do to fix it (like: install haxelib, install some dependency)
6. realized I should start at https://github.com/deepnight/ldtk#building-from-source , so this time I run `haxe setup.hxml`, `npm i`, `haxe main.debug.hxml`, `haxe renderer.debug.hxml`, then `npm run start`

**Comment by deepnight** [comment]
To rebuild CSS, you need to use a SASS compiler. 

The easiest way to do that is to use VScode and add a plugin such as DartJS SASS compiler (https://marketplace.visualstudio.com/items?itemName=codelios.dartsass).

With the plugin enabled, load and save the SCSS file to build the .css and .min.css files.
