### ISSUE TITLE
When selecting a different entity the panels on the right side do not fully refresh

### ISSUE THREAD

**Issue by 00alia00** [deepnight/ldtk#974]
Notice in the following gif that i need to select the value before it refreshes, this makes it very error prone if you have a lot of entites
Windows / LDtk 1.4.1
![LDtk_VkPn37CDxE](https://github.com/deepnight/ldtk/assets/537506/9863187c-95f2-4d0e-95e1-841a588efc49)

**Comment by deepnight** [comment]
Hi!
Sorry about this bug, it's a regression probably introduced in 1.4.x . 

I fixed it in 1.5 version (coming in the next few days)
