### ISSUE TITLE
Allow negative resize and flipping for entities

### ISSUE THREAD

**Issue by Gamer-XP** [deepnight/ldtk#977]
As simple as that - allow to flip entities, resizing them to negative sizes. 
Could be useful, for example, in:
1. Enabling to choose looking direction for entities. Usually must-have for platformers.
2. Some resizeable objects may have their pivot just as important as their size. Being unable to scale them in opposite direction limits thing you can do with them.

The way it can be implemented:

Replace resize bool value with bitmask enum
```
enum
{
   Disabled : 0
   CanResize: 1
   CanFlip : 2
}
```

With this, loading old bool as int value should preserve existing data.

CanFlip flag allows to have negative size for given axis. 
If it's not resizeable - you can still flip entity left/right. I suggest making it as a single dragable dot on the current forward/down direction, the same way as you got 2 dots for resizeable entities.

**Comment by deepnight** [comment]
I don't plan to support negative resizing as the feature would overlap with planned "Flip X/Y" states of an object, wihle producing the exact same result. 

I mentioned this issue in #978 for future reference 👍
