### ISSUE TITLE
defaultEntityWidth and defaultEntityHeight can contain null

### ISSUE THREAD

**Issue by stinkytoe** [deepnight/ldtk#980]
I am writing an importer for the rust bevy engine for your LDtk json format. I used the JSON_SCHEMA.json file you provided on your website. The version in the repo as of today seems to be the same. 

defaultEntityWidth and defaultEntityHeight only have the integer type listed, but the editor generates a null for these fields when I save a project. This prevents my parser from being able to deserialize these values. I'm using serde_json, if that's relevant. 

I was able to work around this by manually editing the schema and adding both integer and null as possible types. I don't think I'll need to actually use this field, so no worries if the type doesn't agree in the future. 

Request: either change the schema to include null as an option, or change the editor to fill these with sane values by default. 

BTW, LDtk is awesome and you're awesome!

**Comment by deepnight** [comment]
Thanks for reporting this issue, I'll have a look for next update 🤔

**Comment by Cammin** [comment]
I have also had this problem. Here was my process:

When making a new blank project, 2 fields in the json file are null. Any attempts at saving the project don't write these null values to 16 either.
When I close and then reopen the project, and then save, then it will properly write these null values to 16.

The big problem is, these values are not explicitly nullable in the json schema, causing my json deserializer to fail! 
Either these fields should be nullable in the json schema, or LDtk should never be able to write these null values in the first place.

![image](https://github.com/deepnight/ldtk/assets/55564581/a9a7c277-700d-45e0-bff8-b26417244407)

**Comment by deepnight** [comment]
Fixed in 1.5
