### ISSUE TITLE
World view in full detail

### ISSUE THREAD

**Issue by tynberry** [deepnight/ldtk#981]
It would be nice to see levels in full detail even while in world view or in level view, so that you can get a better picture of your world and can align rooms better especially with similarly colored tiles.

This could be customizable if all levels would be in full detail or there would be a radius where levels are in full detail, so that even low-end computers can benefit from this.

**Comment by deepnight** [comment]
Done in 1.5

![image](https://github.com/deepnight/ldtk/assets/1671695/b4ed304f-50ba-43bf-a7f3-a79a6e0cc7a3)
