### ISSUE TITLE
Rule editor performance and memory usage issues

### ISSUE THREAD

**Issue by ykt-dev** [deepnight/ldtk#984]
Rule editor becomes unresponsive and eats memory in gigabytes if I set up a lot of rules. 

Here is a minimal project to reproduce the issue, it has hundreds of rules generated by assistant
[rule_editor.zip](https://github.com/deepnight/ldtk/files/13057324/rule_editor.zip)

Launch it and try opening and then closing rules tab to see for yourself.

On fresh launch it is slow but bearable, but every interaction within rule editor gets progressively slower and takes up memory and doesn't free it when I close rule editor.

**Comment by deepnight** [comment]
This should be waaaay better in 1.5 :) Thanks for reporting this and for the demo map.
